### ISSUE TITLE
CPE update failed

### ISSUE THREAD

**Issue by wangqian0818** [future-architect/vuls#1015]
Hello, I have a problem I need your help with.

In the past few days, when I updated CPE, I got a timeout connection error, which caused my update to fail. I've tried many times and I still make this mistake. There was no such problem a week ago. Is there a solution? When updating CPE, can you specify that only the last few years are updated as CVE? Otherwise, it would take too long.

よろしくお願いします。お疲れ様でした。

Screenshot of update failure:
![image](https://user-images.githubusercontent.com/57213445/85968530-eea3e300-b9f7-11ea-9315-6055b6a1b2da.png)

**Comment by kotakanbe** [comment]
Update to the latest version, and then retry plz. 
Maybe OOME occurred.

This pull request may have fixed it.
https://github.com/kotakanbe/go-cpe-dictionary/pull/19
