### ISSUE TITLE
Supporting EC2 Instance Connect

### ISSUE THREAD

**Issue by shinobe179** [future-architect/vuls#1016]
I plan to use Vuls / FutureVuls on AWS.
When we use remote scanning, we must prepare SSH key-pairs, it needs maintenances frequently.
I hope Vuls scanner to support EC2 Instance Connect to make remote scanning easy.

**Comment by kotakanbe** [comment]
In an environment that increases and decreases instances or the key pair changes frequently, it's easier to use FutureVuls to scan in local scan mode and upload the results to SaaS.
