### ISSUE TITLE
The scan results are incorrect

### ISSUE THREAD

**Issue by wangqian0818** [future-architect/vuls#1024]
Hello, I installed Vuls manually. Vuls is really great and can meet the requirements, but I have some small questions to ask you:

1. In the scanning process, I found that there was no LDAP installed on the host of the scanned end, but the scanning results showed LDAP related vulnerabilities, which was very strange.
![image](https://user-images.githubusercontent.com/57213445/88289839-709dd800-cd28-11ea-8dc9-0486d46cb299.png)

2、In the scanning result, the low version vulnerability of Chrony shows the vulnerability that existed before version 1.29, but my software version number is 3.4, so this vulnerability should not be scanned.
![image](https://user-images.githubusercontent.com/57213445/88289918-8dd2a680-cd28-11ea-9c40-c5ea1ac7216d.png)
![image](https://user-images.githubusercontent.com/57213445/88289944-975c0e80-cd28-11ea-897b-80bc8fd83958.png)

お願いします

**Comment by kotakanbe** [comment]
Hi, @wangqian0818 

Please let me know the type and version of the OS to be scanned :)
Would you paste the JSON of the scan result if possible?
Please check the content before uploading and mask sensitive information.
There is a json in /path/to/vuls/results/current/.
