### ISSUE TITLE
Is there a way to talk to vuls report via API?

### ISSUE THREAD

**Issue by jirib** [future-architect/vuls#1038]
IIUC after I send data via POST method (eg. via curl) to Vuls server, Vuls server does NOT return a JSON which is the result of the Vuls check.

Am I able to  get JSON report somehow directly from Vuls server or to trigger 'report' function via API?

Example:

* a job will POST via curl list of RPMs on a server
* (there's report saved on the Vuls server, started with `vuls server -debug -listen 0.0.0.0:5515 -to-localfile -format-json`)
* *now I'like to get this report via HTTP protocol for automated parsing (JSON) or to trigger `vuls report` for a notification

Only workaround I see to get any report without human intervention, is to monitor *results-dir* for changes (inotify) and run `vuls report`.

**Comment by Jiab77** [comment]
@jirib, did you looked at: https://vuls.io/docs/en/vulsrepo.html and https://github.com/ishiDACo/vulsrepo?

When using the client -> server mode, the report can be directly displayed in VulsRepo without having to run `vuls report`.

See here for more details about the server mode: https://vuls.io/docs/en/usage-server.html

**Comment by jirib** [comment]
> @jirib, did you looked at: https://vuls.io/docs/en/vulsrepo.html and https://github.com/ishiDACo/vulsrepo?
> 
> When using the client -> server mode, the report can be directly displayed in VulsRepo without having to run `vuls report`.
> 
> See here for more details about the server mode: https://vuls.io/docs/en/usage-server.html

I'm sorry, I don't work with Vuls anymore, I can't help anymore.
