### ISSUE TITLE
Failed to fetch redhat vulnerability DB

### ISSUE THREAD

**Issue by snowpamela** [future-architect/vuls#1046]
### ERROR

it is failed to fetch redhat DB everyday since 0901(Tue),
but it can be successful from data of 2020-01-01,only 2020
could be downloaded.(2019,2018,2017 also failed)

**_is there any idea about this issue?_**

**error log:**
[vulsuser@infrastsec11nc log]$ /home/vulsuser/go/bin/gost fetch redhatapi --dbpath=/home/vulsuser/gost.sqlite3 --htttp-proxy=http://yum-proxy.niftyzone.local:8080
[Thu Sep 03 11:40:20.311 2020] 
[Thu Sep 03 11:40:21.786 2020] INFO[09-03|11:37:56] Initialize Database 
[Thu Sep 03 11:40:21.786 2020] INFO[09-03|11:37:57] Opening DB.                              db=sqlite3
[Thu Sep 03 11:40:21.826 2020] INFO[09-03|11:37:57] Migrating DB.                            db=sqlite3
[Thu Sep 03 11:40:21.826 2020] INFO[09-03|11:37:57] Fetch the list of CVEs 
[Thu Sep 03 11:41:17.098 2020] EROR[09-03|11:38:52] Failed to fetch the list of CVEs.        err="unexpected end of JSON input"
[Thu Sep 03 11:41:17.098 2020] unexpected end of JSON input

[Thu Sep 03 10:54:58.628 2020] [vulsuser@infrastsec11nc log]$ /home/vulsuser/go/bin/gost fetch redhatapi --after 2020-01-01 --dbpath=/home/vulsuser/gost.sqlite3 --htttp-proxy=http://yum-proxy.niftyzone.local:8080
[Thu Sep 03 10:55:15.724 2020] 
[Thu Sep 03 10:55:15.766 2020] INFO[09-03|10:52:50] Initialize Database 
[Thu Sep 03 10:55:15.766 2020] INFO[09-03|10:52:50] Opening DB.                              db=sqlite3
[Thu Sep 03 10:55:15.766 2020] INFO[09-03|10:52:50] Migrating DB.                            db=sqlite3
[Thu Sep 03 10:55:15.766 2020] INFO[09-03|10:52:50] Fetch the list of CVEs 
[Thu Sep 03 10:56:13.664 2020] INFO[09-03|10:53:48] Fetched 1372 CVEs 

* Gost version
$ go/bin/gost -v
    gost 76d68fe

* Vuls environment:
  CentOS 7

* Vuls version
   0.10.0

**Comment by pawelsocha** [comment]
Look like a typo in command line. `--htttp-proxy` should be `--http-proxy`

**Comment by kotakanbe** [comment]
Fetch with `gost fetch redhat` instead of `gost fetch redhatapi`. 
You'll get the same information faster.
Red Hat's API is too slow.

**Comment by kotakanbe** [comment]
If you're still having problems, you can re-open it.

**Comment by snowpamela** [comment]
> Look like a typo in command line. `--htttp-proxy` should be `--http-proxy`

it's just a clerical error, i used  `--http-proxy` in fact,
thank you for discover it
and it be successful downloaded since 9/4(Fri) that there is no any changed，
maybe is a network error, or redhat server problem

**Comment by snowpamela** [comment]
> Fetch with `gost fetch redhat` instead of `gost fetch redhatapi`.
> You'll get the same information faster.
> Red Hat's API is too slow.

we used `gost fetch redhat` at the beginning, but it always failed at one time,
so we change to api. maybe can retry, thanks for your  information
