### ISSUE TITLE
vuls-beats

### ISSUE THREAD

**Issue by necrose99** [future-architect/vuls#1047]
https://www.elastic.co/guide/en/beats/devguide/current/new-beat.html

(https://www.elastic.co/siem )

send vuls/detections alerts as a copy  that are found to elastic search siems or logstash etc..

**Comment by kotakanbe** [comment]
Pull request welcome :)

It would be good to put it under contrib.
https://github.com/future-architect/vuls/tree/master/contrib

**Comment by necrose99** [comment]
At some future point, 
https://github.com/future-architect/vuls-beats , or similar for agent , if the vulsrepo,  viewer bogs up , or ie malware alerts tick up against a vuln in siem , Anylysts can put action plans  to effect.
(https://github.com/wazuh uses vuls as vulnerability... , ) 
However recently been in inte.... for a ro...l.e.. hmm hmm.
Were they ... could use vul.... sc.. and run elastic siem.

**Comment by kazuminn** [comment]
@nealmcb I try implement from now . https://github.com/kazuminn/vuls-beats
but i don't  know if it can be released.
very sloory implement

**Comment by kazuminn** [comment]
@necrose99 I have released https://github.com/kazuminn/vulsbeat .

**Comment by necrose99** [comment]
this with ie https://github.com/wazuh  , or free elastic seiem  or elastic
based siem /SELKS or many open source siems , should be able no to get vuls
alerts

https://github.com/HASecuritySolutions/VulnWhisperer/ or others in future
should be able to consume alerts
