### ISSUE TITLE
[RFC] Consider following the GNU/POSIX standards for command line interface

### ISSUE THREAD

**Issue by jody-frankowski** [future-architect/vuls#106]
Please consider following the GNU/POSIX standards for command line interface. More precisely at least using "--" for long options.
See [GNU](https://www.gnu.org/prep/standards/html_node/Command_002dLine-Interfaces.html) and [IEEE](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html)

**Comment by kotakanbe** [comment]
Thanks for sending RFC.

Vuls uses google/subcommands for optparse.
https://github.com/google/subcommands

Vuls supports below format for now.
```
./vuls scan --help
./vuls scan -help
./vuls scan -h
```
