### ISSUE TITLE
Support One liner scan for Oracle Linux

### ISSUE THREAD

**Issue by giladsh1** [future-architect/vuls#1061]
Hello, 
I've looked in your documentation, and I see that you do not currently support a one liner scan for Oracle Linux.
Is this something that is in the project's roadmap and you plan to add at some point?

Thank you

**Comment by kotakanbe** [comment]
@giladsh1 

Maybe it works in a similar way to RHEL. Give it a try.

**Comment by giladsh1** [comment]
hello @kotakanbe 
thank you for you response.
even if that works, there is no way to make sure that are no false positives or missing CVEs...

**Comment by Jiab77** [comment]
Hi @giladsh1, you're right and the `one-liner` command is missing from the documentation, I'll add it after this comment. Here is what I'm using in my [own](https://github.com/Jiab77/vuls-scripts/blob/master/vuls-client-scan.sh#L101) project:

```
# Generate the package list
echo -e "`rpm -qa --queryformat "%{NAME} %{EPOCHNUM} %{VERSION} %{RELEASE} %{ARCH}\n"`" > $PACK_LIST

# Generate the vuls server query
curl -X POST -H "Content-Type: text/plain" -H "X-Vuls-OS-Family: `awk '{print tolower($1)}' /etc/oracle-release`" -H "X-Vuls-OS-Release: `awk '{print $5}' /etc/oracle-release`" -H "X-Vuls-Kernel-Release: `uname -r`" -H "X-Vuls-Server-Name: `hostname`" --data-binary @$PACK_LIST http://${VULS_SERVER}:5515/vuls > $LOCAL_REPORT
```

**Comment by Jiab77** [comment]
@giladsh1 and @kotakanbe, please have a look at this pull request [#127](https://github.com/vulsdoc/vuls/pull/127) to have a better idea of the changes.

**Comment by giladsh1** [comment]
thank you very muck @Jiab77 !
