### ISSUE TITLE
Can Vuls be used on a Linux without package manager?

### ISSUE THREAD

**Issue by matzoius** [future-architect/vuls#1064]
Hi,
I installed Vuls on a Docker container and I am scanning the host via SSH. The host I am scanning is a minimal Linux built in Yocto (based on poky-dunfell) and it doesn't have a package manager. After I configured Vuils, I ran a scan and I am getting this error:

`dpkg-query: not found`

(Running this command on the host outputs the same error.)

How can I scan with Vuls an OS without having the package manager installed on the scan target?

Thanks
Andrei

**Comment by kotakanbe** [comment]
You can scan by converting all the installed source versions (upstream versions) to CPE and scan with CPE scan mode.
But it would be a lot of work.
https://vuls.io/docs/en/usage-scan-non-os-packages.html#cpe-scan (edited) 

Vuls right now doesn't support yocto, which doesn't have a package manager, but if there's a vulnerability database for yocto that's publicly available, it may be possible to scan for it without defining CPE.

Try looking for yocto's OVAL database.
