### ISSUE TITLE
Support RancherOS 

### ISSUE THREAD

**Issue by okamuroshogo** [future-architect/vuls#107]
I want to use the vuls in RancherOS.
Could you to the corresponding.

**Comment by kotakanbe** [comment]
I have never used RancherOS.
Do you know how to detect CVEs that are contained in the RancherOS?


If you are Japanese, you can communicate in Japanese at github-vuls slack team.
https://docs.google.com/forms/d/10_pNUFZjgEoCdbbuLowBjcuNI6GOxUT6s4Sxd4vhOyE/viewform?c=0&w=1
Join #japanese channel

**Comment by bscott** [comment]
RancherOs is built using containers, not sure CVE scanning applies here, unless you mean hosting Vuls on RancherOS.

**Comment by kotakanbe** [comment]
Nobody wants
