### ISSUE TITLE
Update "WordPress Vulnerability Database" URL

### ISSUE THREAD

**Issue by kotakanbe** [future-architect/vuls#1079]
https://github.com/vulsdoc/vuls/pull/122

**Comment by shigechika** [comment]
I am using vuls v0.13.6 build-20201204_120609_101c44c.
I have a the following problem. Does this issue fix my problem?

`Dec  5 08:41:39 vuls vuls-daily: time="Dec  5 08:41:39" level=error msg="Failed to fill with integration:\n    github.com/future-architect/vuls/report.FillCveInfo\n        /home/vuls/go/src/github.com/future-architect/vuls/report/report.go:205\n  - Failed to fetch from WPVulnDB. Check the WPVulnDBToken in config.toml. err:\n    github.com/future-architect/vuls/report.WordPressOption.apply\n        /home/vuls/go/src/github.com/future-architect/vuls/report/report.go:476\n  - Not a semantic versioning:\n    github.com/future-architect/vuls/wordpress.FillWordPress\n        /home/vuls/go/src/github.com/future-architect/vuls/wordpress/wordpress.go:158\n  - Malformed version: "`

**Comment by kotakanbe** [comment]
https://github.com/future-architect/vuls/pull/1089
