### ISSUE TITLE
Add sudo support for prepare

### ISSUE THREAD

**Issue by rothgar** [future-architect/vuls#11]
When configuring a server I have ssh access via my user but package installation requires sudo.

There should be an option to use sudo to the config file to allow a non-root user to prepare the OS.

An example would be

```
[servers]

[servers.172-31-4-82]
host        = "172.31.4.82"
port        = "22"
user        = "ec2-user"
sudo        = "true"
keyPath     = "/home/ec2-user/.ssh/id_rsa"
```

There may be some consideration to add a sudo_password option if passwordless sudo ( NOPASSWD ) is not configured. I don't like having passwords in config files so maybe it would just be a pre-requirement of the user installing the packages or have vuls prompt for a sudo password before sshing into a system.

**Comment by kotakanbe** [comment]
- sudo
Prepare subcommand installs required packages to scan vulnerabilities.  (see https://github.com/future-architect/vuls#usage-prepare)
So, sudo option is needed If your target server's OS is CentOS(yum-plugin-security, yum-plugin-changelog) or Debian(apptitude).
Ubuntu, RHEL and Amazon Linux are no need to run prepare before scanning.

- Plain password in config file
I think there are two options. I am going to implement in the near future :-)
    + aws cli
    + encrypt ( something like chef data bag)

**Comment by kotakanbe** [comment]
I implement -ask-sudo-password option and -ask-key-password option. 
Now, you can avoid to define plain password in config.

see #35
