### ISSUE TITLE
I'd like to organize the result directory for the tenant.

### ISSUE THREAD

**Issue by dokuma** [future-architect/vuls#1101]
# Objective
I'd like to organize the result directory for the tenant.

## Backgrounds
I'm trying to figure out how to use the Vuls with VulsRepo. So I realize that there is no way to organize result file except ScanTime. Let me share the image what I thought for easy to understand.

<img width="436" alt="vulsrepo_figure1" src="https://user-images.githubusercontent.com/1147534/103118439-34451e00-46b2-11eb-88da-d52e8aca8c4b.png">

## How
I'm mentioning about using Vuls as HTTP Server. I would figured out the solution by add HTTP Header like `X-Vuls-Result-Prefix: tenant1`, then combine the prefix and result directory that is provided.

**Comment by kotakanbe** [comment]
@dokuma 

There is no plan to support this on the vuls side.
How about modifying vulsrepo or creating your own shell script?

**Comment by dokuma** [comment]
@kotakanbe 
Thank you for your comment. It's OK, I already have an idea do this different way.
