### ISSUE TITLE
WARN [localhost] The OVAL name of the running kernel image {Release:3.19.0-25-generic Version: RebootRequired:false} is not found. So vulns of `linux` wll be detected. server: ubuntu

### ISSUE THREAD

**Issue by KingXS** [future-architect/vuls#1108]
# What did you do? (required. The issue will be **closed** when not provided.)
A warning appears when I scan a remote host

# What did you expect to happen?
WARN [localhost] The OVAL name of the running kernel image {Release:3.19.0-25-generic Version: RebootRequired:false} is not found. So vulns of `linux` wll be detected. server: ubuntu

# What happened instead?
WARN [localhost] The OVAL name of the running kernel image {Release:3.19.0-25-generic Version: RebootRequired:false} is not found. So vulns of `linux` wll be detected. server: ubuntu

Please re-run the command using ```-debug``` and provide the output below.

# Steps to reproduce the behaviour

# Configuration (**MUST** fill this out):

* Go version (`go version`):

* Go environment (`go env`):

* Vuls environment:

Hash : ____

To check the commit hash of HEAD
$ vuls -v

or

$ cd $GOPATH/src/github.com/future-architect/vuls 
$ git rev-parse --short HEAD 

* config.toml:

* command:

**Comment by kotakanbe** [comment]
Since there are no false positives, I will consider display as info instead of warn.
