### ISSUE TITLE
The documentation is inaccurate about Fetch OVAL(redhat)

### ISSUE THREAD

**Issue by nibiwodong** [future-architect/vuls#1111]
https://vuls.io/docs/en/tutorial-docker.html
![image](https://user-images.githubusercontent.com/17465789/103347866-31439680-4ad3-11eb-8283-80d496c0a405.png)

redhat 8 is avaliable
expect is：
`docker run --rm -it \
    -v $PWD:/vuls \
    -v $PWD/goval-dictionary-log:/var/log/vuls \
    vuls/goval-dictionary fetch-redhat 5 6 7 8`

**Comment by kotakanbe** [comment]
Pull request welcome :)

![image](https://user-images.githubusercontent.com/534611/104667139-bc01d380-5718-11eb-8f86-4f3822deb341.png)

**Comment by nibiwodong** [comment]
resolved
https://github.com/vulsdoc/vuls/pull/138
