### ISSUE TITLE
The document about Fetch OVAL  redhat version need add version8

### ISSUE THREAD

**Issue by nibiwodong** [future-architect/vuls#1112]
https://vuls.io/docs/en/tutorial-docker.html
![image](https://user-images.githubusercontent.com/17465789/103347866-31439680-4ad3-11eb-8283-80d496c0a405.png)

redhat 8 is avaliable
expect is：
`docker run --rm -it \
    -v $PWD:/vuls \
    -v $PWD/goval-dictionary-log:/var/log/vuls \
    vuls/goval-dictionary fetch-redhat 5 6 7 8`

**Comment by Jiab77** [comment]
Duplicated with: #1111
