### ISSUE TITLE
cannot scan host sever

### ISSUE THREAD

**Issue by yalexn** [future-architect/vuls#112]
Hi, my name is Alex.
I really like the work you do however, I am having trouble using VULS.
How do I check the vulnerability of the server VULS is installed in?

**Comment by kotakanbe** [comment]
I want to be your help. 
Can you give me more details?
・Are you trying with latest version of Vuls? (If not, please update Vuls)
・OS
・The error message (--debug option)

**Comment by yalexn** [comment]
I just installed it today. I believe it's the newest version unless I must update after installing.
I am trying it on UBUNTU.
The error message is
 err: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none], no supported methods remain, Retrying in 4.506218855s...

Would you be able to help? I am not very experienced in this field, sorry if this is an easy fix.

**Comment by kotakanbe** [comment]
Check if the user defined in config.toml can ssh to the server.
see https://github.com/future-architect/vuls#step2-ssh-setting

**Comment by yalexn** [comment]
I just did this and I went on without a password had a log in error,
 also tried it with a password still a login error.
Could there be another password I am not aware about?
![image](https://cloud.githubusercontent.com/assets/20202488/16449433/7bfe7bca-3e32-11e6-8f94-d9038545e7bb.png)

**Comment by kotakanbe** [comment]
If you use ssh-key with password, Please specify -ask-key-password option.

See https://github.com/future-architect/vuls#usage-prepare
```
  -ask-key-password
        Ask ssh privatekey password before scanning
  -ask-sudo-password
        Ask sudo password of target servers before scanning
```

**Comment by yalexn** [comment]
Thank you for your help! I was able to solve this problem!
