### ISSUE TITLE
I got a error output as the description when running the scan.sh

### ISSUE THREAD

**Issue by ZhixiongChi** [future-architect/vuls#1184]
The executed command:
#./update-all.sh
...
#./scan.sh 
Using default tag: latest
latest: Pulling from vuls/vuls
Digest: sha256:3aba376c0bab1adc59a84b8ec59ace3e050b7438e1d4dd29855e4002dd5d9ef6
Status: Image is up to date for vuls/vuls:latest
[Feb 25 10:23:54]  INFO [localhost] vuls-v0.15.9-build-20210225_011640_518f4dc
[Feb 25 10:23:54]  INFO [localhost] Validating config...
[Feb 25 10:23:54]  INFO [localhost] Detecting Server/Container OS... 
[Feb 25 10:23:54]  INFO [localhost] Detecting OS of servers... 
[Feb 25 10:23:54] ERROR [localhost] Failed to configtest: Failed to init servers. err:
    github.com/future-architect/vuls/scanner.Scanner.Configtest
        /go/src/github.com/future-architect/vuls/scanner/serverapi.go:101
  - No scannable host OS:
    github.com/future-architect/vuls/scanner.Scanner.initServers
        /go/src/github.com/future-architect/vuls/scanner/serverapi.go:229

#cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core)

Did I miss something so that it couldn't detect the server distro?
Thanks.

**Comment by rtuk** [comment]
I had the same problem when installing the version from the master branch
I switched to tags/v0.15.9 and rebuild vuls, now it works

**Comment by ZhixiongChi** [comment]
> I had the same problem when installing the version from the master branch
> I switched to tags/v0.15.9 and rebuild vuls, now it works

Thank you very much, now I bypass it with your methods. :-)

**Comment by kotakanbe** [comment]
Hi, @ZhixiongChi @rtuk 

I cannot reproduce the problem. 
I want to investigate and fix it, so please try running it with the -debug option.

`. /scan.sh --debug`. 

Thank you very much for your help.

**Comment by rtuk** [comment]
@kotakanbe 
I have tried this before changing the branch from master to the latest tag, it did not provide me with any further information
FYI, it seems @ZhixiongChi is running vuls in docker, I am running vuls as a standalone install on a server without using docker

**Comment by rtuk** [comment]
@kotakanbe 
vuls configtest
`/opt/go/bin/vuls configtest -config /data/vuls/config.toml -debug
[Mar  2 07:50:40]  INFO [localhost] vuls-v0.15.9-build-20210302_074828_1d0c5de
[Mar  2 07:50:40]  INFO [localhost] Validating config...
[Mar  2 07:50:40]  INFO [localhost] Detecting Server/Container OS... 
[Mar  2 07:50:40]  INFO [localhost] Detecting OS of servers... 
[Mar  2 07:50:40] ERROR [localhost] Failed to configtest: Failed to init servers. err:
    github.com/future-architect/vuls/scanner.Scanner.Configtest
        /opt/go/src/github.com/future-architect/vuls/scanner/serverapi.go:107
  - No scannable host OS:
    github.com/future-architect/vuls/scanner.Scanner.initServers
        /opt/go/src/github.com/future-architect/vuls/scanner/serverapi.go:235

vuls scan:
`root@artemis:/opt/go/src/github.com/future-architect/vuls# /opt/go/bin/vuls scan -config /data/vuls/config.toml -debug
[Mar  2 07:50:48]  INFO [localhost] vuls-v0.15.9-build-20210302_074828_1d0c5de
[Mar  2 07:50:48]  INFO [localhost] Start scanning
[Mar  2 07:50:48]  INFO [localhost] config: /data/vuls/config.toml
[Mar  2 07:50:48] DEBUG [localhost] map[string]config.ServerInfo{}
[Mar  2 07:50:48]  INFO [localhost] Validating config...
[Mar  2 07:50:48]  INFO [localhost] Detecting Server/Container OS... 
[Mar  2 07:50:48]  INFO [localhost] Detecting OS of servers... 
[Mar  2 07:50:48] ERROR [localhost] Failed to scan: Failed to init servers. err:
    github.com/future-architect/vuls/scanner.Scanner.Scan
        /opt/go/src/github.com/future-architect/vuls/scanner/serverapi.go:83
  - No scannable host OS:
    github.com/future-architect/vuls/scanner.Scanner.initServers
        /opt/go/src/github.com/future-architect/vuls/scanner/serverapi.go:235`

**Comment by HsinTsao** [comment]
I had the same problem and same output and debug info with @rtuk . I installed Vuls by following the tutorial from vuls.io .Did I miss something?  
More information:
`GO111MODULE="on"
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOENV="/root/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/root/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/root/go"
GOPRIVATE=""
GOPROXY="https://goproxy.io"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.16"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build3973673333=/tmp/go-build -gno-record-gcc-switches"`

`[servers]

[servers.localhost]
host = "localhost"
port = "local"
`

**Comment by HsinTsao** [comment]
I tried to read the code, and I found that the reason for this error was that I did not get the required information from the TOML configuration file. Is there something wrong with my TOML file configuration? I've already posted my toml file. 
By the way, there is some error info
`
Error loading /root/go/src/github.com/future-architect/vuls/scanner/config.toml
If you update Vuls and get this error, there may be incompatible changes in config.toml
Please check config.toml template : https://vuls.io/docs/en/usage-settings.html
`
https://vuls.io/docs/en/usage-settings.html  404

**Comment by kotakanbe** [comment]
Hey guys.

I still can't reproduce it.
If you use vulsctl or docker-based vuls, be careful in config.toml. 
If you specify localhost in config.toml, Vuls will scan for Vuls docker containers.

Please read the manual carefully.
https://vuls.io/docs/en/install-with-vulsctl.html#config-scan-report

```
$  pwd
/home/ubuntu/vulsctl/docker

$   cat config.toml
[servers]

[servers.host]
host               = "172.20.0.1"
user               = "ubuntu"
port               = "22"
keyPath            = "/root/.ssh/id_rsa"
scanMode           = ["fast-root"]

$ ./scan.sh host
Using default tag: latest
latest: Pulling from vuls/vuls
e95f33c60a64: Pull complete
8b6511269917: Pull complete
fe0a2e984645: Pull complete
Digest: sha256:158c68d3818f484414b6a9a33a35161b6354e7850fd0c69ce20fe2eb4eb6b0ba
Status: Downloaded newer image for vuls/vuls:latest
docker.io/vuls/vuls:latest
[Mar  2 21:04:22]  INFO [localhost] vuls-v0.15.9-build-20210301_225319_1d0c5de
[Mar  2 21:04:22]  INFO [localhost] Validating config...
[Mar  2 21:04:22]  INFO [localhost] Detecting Server/Container OS...
[Mar  2 21:04:22]  INFO [localhost] Detecting OS of servers...
[Mar  2 21:04:23]  INFO [localhost] (1/1) Detected: host: ubuntu 18.04
[Mar  2 21:04:23]  INFO [localhost] Detecting OS of containers...
[Mar  2 21:04:23]  INFO [localhost] Checking Scan Modes...
[Mar  2 21:04:23]  INFO [localhost] Checking dependencies...
[Mar  2 21:04:23]  INFO [host] Dependencies... Pass
[Mar  2 21:04:23]  INFO [localhost] Checking sudo settings...
[Mar  2 21:04:23]  INFO [host] Checking... sudo checkrestart
[Mar  2 21:04:24]  INFO [host] Checking... sudo stat /proc/1/exe
[Mar  2 21:04:24]  INFO [host] Checking... sudo ls -l /proc/1/exe
[Mar  2 21:04:24]  INFO [host] Checking... sudo cat /proc/1/maps
[Mar  2 21:04:24]  INFO [host] Checking... sudo lsof -i -P
[Mar  2 21:04:24]  INFO [host] Checking... sudo apt-get update
[Mar  2 21:06:33]  INFO [host] Sudo... Pass
[Mar  2 21:06:33]  INFO [localhost] It can be scanned with fast scan mode even if warn or err messages are displayed due to lack of dependent packages or sudo settings in fast-root or deep scan mode
[Mar  2 21:06:33]  INFO [localhost] Scannable servers are below...
host
[Mar  2 21:06:36]  INFO [localhost] vuls-v0.15.9-build-20210301_225319_1d0c5de
[Mar  2 21:06:36]  INFO [localhost] Start scanning
[Mar  2 21:06:36]  INFO [localhost] config: /vuls/config.toml
[Mar  2 21:06:36]  INFO [localhost] Validating config...
[Mar  2 21:06:36]  INFO [localhost] Detecting Server/Container OS...
[Mar  2 21:06:36]  INFO [localhost] Detecting OS of servers...
[Mar  2 21:06:37]  INFO [localhost] (1/1) Detected: host: ubuntu 18.04
[Mar  2 21:06:37]  INFO [localhost] Detecting OS of containers...
[Mar  2 21:06:37]  INFO [localhost] Checking Scan Modes...
[Mar  2 21:06:37]  INFO [localhost] Detecting Platforms...
[Mar  2 21:06:38]  INFO [localhost] (1/1) host is running on other
[Mar  2 21:06:38]  INFO [localhost] Detecting IPS identifiers...
[Mar  2 21:06:38]  INFO [localhost] (1/1) host has 0 IPS integration
[Mar  2 21:06:38]  INFO [host] Scanning OS pkg in fast-root mode
[Mar  2 21:06:38]  INFO [host] apt-get update...
[Mar  2 21:07:08]  WARN [host] Failed to stat systemctl status --quiet --no-pager 4819: execResult: servername: host
  cmd: /usr/bin/ssh -tt -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=auto -o ControlPath=/root/.vuls/controlmaster-%r-host.%p -o Controlpersist=10m ubuntu@172.20.0.1 -p 22 -i /root/.ssh/id_rsa -o PasswordAuthentication=no stty cols 1000; systemctl status --quiet --no-pager 4819
  exitstatus: 1
  stdout: Failed to get unit for PID 4819: PID 4819 does not belong to any loaded unit.

  stderr:
  err: %!s(<nil>)
[Mar  2 21:07:08]  INFO [host] Scanning listen port...


Scan Summary
================
host    ubuntu18.04     942 installed, 234 updatable





To view the detail, vuls tui is useful.
To send a report, run vuls report -h.
```

**Comment by HsinTsao** [comment]
I did not use the vulsctl or docker, and I installed it manually, but I still have the problem. I will try to switch to tags/v0.15.9 and rebuild vuls

**Comment by kotakanbe** [comment]
Hi, @HsinTsao 

Plz scan with `--debug` option and paste here the output.
（Make sure no sensitive information.）

`./vusl scan --debug`

If you paste the `-debug` output, I may be able to help you.

**Comment by HsinTsao** [comment]
Hi, thank you for your reply! 
This is my output:
`# vuls scan -debug
[Mar  3 10:06:24]  INFO [localhost] vuls-v0.15.9-build-20210303_100014_1d0c5de
[Mar  3 10:06:24]  INFO [localhost] Start scanning
[Mar  3 10:06:24]  INFO [localhost] config: /root/config.toml
[Mar  3 10:06:24] DEBUG [localhost] map[string]config.ServerInfo{}
[Mar  3 10:06:24]  INFO [localhost] Validating config...
[Mar  3 10:06:24]  INFO [localhost] Detecting Server/Container OS... 
[Mar  3 10:06:24]  INFO [localhost] Detecting OS of servers... 
[Mar  3 10:06:24] ERROR [localhost] Failed to scan: Failed to init servers. err:
    github.com/future-architect/vuls/scanner.Scanner.Scan
        /root/go/src/github.com/future-architect/vuls/scanner/serverapi.go:83
  - No scannable host OS:
    github.com/future-architect/vuls/scanner.Scanner.initServers
        /root/go/src/github.com/future-architect/vuls/scanner/serverapi.go:235`

`#cat config.toml 

[servers]

[servers.localhost]
host = "localhost"
port = "local"
scanMode = ["fast-root"]
`

**Comment by kotakanbe** [comment]
Hi, @HsinTsao 

```
[Mar 3 10:06:24] INFO [localhost] config: /root/config.toml
[Mar 3 10:06:24] DEBUG [localhost] map[string]config.ServerInfo{}
```

Check the content of ` /root/config.toml`

**Comment by HsinTsao** [comment]
Hi, I just followed this tutorial 
![image](https://user-images.githubusercontent.com/19318620/109742180-94ec5c00-7c09-11eb-81b2-ba87d64063dc.png)
This is my config
`
# cat /root/config.toml 
[servers]

[servers.localhost]
host = "localhost"
port = "local"
`

**Comment by kotakanbe** [comment]
@HsinTsao 

Thanks, I finally recreated it :)
I'll fix it.

```
$ cat config.toml
[servers]

[servers.localhost]
host = "localhost"
port = "local"

$  ./vuls scan --debug
[Mar  3 11:39:44]  INFO [localhost] vuls-v0.15.9-build-20210303_112121_1d0c5de
[Mar  3 11:39:44]  INFO [localhost] Start scanning
[Mar  3 11:39:44]  INFO [localhost] config: /home/ubuntu/go/src/github.com/future-architect/vuls/config.toml
[Mar  3 11:39:44] DEBUG [localhost] map[string]config.ServerInfo{}
[Mar  3 11:39:44]  INFO [localhost] Validating config...
[Mar  3 11:39:44]  INFO [localhost] Detecting Server/Container OS... 
[Mar  3 11:39:44]  INFO [localhost] Detecting OS of servers... 
[Mar  3 11:39:44] ERROR [localhost] Failed to scan: Failed to init servers. err:
    github.com/future-architect/vuls/scanner.Scanner.Scan
        /home/ubuntu/go/src/github.com/future-architect/vuls/scanner/serverapi.go:83
  - No scannable host OS:
    github.com/future-architect/vuls/scanner.Scanner.initServers
        /home/ubuntu/go/src/github.com/future-architect/vuls/scanner/serverapi.go:235
```

**Comment by kotakanbe** [comment]
Hi, Guys, 

https://github.com/future-architect/vuls/pull/1188

**Comment by kotakanbe** [comment]
Hi, Guys

It's fixed, try the latest version.

Thanks for reporting the issue.
If you guys didn't register the issue, I wouldn't have noticed.
👍

**Comment by HsinTsao** [comment]
THANKS!!  
It works well now, and it is really wonderful!

**Comment by kotakanbe** [comment]
That's good to hear :)
