### ISSUE TITLE
jvndb cannot be updated normally from 2021/02/26

### ISSUE THREAD

**Issue by snowpamela** [future-architect/vuls#1192]
# What did you do? (required. The issue will be **closed** when not provided.)
it is failed to fetch jvn data from 2021/02/26,
2021/02/26,  the reason for failure is as follows:

> t=2021-02-26T15:00:28+0900 lvl=info msg="Fetching... https://jvndb.jvn.jp/ja/feed/checksum.txt"
> t=2021-02-26T15:00:28+0900 lvl=info msg="Fetched... https://jvndb.jvn.jp/ja/feed/checksum.txt"
> t=2021-02-26T15:00:28+0900 lvl=info msg="Up to date: https://jvndb.jvn.jp/ja/rss/years/jvndb_2021.rdf"
> t=2021-02-26T15:00:28+0900 lvl=info msg="Up to date: https://jvndb.jvn.jp/ja/rss/years/jvndb_2020.rdf"
> t=2021-02-26T15:00:28+0900 lvl=info msg="Outdated  : https://jvndb.jvn.jp/ja/rss/jvndb.rdf"
> t=2021-02-26T15:00:28+0900 lvl=info msg="Outdated  : https://jvndb.jvn.jp/ja/rss/jvndb_new.rdf"
> t=2021-02-26T15:00:28+0900 lvl=info msg="Fetcling CVE information from JVN."
> t=2021-02-26T15:00:28+0900 lvl=info msg="Fetching... https://jvndb.jvn.jp/ja/rss/jvndb.rdf"
> t=2021-02-26T15:00:28+0900 lvl=info msg="Fetching... https://jvndb.jvn.jp/ja/rss/jvndb_new.rdf"
> t=2021-02-26T15:00:28+0900 lvl=info msg="Fetched... https://jvndb.jvn.jp/ja/rss/jvndb_new.rdf"
> t=2021-02-26T15:00:28+0900 lvl=info msg="Fetched... https://jvndb.jvn.jp/ja/rss/jvndb.rdf"
> t=2021-02-26T15:00:28+0900 lvl=eror msg="Failed to fetch JVN: [Failed to validate a value: component cannot contain whitespace:: cpu_
> module_logging_configuration_tool: Parse error Failed to validate a value: component cannot contain whitespace:: cpu_ module_logging_c
> onfiguration_tool: Parse error]"

but, there is no any error messages in output since the 27th, and the proccess is always existing 

>  /home/vulsuser/go/bin/go-cve-dictionary fetchjvn -last2y -dbpath=/home/vulsuser/cve.sqlite3 -http-proxy=http://yum-proxy.niftyzone.l
> ocal:8080
> 
> t=2021-03-04T15:00:08+0900 lvl=info msg="Fetching... https://jvndb.jvn.jp/ja/feed/checksum.txt"
> t=2021-03-04T15:00:08+0900 lvl=info msg="Fetched... https://jvndb.jvn.jp/ja/feed/checksum.txt"
> t=2021-03-04T15:00:08+0900 lvl=info msg="Outdated  : https://jvndb.jvn.jp/ja/rss/years/jvndb_2021.rdf"
> t=2021-03-04T15:00:08+0900 lvl=info msg="Outdated  : https://jvndb.jvn.jp/ja/rss/years/jvndb_2020.rdf"
> t=2021-03-04T15:00:08+0900 lvl=info msg="Outdated  : https://jvndb.jvn.jp/ja/rss/jvndb.rdf"
> t=2021-03-04T15:00:08+0900 lvl=info msg="Outdated  : https://jvndb.jvn.jp/ja/rss/jvndb_new.rdf"
> t=2021-03-04T15:00:08+0900 lvl=info msg="Fetcling CVE information from JVN."
> t=2021-03-04T15:00:08+0900 lvl=info msg="Fetching... https://jvndb.jvn.jp/ja/rss/years/jvndb_2021.rdf"
> t=2021-03-04T15:00:08+0900 lvl=info msg="Fetching... https://jvndb.jvn.jp/ja/rss/years/jvndb_2020.rdf"
> t=2021-03-04T15:00:08+0900 lvl=info msg="Fetching... https://jvndb.jvn.jp/ja/rss/jvndb.rdf"
> t=2021-03-04T15:00:08+0900 lvl=info msg="Fetching... https://jvndb.jvn.jp/ja/rss/jvndb_new.rdf"
> t=2021-03-04T15:00:08+0900 lvl=info msg="Fetched... https://jvndb.jvn.jp/ja/rss/jvndb.rdf"
> t=2021-03-04T15:00:08+0900 lvl=info msg="Fetched... https://jvndb.jvn.jp/ja/rss/jvndb_new.rdf"
> t=2021-03-04T15:00:08+0900 lvl=info msg="Fetched... https://jvndb.jvn.jp/ja/rss/years/jvndb_2021.rdf"
> t=2021-03-04T15:00:13+0900 lvl=info msg="Fetched... https://jvndb.jvn.jp/ja/rss/years/jvndb_2020.rdf"
> 

> [vulsuser@infrapdvuls01nc ~]$ ps -ef | grep go-cve-dictionary
> vulsuser 11423 10577  2 12:26 pts/1    00:00:01 /home/vulsuser/go/bin/go-cve-dictionary fetchjvn -last2y -dbpath=/home/vulsuser/cve.sqlite3 -http-proxy=http://yum-proxy.niftyzone.local:8080
> vulsuser 11534 10577  0 12:28 pts/1    00:00:00 grep --color=auto go-cve-dictionary
> vulsuser 13864 13827  0  3月03 ?      00:00:45 /home/vulsuser/go/bin/go-cve-dictionary fetchjvn -last2y -dbpath=/home/vulsuser/cve.sqlite3 -http-proxy=http://yum-proxy.niftyzone.local:8080
> vulsuser 49153 49130  0  3月04 ?      00:00:23 /home/vulsuser/go/bin/go-cve-dictionary fetchjvn -last2y -dbpath=/home/vulsuser/cve.sqlite3 -http-proxy=http://yum-proxy.niftyzone.local:8080
> 

the succeful log is follow the below：

>  /home/vulsuser/go/bin/go-cve-dictionary fetchjvn -last2y -dbpath=/home/vulsuser/cve.sqlite3 -http-proxy=http://yum-proxy.niftyzone.l
> ocal:8080
> 
> t=2021-02-25T15:00:14+0900 lvl=info msg="Fetching... https://jvndb.jvn.jp/ja/feed/checksum.txt"
> t=2021-02-25T15:00:15+0900 lvl=info msg="Fetched... https://jvndb.jvn.jp/ja/feed/checksum.txt"
> t=2021-02-25T15:00:15+0900 lvl=info msg="Up to date: https://jvndb.jvn.jp/ja/rss/years/jvndb_2021.rdf"
> t=2021-02-25T15:00:15+0900 lvl=info msg="Up to date: https://jvndb.jvn.jp/ja/rss/years/jvndb_2020.rdf"
> t=2021-02-25T15:00:15+0900 lvl=info msg="Outdated  : https://jvndb.jvn.jp/ja/rss/jvndb.rdf"
> t=2021-02-25T15:00:15+0900 lvl=info msg="Outdated  : https://jvndb.jvn.jp/ja/rss/jvndb_new.rdf"
> t=2021-02-25T15:00:15+0900 lvl=info msg="Fetcling CVE information from JVN."
> t=2021-02-25T15:00:15+0900 lvl=info msg="Fetching... https://jvndb.jvn.jp/ja/rss/jvndb.rdf"
> t=2021-02-25T15:00:15+0900 lvl=info msg="Fetching... https://jvndb.jvn.jp/ja/rss/jvndb_new.rdf"
> t=2021-02-25T15:00:15+0900 lvl=info msg="Fetched... https://jvndb.jvn.jp/ja/rss/jvndb_new.rdf"
> t=2021-02-25T15:00:15+0900 lvl=info msg="Fetched... https://jvndb.jvn.jp/ja/rss/jvndb.rdf"
> t=2021-02-25T15:00:15+0900 lvl=info msg="Fetched 445 CVEs"
> t=2021-02-25T15:00:15+0900 lvl=info msg="Inserting JVN into DB (sqlite3)."
> t=2021-02-25T15:00:15+0900 lvl=info msg="Inserting fetched CVEs..."
> 5 / 445 [>_____________________________________________________________________________] 1.12% ? p/s12 / 445 [-->_____________________
> _____________________________________________________] 2.70% ? p/s50 / 445 [-------->_________________________________________________
> __________________] 11.24% ? p/s445 / 445 [------------------------------------------------------------------------] 100.00% 812 p/st=
> 2021-02-25T15:00:16+0900 lvl=info msg="Refreshed 32 Jvns."

# What did you expect to happen?
it can be updated successfully before 2021/02/26

# What happened instead?

* Current Output

Please re-run the command using ```-debug``` and provide the output below.

# Steps to reproduce the behaviour

# Configuration (**MUST** fill this out):

* Go version (`go version`):
go version go1.13.1 linux/amd64
* Go environment (`go env`):

* Vuls environment:

Hash : ____

To check the commit hash of HEAD
$ vuls -v
vuls v0.11.0 build-20200728_100236_11a7a0c

or

$ cd $GOPATH/src/github.com/future-architect/vuls 
$ git rev-parse --short HEAD 

* config.toml:

* command:
/home/vulsuser/go/bin/go-cve-dictionary fetchjvn -last2y -dbpath=/home/vulsuser/cve.sqlite3 --http-proxy=http://yum-proxy.niftyzone.local:8080

**Comment by segatomo** [comment]
It has been fixed in [this](https://github.com/kotakanbe/go-cve-dictionary/pull/181) pull request.
Please use the latest version of go-cve-dictionary.

**Comment by snowpamela** [comment]
> It has been fixed in [this](https://github.com/kotakanbe/go-cve-dictionary/pull/181) pull request.
> Please use the latest version of go-cve-dictionary.

thank you so much,  try to test

**Comment by snowpamela** [comment]
It's be OK after upgrade to the lastest version,
but, Must the error message be output? Can't be removed?

> Failed to parse CPE URI: cpe:/a:mitsubishielectric:cpu_ module_logging_configuration_tool, Failed to validate a value: component cannot contain whitespace:: cpu_ module_logging_configuration_tool: Parse error
