### ISSUE TITLE
Vuls in server mode: the package order in POST request has an effect on vuls CVE report content

### ISSUE THREAD

**Issue by fredericg78** [future-architect/vuls#1199]
- Vuls version:
VULS image: vuls-v0.15.9-build-20210312_003439_56017e5
GO CVE image: go-cve-dictionary v0.5.9 5ca1230
GOVAL image: goval-dictionary v0.3.2 585b989

- order of packages in the POST json:
curl -v http://vuls-vuls:5515/vuls -H 'Content-type: text/plain' -H 'X-Vuls-OS-Family: redhat' -H 'X-Vuls-OS-Release: 8.2' -H 'X-Vuls-Kernel-Release: 4.18.0-240.15.1.el8_3.x86_64' -H 'X-Vuls-Server-Name: VMrh8' --data-binary @paquets.txt

With paquets.txt including:
grub2-common 1 2.02 90.el8 noarch
grub2-pc 1 2.02 90.el8 x86_64
grub2-pc-modules 1 2.02 90.el8 noarch
grub2-tools 1 2.02 90.el8 x86_64
grub2-tools-efi 1 2.02 90.el8 x86_64
grub2-tools-extra 1 2.02 90.el8 x86_64
grub2-tools-minimal 1 2.02 90.el8 x86_64
kernel 0 4.18.0 193.el8 x86_64
kernel 0 4.18.0 240.15.1.el8_3 x86_64
kernel-core 0 4.18.0 193.el8 x86_64
kernel-core 0 4.18.0 240.15.1.el8_3 x86_64
kernel-modules 0 4.18.0 193.el8 x86_64
kernel-modules 0 4.18.0 240.15.1.el8_3 x86_64

If kernel are listed in the above order (it has been sorted in alphabetical order), vuls returns a json report with 8 CVE about grub paquets. It is the expected behaviour, because kernel has been patched on this VM.

But if the POST sends packets in the output order of the rpm -qa --queryformat "%{NAME} %{EPOCHNUM} %{VERSION} %{RELEASE} %{ARCH}\\n" system command, vuls reports 83 CVE (it includes CVE on previous kernel releases).

Expected: the vuls results should be the same.

**Comment by kotakanbe** [comment]
@fredericg78 

Sorry for the late response.
Thanks, I was able to reproduce it and will figure out how to fix it.

**Comment by kotakanbe** [comment]
@fredericg78   

Fixed :)
