### ISSUE TITLE
Maximum 6 nodes available to scan

### ISSUE THREAD

**Issue by Bregor** [future-architect/vuls#12]
With "full" load of nodes:

	$ grep "servers\." /tmp/go/src/github.com/future-architect/vuls/config.toml|wc -l
      20

	$ ./vuls scan
	INFO[0000] Begin scannig (config: /tmp/go/src/github.com/future-architect/vuls/config.toml)
	panic: runtime error: index out of range

	goroutine 1 [running]:
	panic(0x4709000, 0xc8200121a0)
		/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
	github.com/future-architect/vuls/config.TOMLLoader.Load(0xc8202aff40, 0x38, 0x0, 0x0)
		/tmp/go/src/github.com/future-architect/vuls/config/tomlloader.go:89 +0xbd5
	github.com/future-architect/vuls/config.(*TOMLLoader).Load(0x4b1e8f8, 0xc8202aff40, 0x38, 0x0, 0x0)
		<autogenerated>:3 +0xaf
		...

After deleting 14 nodes:

	$ grep "servers\." /tmp/go/src/github.com/future-architect/vuls/config.toml|wc -l
       6

	$ ./vuls scan
	INFO[0000] Begin scannig (config: /tmp/go/src/github.com/future-architect/vuls/config.toml)
	[Apr  7 19:34:59]  INFO [localhost] Validating Config...
	[Apr  7 19:34:59]  INFO [localhost] Detecting OS...
	[Apr  7 19:35:01]  INFO [localhost] Scanning vulnerabilities...
	[Apr  7 19:35:01]  INFO [localhost] Check required packages for scanning...
	[Apr  7 19:35:01]  INFO [localhost] Scanning vuluneable OS packages...

Is there expected behaviour?

**Comment by kotakanbe** [comment]
Thanks for reporting. It is a bug. I will fix it soon.

**Comment by Bregor** [comment]
Thank you!

**Comment by kotakanbe** [comment]
@Bregor Fixed and merged to master. please try again.

**Comment by Bregor** [comment]
Works like a charm!
Thank you!
