### ISSUE TITLE
Can't report Ubuntu 21.04

### ISSUE THREAD

**Issue by shigechika** [future-architect/vuls#1230]
# What did you do? (required. The issue will be **closed** when not provided.)

vuls report

# What did you expect to happen?

Great reporting😀

# What happened instead?
```
% vuls report -debug
 :
[Apr 28 23:20:40] DEBUG [localhost] Check if oval fetched: ubuntu 21.04
[Apr 28 23:20:40]  INFO [localhost] OVAL ubuntu 21.04 found. defs: 6509
[Apr 28 23:20:40] DEBUG [localhost] Check if oval fresh: ubuntu 21.04
[Apr 28 23:20:40]  INFO [localhost] OVAL ubuntu 21.04 is fresh. lastModified: 2021-04-28T17:01:03+09:00
[Apr 28 23:20:40] DEBUG [localhost] Fill with oval: ubuntu 21.04
[Apr 28 23:20:40] ERROR [localhost] Failed to detect Pkg CVE:
    github.com/future-architect/vuls/detector.Detect
        /home/vuls/go/src/github.com/future-architect/vuls/detector/detector.go:65
  - Failed to detect CVE with OVAL:
    github.com/future-architect/vuls/detector.DetectPkgCves
        /home/vuls/go/src/github.com/future-architect/vuls/detector/detector.go:176
  - Ubuntu 21.04 is not support for now
```

* Current Output

Please re-run the command using ```-debug``` and provide the output below.

# Steps to reproduce the behaviour

# Configuration (**MUST** fill this out):

* Go version (`go version`):

go version go1.16.3 linux/amd64

* Go environment (`go env`):

* Vuls environment:

vuls-v0.15.11-build-20210428_230232_a7b0ce1

* config.toml:

* command:

**Comment by kotakanbe** [comment]
Anyone using Ubuntu 21 for server purposes?
Is anyone happy with vulnerability detection in vuls?

Ubuntu21 will be out of support at the end of this year, and I'm thinking that I don't need to merge this pull request.
