### ISSUE TITLE
FreeBSD 13.0 EOL

### ISSUE THREAD

**Issue by masayuki-koba** [future-architect/vuls#1245]
# vuls report
```
Warning for freebsd: [Failed to check EOL. Register the issue to https://github.com/future-architect/vuls/issues with the information in `Family: freebsd Release: 13.0-RELEASE-p2`]
```

# Information
[FreeBSD 13.0 released at April 13, 2021](https://www.freebsd.org/news/newsflash/#2021-04-13:4), and [EOL is  January 31, 2026](https://www.freebsd.org/security/#sup).

**Comment by kotakanbe** [comment]
Hi, @masayuki-koba
 
If you'd like, you can add it here and send us a pull request.
https://github.com/future-architect/vuls/blob/master/config/os.go#L181
https://github.com/future-architect/vuls/blob/master/config/os_test.go#L310
