### ISSUE TITLE
DockerHub Automated Builds not working

### ISSUE THREAD

**Issue by kotakanbe** [future-architect/vuls#1284]
We have to upgrade to paid plan...

![image](https://user-images.githubusercontent.com/534611/129334700-4d597d5d-4451-47ed-840b-4cccd6a43a7a.png)

**Comment by curantes** [comment]
Is this the reason of the missing tag of 0.15.13?

**Comment by tomoyamachi** [comment]
It's okay to build images in goreleaser and push it.
https://github.com/goodwithtech/dockle/blob/0e44bbb29a3ac40923810a62f7ebe2d8fad0b825/.github/workflows/releasebuild.yml#L31-L39
https://github.com/goodwithtech/dockle/blob/0e44bbb29a3ac40923810a62f7ebe2d8fad0b825/goreleaser.yaml#L108-L124

**Comment by kotakanbe** [comment]
👍 
https://github.com/future-architect/vuls/pull/1291
