### ISSUE TITLE
Empty CVE list

### ISSUE THREAD

**Issue by melhir** [future-architect/vuls#1304]
Hi,

I don't know if anyone encounters this issue, but when I am executing a scan of machines for updates and CVEs, the result of every machine doesn't have a CVE list, the `vuls tui` command output:

```
[Sep 14 07:20:05] ERROR [localhost] Failed to detect CVE of `[]`: Failed to init CVE DB. err: Failed to migrate. err: duplicate column name: id, path: /usr/share/vuls-data/cve.sqlite3: Failed to migrate. err: duplicate column name: id
```
I am using the latest tag version, any advice?

**Comment by MaineK00n** [comment]
There is a possibility that the DB created by go-cve-dictionary is outdated. Please recreate the DB with the latest version of go-cve-dictionary, and then run `vuls tui`.

**Comment by melhir** [comment]
I've built the newest tag of go-cve-dictionary and I am having a problem with fetching NVD.

```
Failed to insert. dbpath: /usr/share/vuls-data/cve.sqlite3, err: Failed to FetchConvert. err: Failed to fetch. err: Failed to fetch. err: [aborting: could not write to output stream: Expected HTTP Status 200, received: "403 Forbidden"]
```

**Comment by melhir** [comment]
Okay, I've managed to update the database of go-cve-dictionary which is built on the newest tag (there were some 404 when fetching nvd) but still, I am receiving the same error.

**Comment by melhir** [comment]
Nvm, I've discovered a newer version and it is working.
