### ISSUE TITLE
Error in cve_client.go

### ISSUE THREAD

**Issue by amankumarchagti** [future-architect/vuls#1319]
# What did you do? (required. The issue will be **closed** when not provided.)
I cloned the vulsctl repository locally and fetched the database locally, while running the server scan, I am getting the following error:
level=error msg="Failed to fill with CVE: Failed to fetch CVE. err:\n    github.com/future-architect/vuls/detector.goCveDictClient.fetchCveDetails\n        /home/user/go/src/github.com/future-architect/vuls/detector/cve_client.go:57\n  - too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; 

# What did you expect to happen?
how to resolve this issue

# What happened instead?
the file is filed with too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; ........nd so on
* Current Output

Please re-run the command using ```-debug``` and provide the output below.

# Steps to reproduce the behaviour
need to install all the databases in vulsctl repo and run vuls server (vusl server -listen=0.0.0.0:5515)
 and run the scan
# Configuration (**MUST** fill this out):

* Go version (`go version`):
go version go1.10.4 linux/amd64

* Go environment (`go env`):
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/user/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/seconize/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build164593103=/tmp/go-build -gno-record-gcc-switches"

* Vuls environment:

Hash : ____

To check the commit hash of HEAD
$ vuls -v
vuls-v0.15.13-build-20211012_122957_020f6ac
or

$ cd $GOPATH/src/github.com/future-architect/vuls 
$ git rev-parse --short HEAD 

* config.toml:
[servers]

[servers.localhost]
host               = "127.0.0.1"
port               = "local"
scanMode           = ["fast"]
* command:
vuls server -listen=0.0.0.0:5515

**Comment by aburie** [comment]
Hello
Is this issue resolved ? I've the same error on the latest build (0.19.0) when i'm using Vuls with a Debian 11
Thanks

**Comment by MaineK00n** [comment]
@aburie 

Please let me know the Error Message.
It may be that the DB is outdated.
Re-fetching with the latest goval-dictionary, gost, etc. may help.

**Comment by aburie** [comment]
@MaineK00n Hello :)

Here it is :

```
[Nov 26 08:39:23]  INFO [localhost] OVAL debian 11.0 found. defs: 20906
[Nov 26 08:39:23]  INFO [localhost] OVAL debian 11.0 is fresh. lastModified: 2021-11-26T08:33:32Z
[Nov 26 08:39:24]  INFO [localhost] XXX: 44 CVEs are detected with OVAL
[Nov 26 08:39:27]  INFO [localhost] XXX: 229 CVEs are detected with gost
[Nov 26 08:39:27]  INFO [localhost] Fill CVE detailed with gost
[Nov 26 08:39:27]  INFO [localhost] Fill CVE detailed with CVE-DB
[Nov 26 08:39:32] ERROR [localhost] Failed to fill with CVE: Failed to GetMulti. err:
    github.com/future-architect/vuls/detector.goCveDictClient.fetchCveDetails
        /go/src/github.com/future-architect/vuls/detector/cve_client.go:53
  - Failed to fill Nvd. Nvd{CveID: } err:
    github.com/vulsio/go-cve-dictionary/db.(*RDBDriver).Get
        /go/pkg/mod/github.com/vulsio/go-cve-dictionary@v0.8.2-0.20211028094424-0a854f8e8f85/db/rdb.go:213
  - too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables; too many SQL variables
```
The DB is updated, i've the error with compiled binaries & docker images
