### ISSUE TITLE
Product bugs encountered during scanning

### ISSUE THREAD

**Issue by OldFish66** [future-architect/vuls#1427]
# What did you do? (required. The issue will be **closed** when not provided.)
vuls scan

# What did you expect to happen?
Successfully scanned and output the results.

# What happened instead?
warning and stop scan.

* Current Output
Warning: [Standard OS support is EOL(End-of-Life). Purchase extended support if available or Upgrading your OS is strongly recommended.]

Please re-run the command using ```-debug``` and provide the output below.
Warning: [Failed to check EOL. Register the issue to https://github.com/future-architect/vuls/issues with the information in `Family: redhat Release: 20`]

# Steps to reproduce the behaviour

# Configuration (**MUST** fill this out):

* Go version (`go version`):
go version go1.17.3 linux/amd64

* Vuls environment:
vuls-v0.19.4-build-20220323_151647_262e09b

Hash : _262e09bc8311b28ee713665347abcf01c5827e82___

To check the commit hash of HEAD
$ vuls -v

or

$ cd $GOPATH/src/github.com/future-architect/vuls 
$ git rev-parse --short HEAD 

* command:
vuls scan

**Comment by OldFish66** [comment]
and I think this patch may help.
[0001-fix-a-scan-bug-for-extra-product.txt](https://github.com/future-architect/vuls/files/8330720/0001-fix-a-scan-bug-for-extra-product.txt)

**Comment by MaineK00n** [comment]
@OldFish66 

Vuls currently supports only RedHat Enterprise Linux (referred to as "redhat"), versions 5 through 8.
Even if the patch you wrote could scan server information, it would not be able to detect vulnerabilities.

By the way, what product or environment would you like to scan? For example, it would be great if you could tell us the name of the product, the display of `/etc/redhat-release`, and so on.

**Comment by OldFish66** [comment]
&nbsp;Sorry to reply to your email so late,


&nbsp; &nbsp; &nbsp; &nbsp;Although this bug is caused by vuls' inability to identify the product, it seems to be more of our problem. After careful consideration, we decided to modify the file （./config/os.go）locally. Thank you very much for your attention. &nbsp; &nbsp; &nbsp; &nbsp;Please forgive me for taking the liberty, and I hope you will enjoy your work.&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Mon, Mar 28, 2022 00:58 AM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [future-architect/vuls] Product bugs encountered during scanning (Issue #1427)

&nbsp;



 
@OldFish66
 
Vuls currently supports only RedHat Enterprise Linux (referred to as "redhat"), versions 5 through 8.
 Even if the patch you wrote could scan server information, it would not be able to detect vulnerabilities.
 
By the way, what product or environment would you like to scan? For example, it would be great if you could tell us the name of the product, the display of /etc/redhat-release, and so on.
