### ISSUE TITLE
error when trying to run the scan

### ISSUE THREAD

**Issue by TheMania** [future-architect/vuls#145]
Hi,

I have been trying to run the tool and I think i was able to install it properly, but when trying ti finally run the scan i get the error below. I hope you can help with this 

Command:
vuls scan -lang=en -config=config.toml --cve-dicitonary-dbpath=cve.sqlite3 -http-proxy=someproxy -debug 10-210-67-67

config.toml
[servers]

[servers.10-210-67-67] 
host="10.210.67.67"
port="22"
user="user"
keyPath="/home/user/id_rsa"

Error:
time="2016-08-04T15:21:52-07:00" level=debug msg="SSHResult: servername: 10-210-67-67, cmd: set -o pipefail; type curl, exitstatus: 0, stdout: curl is /usr/bin/curl\r\n, stderr: , err: %!s(<nil>)" prefix=10-210-67-67 
time="2016-08-04T15:21:53-07:00" level=debug msg="SSHResult: servername: 10-210-67-67, cmd: set -o pipefail; curl --max-time 1 --retry 3 --noproxy 169.254.169.254 http://169.254.169.254/latest/meta-data/instance-id, exitstatus: 7, stdout: curl: (7) couldn't connect to host\r\n, stderr: , err: %!s(<nil>)" prefix=10-210-67-67 
----snip----
----snip----

stderr: , err: %!s(<nil>)" prefix=10-210-67-67 
time="2016-08-04T15:25:11-07:00" level=debug msg="SSHResult: servername: 10-210-67-67, cmd: set -o pipefail; echo ***** | sudo -S env http_proxy=\"someproxy\" https_proxy=\"someproxy" HTTP_PROXY=\"someproxy" HTTPS_PROXY=\"someproxy" yum --color=never repolist, exitstatus: 1, stdout: Password:\r\n, stderr: , err: %!s(<nil>)" prefix=10-210-67-67 
time="2016-08-04T15:25:11-07:00" level=error msg="Failed to scan vulnerable packages" prefix=10-210-67-67

**Comment by kotakanbe** [comment]
Thanks for using vuls.

You need to pass a sudo password with -ask-sudo-password option.
For details, see https://github.com/future-architect/vuls#-ask-sudo-password-option

**Comment by kotakanbe** [comment]
-ask-sudo-password option will be deleted for security reason in the near future.
You have better define NOPASSWD in /etc/sudoers.

**Comment by kotakanbe** [comment]
If you are still in trouble, reopen the issue.
Thanks.
