### ISSUE TITLE
vuls report -to-localfile not writing

### ISSUE THREAD

**Issue by CA-dfox** [future-architect/vuls#1468]
Hello,

I am trying to get vuls to write the results to a file in JSON.  The command I am using is:
`vuls report -config=/usr/share/vuls-data/config237 -format-json -to-localfile`.
There is no file written anywhere that I can locate.  Where is the output written to?  The documentation is not very clear on this option.

**Comment by MaineK00n** [comment]
Is it placed under `<results-dir>/<scan date/time>` with `<server name>.json`?
e.g. 
```console
$ vuls report --help
...
-results-dir string
    	/path/to/results (default "/home/mainek00n/github/github.com/MaineK00n/vuls/results")
...

$ ls /home/mainek00n/github/github.com/MaineK00n/vuls/results/2022-05-20T16:02:44+09:00/
vuls-target.json
```

**Comment by CA-dfox** [comment]
Thanks for that answer!

I wasn't looking at the date/time stamp or size to notice a change.  Just that the JSON files were still JSON files.
