### ISSUE TITLE
error thrown from 'docker build .'

### ISSUE THREAD

**Issue by chuenlye** [future-architect/vuls#157]
when doing:
cd vuls/setup/docker/dockerfile
docker build .

Errors:
```
Step 24 : RUN cp -rp /tmp/vulsrepo/src/* /usr/share/nginx/html/vulsrepo
 ---> Running in 5f31317122cc
cp: cannot stat '/tmp/vulsrepo/src/*': No such file or directory
INFO[0278] The command [/bin/sh -c cp -rp /tmp/vulsrepo/src/* /usr/share/nginx/html/vulsrepo] returned a non-zero code: 1 
```

**Comment by kotakanbe** [comment]
The install procedure of VulsRepo was changed.
@hikachan are working to fix the issue.

For now, If you want to setup Vuls and VulsRepo with docker-compose, please comment out or setup Vulsrepo manually.
see https://github.com/usiusi360/vulsrepo

**Comment by kotakanbe** [comment]
The bug was fixed. Please try it out!!
https://github.com/future-architect/vuls/pull/159
