### ISSUE TITLE
Support to upload report to custom S3 (minio)

### ISSUE THREAD

**Issue by Vatson112** [future-architect/vuls#1605]
# Description

It will be nice to have oportunity to use custom s3 provider like Minio.

Minio is AWS S3 compatible, so we can use ordinary aws cli with it. For [example](https://min.io/docs/minio/linux/integrations/aws-cli-with-minio.html):
```bash
aws --endpoint-url https://play.min.io:9000 s3 ls
```

Therefore I think it's possible to implement this without completely rewriting the current implementation.

Unfortunatly, I dont have any expirience with AWS and AWS-SDK to realise it by myself.

**Comment by MaineK00n** [comment]
This part of the implementation should work if you follow the minio documentation below.
https://github.com/future-architect/vuls/blob/704492963c5dc75cc6131dca23a02aa405673dd5/reporter/s3.go#L38-L45

https://github.com/krishnasrinivas/cookbook/blob/master/docs/aws-sdk-for-go-with-minio.md
