### ISSUE TITLE
List of CVEs to ignore

### ISSUE THREAD

**Issue by F00ker** [future-architect/vuls#1630]
Hi,

Is there a way to implement a list of CVE-IDs that could be ignored and/or not put in the reports?
We're getting many old or even rejected CVEs on our servers and we'd like to filter them out before they reach our dashboard.

Thanks

**Comment by MaineK00n** [comment]
Have you read this one?
https://vuls.io/docs/en/usage-report.html#example-ignorecves

**Comment by MaineK00n** [comment]
If you want to ignore some CVEs from ScannedCves in JSON, try running `$ vuls report -format-json -to-localfile` after setting ignoreCves in config.toml.

**Comment by F00ker** [comment]
Beuh, my bad, I knew I'd seen the option somewhere.
Sorry for the disturbance.
