### ISSUE TITLE
symlink - current

### ISSUE THREAD

**Issue by witchcraze** [future-architect/vuls#1641]
I noticed symlink - "current" is not created/updated from recent update
Is this expected situation ?

----

Environment
Ubuntu22.04 on WSL2

**Comment by MaineK00n** [comment]
Yes, this is the expected behavior for https://github.com/future-architect/vuls/commit/947d6684526fc036b5987d1992ef244009a466e7 or later.
When supporting Windows, results/current is no longer created because symlink creation on Windows requires administrator privileges.

**Comment by witchcraze** [comment]
Thank you for your comment.
I got it.
