### ISSUE TITLE
Support for Grafana or Kibana

### ISSUE THREAD

**Issue by UncleJ4ck** [future-architect/vuls#1705]
I was considering whether we might incorporate a functionality that allows Vuls to transmit its data to visualization platforms such as Grafana or Kibana. This would enable us to illustrate the data in a dashboard format, comparable to the style employed in Grafana or Kibana.

**Comment by schewara** [comment]
@UncleJ4ck Have you had a look at [DefectDojo](https://www.defectdojo.org/)? Maybe It already has everythinng you are expecting and reports can be easily imported trough standard report formats like cyclonedx or through a `-to-defectdojo` report option via API.

As Grafana and Kibana are purely visualization tools which get the relevant data from an underlying Datasource.

For Grafana, one option could be, that the vuls server can act a data source, by creating a dedicated Datasource plugin, or accessed by something like the Infinity data source plugin.

Alternatively the vuls server could be instrumented with OpenTelemetry and provide metrics trough a prometheus exporter endpoint, or an otlp exporter, where the metrics then can be picked up by almost any tool which works with metrics.
