### ISSUE TITLE
goval-dictionary : Failed to fetch redhat 8

### ISSUE THREAD

**Issue by Viengogo** [future-architect/vuls#1737]
# What did you do? (required. The issue will be **closed** when not provided.)
On goval-dictionary, fetching data for redhat 8

# What did you expect to happen?
Receiving CVE for redhat 8

# What happened instead?
Fetching error
* Current Output
vieng.thasintham
[11:21 AM](https://mattermost.tech.orange/secwatt/pl/bipys61k1id58xsayqwfinkdwr)

par rapport au pb de vuls (SECWATT-1817)
Sur mon env local, j'ai une erreur lorsque je fetch redhat (ubuntu c'est ok) :
live@live:~$ docker run --net=host --rm -it -v $PWD:/vuls -v $PWD/goval-dictionary-log:/var/log/vuls vuls/goval-dictionary fetch redhat --dbtype=redis --dbpath=redis://127.0.0.1:7000/0 8
INFO[09-20|08:18:26] Fetching... URL=https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL8.xml.bz2
Failed to fetch files. err: Failed to fetch. err: [Failed to HTTP GET. url: https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL8.xml.bz2, response: &{Status:404 Not Found StatusCode:404 Proto:HTTP/2.0 ProtoMajor:2 ProtoMinor:0 Header:map[Accept-Ranges:[bytes] Cache-Control:[max-age=0, no-cache, no-store] Content-Length:[4175] Content-Type:[text/html] Date:[Wed, 20 Sep 2023 08:18:27 GMT] Etag:["ae034f3a82c72cf3e42fbff031eb884e:1605205643.329165"\] Expires:[Wed, 20 Sep 2023 08:18:27 GMT] Last-Modified:[Thu, 12 Nov 2020 18:26:58 GMT] Pragma:[no-cache] Server:[AkamaiNetStorage]]
Please re-run the command using ```-debug``` and provide the output below.

# Steps to reproduce the behaviour

# Configuration (**MUST** fill this out):

goval-dictionary:v0.8.2
go-cve-dictionary:v0.8.3
* Go version (`go version`):

* Go environment (`go env`):

* Vuls environment:
Vuls v0.22.0
Hash : ____

To check the commit hash of HEAD
$ vuls -v

or

$ cd $GOPATH/src/github.com/future-architect/vuls 
$ git rev-parse --short HEAD 

* config.toml:

* command:

**Comment by kotakanbe** [comment]
Please update to the latest version of goval dictionary and re-run it.
