### ISSUE TITLE
`future-vuls upload` command doesn't have `--upload` flag in v0.23.4

### ISSUE THREAD

**Issue by takaishi** [future-architect/vuls#1740]
# What did you do? (required. The issue will be **closed** when not provided.)

I run `future-vuls upload` command in Github Action workflow, but it fails.

```
Error: unknown flag: --url
Usage:
  future-vuls upload [flags]

Flags:
      --config string   config file (default is $HOME/.cobra.yaml)
  -g, --group-id int    future vuls group id, ENV: VULS_GROUP_ID
  -h, --help            help for upload
  -s, --stdin           input from stdin. ENV: VULS_STDIN
  -t, --token string    future vuls token
      --uuid string     server uuid. ENV: VULS_SERVER_UUID

Failed to execute command
```

I checked v0.23.4 and v0.23.3, and I found `--url` flag is removed in https://github.com/future-architect/vuls/pull/1721. Is this intended or not?

v0.23.4:

```
% ./future-vuls upload -h
Upload to FutureVuls

Usage:
  future-vuls upload [flags]

Flags:
      --config string   config file (default is $HOME/.cobra.yaml)
  -g, --group-id int    future vuls group id, ENV: VULS_GROUP_ID
  -h, --help            help for upload
  -s, --stdin           input from stdin. ENV: VULS_STDIN
  -t, --token string    future vuls token
      --uuid string     server uuid. ENV: VULS_SERVER_UUID
```

v.0.23.3:

```
% ./future-vuls upload -h
Upload to FutureVuls

Usage:
  future-vuls upload [flags]

Flags:
      --config string   config file (default is $HOME/.cobra.yaml)
  -g, --group-id int    future vuls group id, ENV: VULS_GROUP_ID
  -h, --help            help for upload
  -s, --stdin           input from stdin. ENV: VULS_STDIN
  -t, --token string    future vuls token
      --url string      future vuls upload url
      --uuid string     server uuid. ENV: VULS_SERVER_UUID
```

# What did you expect to happen?

I expect to use `future-vuls upload` command with `--url` flag.

# What happened instead?

* Current Output

Please re-run the command using ```-debug``` and provide the output below.

# Steps to reproduce the behaviour

# Configuration (**MUST** fill this out):

* Go version (`go version`):

`go version go1.21.1 darwin/arm64`

* Go environment (`go env`):

* Vuls environment:

```
% git rev-parse --short HEAD
70fd968
```

* command:

```
future-vuls upload --stdin --url ${{ env.FVULS_AUTH_URL }} --group-id ${{ env.VULS_SAAS_GROUPID }} --token ${{ env.VULS_SAAS_TOKEN }} --uuid ${{ env.VULS_SAAS_UUID }}
```

**Comment by wadda0714** [comment]
With the update from v0.23.3 to v0.23.4, the url flag in the future-vuls upload command has been removed.
In v0.23.4 future-vuls upload, the --url is no longer needed because the url to upload is specified in the code.
The following command is supposed to work correctly.
```
future-vuls upload --stdin --group-id ${{ env.VULS_SAAS_GROUPID }} --token ${{ env.VULS_SAAS_TOKEN }} --uuid ${{ env.VULS_SAAS_UUID }}
```
I apologize for forgetting to mention this change in my PR.

**Comment by takaishi** [comment]
I understand why --url flag was removed. I fix my command and confirm it works well. Thank you so much!
