### ISSUE TITLE
Error on make install

### ISSUE THREAD

**Issue by tazikazitr9s** [future-architect/vuls#1760]
# What did you do? (required. The issue will be **closed** when not provided.)
Installed according to the manual.

$ mkdir -p $GOPATH/src/github.com/future-architect
$ cd $GOPATH/src/github.com/future-architect
$ git clone https://github.com/future-architect/vuls.git
$ cd vuls
$ make install

# What did you expect to happen?
The software is installed successfully.

# What happened instead?
make: *** [install] error1

* Current Output
CGO_ENABLED=0 go install -ldflags "-X 'github.com/future-architect/vuls/config.Version=v0.24.1' -X 'github.com/future-architect/vuls/config.Revision=build-20231011_112730_d2ca56a'" ./cmd/vuls
../../../../pkg/mod/github.com/aquasecurity/go-dep-parser@v0.0.0-20221114145626-35ef808901e8/pkg/golang/binary/parse.go:4:2: package debug/buildinfo is not in GOROOT (/usr/local/go/src/debug/buildinfo)
../../../../pkg/mod/golang.org/x/net@v0.17.0/publicsuffix/table.go:5:8: package embed is not in GOROOT (/usr/local/go/src/embed)
../../../../pkg/mod/github.com/!burnt!sushi/toml@v1.3.2/decode_go116.go:7:2: package io/fs is not in GOROOT (/usr/local/go/src/io/fs)
../../../../pkg/mod/github.com/jackc/pgx/v5@v5.4.3/pgtype/builtin_wrappers.go:9:2: package net/netip is not in GOROOT (/usr/local/go/src/net/netip)

Please re-run the command using ```-debug``` and provide the output below.

# Steps to reproduce the behaviour

$ mkdir -p $GOPATH/src/github.com/future-architect
$ cd $GOPATH/src/github.com/future-architect
$ git clone https://github.com/future-architect/vuls.git
$ cd vuls
$ make install
# Configuration (**MUST** fill this out):

* Go version (`go version`):
go version go1.19.10 linux/amd64

* Go environment (`go env`):
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ichi/.cache/go-build"
GOENV="/home/ichi/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/ichi/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/ichi/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.19.10"
GCCGO="gccgo"
GOAMD64="v1"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/ichi/go/src/github.com/future-architect/vuls/go.mod"
GOWORK=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -Wl,--no-gc-sections -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build516267238=/tmp/go-build -gno-record-gcc-switches"

* Vuls environment:
N/A
Hash : ____

To check the commit hash of HEAD
$ vuls -v

or

$ cd $GOPATH/src/github.com/future-architect/vuls 
$ git rev-parse --short HEAD 

* config.toml:
N/A
* command:
N/A

**Comment by MaineK00n** [comment]
Go 1.20+ version is required to install vuls.
However, your go version is 1.19.10. 
Please update to version 1.20 or higher and try `make install` again.

https://github.com/future-architect/vuls/blob/d2ca56a515e055b6e8f1d0f5cb3a3be1fb8be56f/go.mod#L3

**Comment by tazikazitr9s** [comment]
Done, thank you for your support.
