### ISSUE TITLE
vuls configtest -ssh-external doesnt work

### ISSUE THREAD

**Issue by novakin** [future-architect/vuls#178]
Hi :-)

A small issue, option `-ssh-external` is not working properly with `vuls configtest` 

Looks like it still use the ssh go client, below the logs:

> err: ssh: handshake failed: ssh: no common algorithm for client to server cipher; client offered: [aes128-ctr aes192-ctr aes256-ctr aes128-gcm@openssh.com arcfour256 arcfour128], server offered: [chacha20-poly1305@openssh.com], Retrying in 954.512469ms...

vuls scan work as intended with  `-ssh-external`

**Comment by kotakanbe** [comment]
Thanks a lot :)
I fixed the problem.

**Comment by novakin** [comment]
Wow ! 👍 

Updated and it works perfectly :-)
