### ISSUE TITLE
Package for debian 12

### ISSUE THREAD

**Issue by yilas** [future-architect/vuls#1787]
Hello 👋🏻 

Is a debian 12 package of vuls planned ?
As far as I see, only debian 11 (and older versions) is supported ([link](https://packages.debian.org/search?keywords=vuls))

Thanks !

**Comment by MaineK00n** [comment]
Currently, the officially provided installation methods are either using GitHub releases or generating binaries with go.
Therefore, the vuls package on debian is currently not officially maintained.

**Comment by yilas** [comment]
> Currently, the officially provided installation methods are either using GitHub releases or generating binaries with go. Therefore, the vuls package on debian is currently not officially maintained.

Thank you for the feedback, @MaineK00n
