### ISSUE TITLE
Question: Heatmap Category Count

### ISSUE THREAD

**Issue by b4rlw** [future-architect/vuls#1813]
Hello, I'm new to Vuls and CVE scans in general.

How is the count determined for each CVSS category in the heatmap pivot tables, when the underlying JSON files from which the tables are generated stratify by CVSSv2 and CVSSv3 severity/scores?

Ie. if I am looking at CVSS Medium scores on the default heatmap view, is this the combined count of CVSSv2 and CVSSv3 CVEs, or the unique CVE IDs between these two sets that fall into the Medium category, or some other way?

Thanks.

**Comment by MaineK00n** [comment]
@b4rlw 
Is this a question about vulsrepo?
If so, this issue should be created in the vulsrepo repository.

**Comment by b4rlw** [comment]
@MaineK00n My apologies, wrong repo! I'll open there.
