### ISSUE TITLE
Windows not shown in supported OS list

### ISSUE THREAD

**Issue by JustinWebDev** [future-architect/vuls#1821]
# What did you do? (required. The issue will be **closed** when not provided.)
https://github.com/future-architect/vuls#scan-for-any-vulnerabilities-in-linuxfreebsdwindowsmacos says Windows is supported
but the OS pages does not mention Windows
https://vuls.io/docs/en/supported-os.html

**Comment by kotakanbe** [comment]
Pull request welcome!

**Comment by MaineK00n** [comment]
The cause is that the CI of this repository is failing.
https://github.com/vulsdoc/vuls
