### ISSUE TITLE
Support for Fedora is not working

### ISSUE THREAD

**Issue by asrocha** [future-architect/vuls#1825]
# What did you expect to happen?
I wanna to fetch  fedora  vulnerabilities 

# What happened instead?

Fedora  is not in  fetch options o command line

docker run vuls/goval-dictionary:latest --debug fetch fedora

* Current Output
Available Commands:
  alpine      Fetch Vulnerability dictionary from Alpine secdb
  amazon      Fetch Vulnerability dictionary from Amazon ALAS
  debian      Fetch Vulnerability dictionary from Debian
  oracle      Fetch Vulnerability dictionary from Oracle
  redhat      Fetch Vulnerability dictionary from RedHat
  suse        Fetch Vulnerability dictionary from SUSE
  ubuntu      Fetch Vulnerability dictionary from Ubuntu

vuls--build-20211029_022527_

**Comment by MaineK00n** [comment]
@asrocha 
Please create an issue in vulsio/goval-dictionary.
