### ISSUE TITLE
Results of the scan & report seem odd

### ISSUE THREAD

**Issue by ele18081** [future-architect/vuls#1840]
Hello, 

I'm facing an issue trying to execute the tool, maybe i'm doing it wrong but I made sure to follow the documentation at https://vuls.io/docs/en/tutorial-vulsctl-docker.html

# What did you do?

Run the following commands :

`$ ./scan.sh TEST`
`$ ./oval.sh --debian`
`$ ./report.sh `

# What did you expect to happen?

Have some CVE founds in the report output

# What happened instead?

The commands are executed but i get only the "installed" packages and the report show 0 associated CVE which seems odd. 

The report also show a skip that i don't want : 

> time="Jan 30 16:22:26" level=info msg="Skip OVAL and Scan with gost alone."

For reference, when i do a "apt update" on the remote Debian, i get 81 upgrade needed.
Some of which are tagged "security" so they obiously correct some existing CVE.

![image](https://github.com/future-architect/vuls/assets/77396426/8fea90a6-cbe3-46b2-95dd-33d8d45e7756)

![image](https://github.com/future-architect/vuls/assets/77396426/af245174-be63-4c5a-b5ce-e9b226e4f7d4)

## Debug

During execution, i get the following errors : 

![image](https://github.com/future-architect/vuls/assets/77396426/b692e52d-6d64-4e7d-aaab-2fa31d38a012)

# Configuration:

* Vuls environment:

Hash : vuls--build-20240115_225910_b7e5bb2

* config.toml:

![image](https://github.com/future-architect/vuls/assets/77396426/4f84a5ba-8edd-4a10-9d62-0b4ff2d3e23c)

* ssh config 

i can ssh into the remote host from the local host (and the docker image executing vuls) without a password, as requested by the documentation (and the known_host file is being filled correctly).

---
Did anyone experienced this same behavior ? 
Hope someone can help me on this, i'll be glad to use this scan more often :) 

Have a nice day !

**Comment by MaineK00n** [comment]
Currently, vuls uses only gost instead of oval and gost for debian.
Therefore, run `$ ./gost.sh --debian`.

Also, it's an stty error, but it's probably something that can be ignored.

**Comment by MaineK00n** [comment]
If you don't mind, I would be happy if you could send a PR for tutorial corrections to [vulsdoc/vuls](https://github.com/vulsdoc/vuls).

**Comment by ele18081** [comment]
thank you for the quick reply! The CVE get reported correctly with the ghost DB.  
(the stty error seem related to my setup as i use a proxy to access the remote target. It doesn't prevent vuls to work). 

I added a PR with a little note : https://github.com/vulsdoc/vuls/pull/238
