### ISSUE TITLE
Failed to scan. err: No server defined. Check the configuration

### ISSUE THREAD

**Issue by keyolk** [future-architect/vuls#187]
Hello~
I'm newbie on this project.

I'm tyring it with docker, docker-compose.
but failed with below error
```
[Sep 19 02:04:56]  INFO [localhost] Validating Config...
[Sep 19 02:04:56]  INFO [localhost] Detecting Server/Contianer OS... 
[Sep 19 02:04:56]  INFO [localhost] Detecting OS of servers... 
[Sep 19 02:04:56]  INFO [localhost] Detecting OS of containers... 
[Sep 19 02:04:56]  INFO [localhost] Checking sudo configuration... 
[Sep 19 02:04:56]  INFO [localhost] Detecting Platforms... 
[Sep 19 02:04:56]  INFO [localhost] Scanning vulnerabilities... 
[Sep 19 02:04:56] ERROR [localhost] Failed to scan. err: No server defined. Check the configuration
```

my config.toml is below
```
[servers]

[my laptop]
host  = "xx.xx.xxxx.xxx"
user  = "keyolk"
keyPath  = "conf/id_rsa"
```

```
vuls configtest -debug
[Sep 19 03:04:31]  INFO [localhost] Validating Config...
[Sep 19 03:04:31]  INFO [localhost] Detecting Server/Contianer OS... 
[Sep 19 03:04:31]  INFO [localhost] Detecting OS of servers... 
[Sep 19 03:04:31]  INFO [localhost] Detecting OS of containers... 
[Sep 19 03:04:31]  INFO [localhost] Checking sudo configuration... 
[Sep 19 03:04:31]  INFO [localhost] SSH-able servers are below...
```
Could anyone inform me why it puts the error ?

**Comment by kotakanbe** [comment]
Hello. Thanks for using Vuls :)

You have to change  `[my laptop]` to `[servers.my_laptop]`

For details, see   
https://github.com/toml-lang/toml#user-content-table or
https://github.com/BurntSushi/toml#more-complex-usage
```
Whitespace around dot-separated parts is ignored, however, best practice is to not use any extraneous whitespace.
```

**Comment by keyolk** [comment]
@kotakanbe 
Thanks reply
but still has an issue

it puts belows
```
[Sep 19 07:12:29]  INFO [localhost] Validating Config...
[Sep 19 07:12:33]  INFO [localhost] Detecting Server/Contianer OS... 
[Sep 19 07:12:33]  INFO [localhost] Detecting OS of servers... 
[Sep 19 07:12:34] ERROR [localhost] (1/2) Failed: xx-xx-xxx-xxx, err: [Unknown OS Type]
[Sep 19 07:12:35] ERROR [localhost] (2/2) Failed: xx-xx-xxx-xx, err: [Unknown OS Type]
[Sep 19 07:12:35]  INFO [localhost] Detecting OS of containers... 
[Sep 19 07:12:35]  INFO [localhost] Checking sudo configuration... 
[Sep 19 07:12:35]  INFO [localhost] SSH-able servers are below...
```

Both are Arch based distro
whether it has some OS limitation for use ?

**Comment by kotakanbe** [comment]
Arch Linux is not supported yet.
see https://github.com/future-architect/vuls#support-os

I found the vulnerability information abount arch Linux on the web.
https://wiki.archlinux.org/index.php/CVE#Documented_CVE.27s

If we get these CVE information via command line, Vuls can detect the vulnerability information on Arch Linux. Do you know about that?

**Comment by keyolk** [comment]
@kotakanbe 
I'll check how I can get the information.
And I just wannted to check docker images not the docker engine host.
Is there some workaround ?

**Comment by kotakanbe** [comment]
> And I just wannted to check docker images not the docker engine host.
Is there some workaround ?

Not implemented yet.
https://github.com/future-architect/vuls/issues/122

> And How it make matching CPE ID and target files ?
What I mean it just check package management system ? 

 Please see Usage: Scan vulnerability of non-OS package section.
https://github.com/future-architect/vuls#usage-scan-vulnerability-of-non-os-package

**Comment by kotakanbe** [comment]
@keyolk 

> And I just wannted to check docker images not the docker engine host.
Is there some workaround ?

I implemented the function :)
Please specify -containers-only option of scan subcommand.
For details, see https://github.com/future-architect/vuls/pull/190

**Comment by kotakanbe** [comment]
If you are still in trouble, please reopen the issue.
Thanks

**Comment by swiftgeek** [comment]
vulnerability information is now available at https://security.archlinux.org/
