### ISSUE TITLE
Error on json report : err: json: cannot unmarshal object into Go struct field Nvd.Cvss2 of type

### ISSUE THREAD

**Issue by Viengogo** [future-architect/vuls#1870]
# What did you do? (required. The issue will be **closed** when not provided.)
We using Vuls in server mode (v.0.25.1) 
curl -v http://127.0.0.1:5515/vuls -H 'Content-type: text/plain' -H 'X-Vuls-OS-Family: redhat' -H 'X-Vuls-OS-Release: 8.7' -H 'X-Vuls-Kernel-Release: 4.18.0-477.13.1.el8_8.x86_64' --data-binary @rh87.txt > res_rh1303-2.json

In results we having an error in json report : 
Failed to fetchCveDetails. err: Failed to GetMulti. err: Failed to convertToCveDetail. err: Failed to Unmarshal JSON. err: json: cannot unmarshal object into Go struct field Nvd.Cvss2 of type []models.NvdCvss2Extra
[{"jsonVersion":0,"lang":"","serverUUID":"","serverName":"","family":"redhat","release":"8.7", ...

# What did you expect to happen?

# What happened instead?

* Current Output
[res_rh1303.json](https://github.com/future-architect/vuls/files/14585579/res_rh1303.json)

Please re-run the command using ```-debug``` and provide the output below.

# Steps to reproduce the behaviour

# Configuration (**MUST** fill this out):

* Go version (`go version`):

* Go environment (`go env`):

* Vuls environment:
vuls v0.25.1
goval-dictionary  v0.9.4
go-cve-dictionary v0.10.1
gost v0.4.5

Hash : ____

To check the commit hash of HEAD
$ vuls -v

or

$ cd $GOPATH/src/github.com/future-architect/vuls 
$ git rev-parse --short HEAD 

* config.toml:

* command:

**Comment by MaineK00n** [comment]
@Viengogo

This is probably because the go-cve-dictionary DB is not the latest.

I assume you are using Redis.
Please check SchemaVersion.
If it is not 3, please create a new DB with go-cve-dictionary and try running vuls report again.
```console
127.0.0.1:6379[1]> HGET CVE#FETCHMETA SchemaVersion
"3"
```

**Comment by Viengogo** [comment]
by updating go-cve-dictionary to v0.10.1 and re-creating new DB, vuls report is OK.

You can close this issue. Thanks.
