### ISSUE TITLE
Segmentation fault with configtest

### ISSUE THREAD

**Issue by benji1000** [future-architect/vuls#192]
Hello,

I've followed the installation guide until step 6. I ran into a problem at step 7:

```
root@kali:~# cat config.toml 
[servers]

[servers.10-0-0-111]
host        = "10.0.0.111"
port        = "22"
user        = "ben"
keyPath     = "/root/.ssh/id_rsa"
root@kali:~# vuls prepare
Erreur de segmentation
```
Maybe I'm stating the obvious here, but "Erreur de segmentation" means "Segmentation fault" in French :)

So I can't proceed with the install. I'm running Vuls from:

`Linux kali 4.0.0-kali1-amd64 #1 SMP Debian 4.0.4-1+kali2 (2015-06-03) x86_64 GNU/Linux`

What's going on? Thanks for your help!

**Comment by kotakanbe** [comment]
Probably the error was occurred in go runtime....

Please try blow options.
- Try using the latest version of go.
- Run Vuls on Other Linux.

**Comment by benji1000** [comment]
You're right, installing latest version of Go (1.7.1 at the time of writing) solved it. I actually did not think of that since you're specifying a particular version in the install notes (step 3).

Also, maybe you could add in step 6 that the config file must be in the home directory? There's an error message when launching `configtest` if the file is not there, but it could be nice to know it beforehand.

Thanks!
