### ISSUE TITLE
Support for alpine is not actually in place despite the OS being listed as supported

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [future-architect/vuls#1932]
# What did you do? (required. The issue will be **closed** when not provided.)

Tried to install `vuls` on an `alpine` container

# What did you expect to happen?

`vuls` to be installed

# What happened instead?

* Current Output

```
# ./install.sh
"alpine" is not supported distro, so please install packages manually.
```

# Steps to reproduce the behaviour

# Configuration (**MUST** fill this out):

No configuration-specific issue

```sh
# cat /etc/os-release
NAME="Alpine Linux"
ID=alpine
VERSION_ID=3.15.4
PRETTY_NAME="Alpine Linux v3.15"
HOME_URL="https://alpinelinux.org/"
BUG_REPORT_URL="https://bugs.alpinelinux.org/"
```

`alpine` is [listed](https://vuls.io/docs/en/supported-os.html) as supported.

**Comment by MaineK00n** [comment]
This list shows whether the detection target is supported or not.
https://vuls.io/docs/en/supported-os.html

Alpine currently does not support installing vuls tools via vulsctl, but it will be supported in the near future.
https://github.com/vulsio/vulsctl/blob/03590f1c9a5dda0a459f8a60e662875569fbb326/install-host/install.sh
