### ISSUE TITLE
Failed: Unknown OS Type

### ISSUE THREAD

**Issue by benji1000** [future-architect/vuls#196]
Hi,

I successfully ran Vuls against one of my servers, but I have a problem when running Vuls against another one of my servers. When running `vuls prepare`, it fails with this error log:

```
INFO [localhost] Detecting OS... 
INFO [localhost] Detecting OS of servers... 
ERROR [localhost] (1/1) Failed: web, err: [Unknown OS Type]
ERROR [localhost] Failed to init servers: No scannable servers
```

The server I'm trying to scan is a standard Ubuntu 14.04. How come it fails to detect the OS version?

I saw in the code that the detection is based on [this module](https://github.com/serverspec/specinfra/blob/master/lib/specinfra/helper/detect_os/debian.rb), but I'm not familiar with Ruby nor the Go language. As far as I can understand, all the commands indicated in this snippet of code seem to output useful info. Should I report this to [specinfra](https://github.com/mizzy/specinfra) directly?

`cat /etc/debian_version`:

```
jessie/sid
```

`lsb_release -ir`:

```
Distributor ID: Ubuntu
Release:        14.04
```

`cat /etc/lsb-release`:

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.5 LTS"
```

Thanks for your help!

**Comment by kotakanbe** [comment]
Hi @benji1000 

Please scan with --debug option to get detail information.

**Comment by benji1000** [comment]
Thank you for your answer.

I added a user on the server I wanted to test using the `useradd` command, but I didn't specify a shell. Turns out, the default shell for my system was set to `/bin/sh`, and Vuls runs the command `set -o pipefail`, which is incompatible with `/bin/sh`, and requires `/bin/bash` as shell to work.

Re-creating the user using `--shell /bin/bash` option in `useradd` solved the issue.

**Comment by hktalent** [comment]
mac os 10.12.3

$ cat config.toml 
[servers]

[servers.192_168_10_115]
host         = "192.168.10.115"
port        = "22"
user        = "root"
keyPath     = "/Users/xiatian/.ssh/id_rsa"

$ ./vuls scan -debug
INFO[0000] Start scanning                               
INFO[0000] config: /usr/local/opt/go/bin/config.toml    
DEBU[0000] map[string]config.ServerInfo{}      
[Feb 13 15:41:50]  INFO [localhost] Validating Config...
[Feb 13 15:41:50]  INFO [localhost] Detecting Server/Container OS... 
[Feb 13 15:41:50]  INFO [localhost] Detecting OS of servers... 
[Feb 13 15:41:50] DEBUG [localhost] execResult: servername: 192_168_10_115
  cmd: 
  exitstatus: 999
  stdout: 
  stderr: 
  err: x509: decryption password incorrect
[Feb 13 15:41:50] DEBUG [localhost] execResult: servername: 192_168_10_115
  cmd: 
  exitstatus: 999
  stdout: 
  stderr: 
  err: x509: decryption password incorrect
[Feb 13 15:41:51] DEBUG [localhost] execResult: servername: 192_168_10_115
  cmd: 
  exitstatus: 999
  stdout: 
  stderr: 
  err: x509: decryption password incorrect
[Feb 13 15:41:51] DEBUG [localhost] execResult: servername: 192_168_10_115
  cmd: 
  exitstatus: 999
  stdout: 
  stderr: 
  err: x509: decryption password incorrect
[Feb 13 15:41:51] DEBUG [localhost] Not RedHat like Linux. servername: 192_168_10_115
[Feb 13 15:41:51] DEBUG [localhost] execResult: servername: 192_168_10_115
  cmd: 
  exitstatus: 999
  stdout: 
  stderr: 
  err: x509: decryption password incorrect
[Feb 13 15:41:51] DEBUG [localhost] Not FreeBSD. servernam: 192_168_10_115
[Feb 13 15:41:51] ERROR [localhost] (1/1) Failed: 192_168_10_115, err: [Unknown OS Type]
[Feb 13 15:41:51] ERROR [localhost] Failed to init servers: No scannable servers
