### ISSUE TITLE
Wrong file permissions for results/*.json in official Docker container

### ISSUE THREAD

**Issue by freerko** [future-architect/vuls#197]
Hi,

using vuls via the official Docker container saves the /var/www/html/vulsrepo/results/*.json files with the wrong permissions (-rw-------, 600) which prevents the vulsrepo UI from accessing the json files.

**Comment by kotakanbe** [comment]
@freerko 

We are working to improve setup/docker.
https://github.com/future-architect/vuls/pull/163

The P/R will be merged in this week (probably:).
Stay tuned!

**Comment by kotakanbe** [comment]
Merged.

Please check it out :)

**Comment by kotakanbe** [comment]
If you are still in trouble, please reopen the issue.
Thanks
