### ISSUE TITLE
Group servers to projects, group projects to teams

### ISSUE THREAD

**Issue by freerko** [future-architect/vuls#198]
Hi,

it would be useful to be able to group servers to projects/apps and to group projects to teams/owners. This would make it possible to use vuls for various independent projects/apps which are managed by different teams.

Can we use the nested tables of TOML for this? Like:

```
[teamA.projectA.hostname1]
host        = "1.2.3.4"
port        = "22"
user        = "root"
keyPath     = "conf/id_rsa-vuls"

[teamA.projectA.hostname2]
host        = "1.2.3.5"
port        = "22"
user        = "root"
keyPath     = "conf/id_rsa-vuls"

[teamA.projectB.hostname1]
host        = "1.2.4.1"
port        = "22"
user        = "root"
keyPath     = "conf/id_rsa-vuls"

[teamB.projectC.hostname1]
host        = "1.2.5.20"
port        = "22"
user        = "root"
keyPath     = "conf/id_rsa-vuls"
```

With this it would be possible to add a feature to scan servers by project/app or by team/owner. The vulsrepo webinterface would as well allow filtering based on that information.

**Comment by kotakanbe** [comment]
Hi, sorry for late reply :)

Nice idea!

For now, there is a workaround to manage independent project/apps.
- Split into some config.toml files.
- Run vuls using each config.toml ( with different -result-dir ).
- Run some vulsrepo with different port.

I am going to improve config.toml in the near future.
- Enable to define command line args in config.toml ... and so on.

I will take your idea into consideration.

Thanks!

**Comment by kotakanbe** [comment]
Nobody wants
