### ISSUE TITLE
Known Host Error does not properly explain issues 

### ISSUE THREAD

**Issue by Rattkener** [future-architect/vuls#1998]
I have received the following error a number of times, seemingly from different issues:
`ERROR [localhost] (1/1) Failed: cpv, err: [Failed to find the server key that matches the key registered in the client. The server key may have been changed. Please exec `$ /usr/bin/ssh-keygen -R -f /root/.ssh/known_hosts` and `$ /usr/bin/ssh -i /root/.ssh/id_rsa -p 22 -l  6` or `$ /usr/bin/ssh-keyscan -p 22 >> /root/.ssh/known_hosts`:
    github.com/future-architect/vuls/scanner.validateSSHConfig
        /go/src/github.com/future-architect/vuls/scanner/scanner.go:476]`

Previously this was because the known_hosts file on my machine was not readable by other. I figured that one out on my own, the current issue where the above log was collected from I'm still not sure the cause. 

Apparently this error can be caused by a number of issues/misconfiguration/etc that aren't well detailed in the error, from genuine host key mismatching to permissions issues. This error would appear to need more verbosity. 

For context on the exact issue I'm facing, other hosts have scanned successfully, username checks out, host has been logged into before outside of vuls, Known_hosts permissions are set 755, and has been wiped and started over. This scan process was used on 2 nearly identical centos 7.9 systems using the remote scan feature, but for some reason this one is failing while the other is not. And a previous system of similar configuration has also been successfully scanned. 

Is there additional logging or debugging that can be accessed that may point me to a better solution for this issue?

**Comment by MaineK00n** [comment]
Sorry for the late reply.

Can you connect to the machine where the scan is failing using the current /root/.ssh/known_hosts via ssh command?

**Comment by MaineK00n** [comment]
This error often occurs in the following situations:
1. A host was previously added to known_hosts.
2. Then, the host key of that host is changed for some reason.
3. As a result, the host key differs from the one written in known_hosts previously registered, and host authentication fails.

```console
// Prepare a machine that can connect via SSH
$ docker run --rm -itd -p 2222:22 --name vuls-target vuls-target:ubuntu24.04
c2b9c12134905dc3f3851b29ec9870007d49f538d1d9f95e067b24dddc9846ff

$ ssh-keyscan -p 2222 127.0.0.1
# 127.0.0.1:2222 SSH-2.0-OpenSSH_9.6p1 Ubuntu-3ubuntu13.4
# 127.0.0.1:2222 SSH-2.0-OpenSSH_9.6p1 Ubuntu-3ubuntu13.4
[127.0.0.1]:2222 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCqJ1Qo9i7j3IC4e3tIpsOWBgcyJJ95WiMafFcTCNmwfvNEyLpRXvKl9jYtTdFCUivNpcOgNn3Kx4oAJsRmjnUvcpFeWr7pe/eC7fs5ecAYCfC4v0xepIqsU72+2rC2d0tXFQri0SAFW0j84EYf/oPfqKRLvgu/7Md/AXHlNBIVuJRI/imCbt0NiuJnOK4jJZUakEQcrT9NCMQMAgKpKY18hCSpbOlF6z+tHI4DtlDHplMMuxbAexY7QszgyqvTT6RQsuShAiq8jmpYHgHW4iGAi6Idp5DREVydXy6vhknLlbOkrlksHmQyMFO0qTKbA+Ddzy/sWaLM3tXmidr3bAwL8QJ6JrkI6IdxmTiO1wK0t/DXkiDVkS9klXf1AGfY5iE2HO9VvmcSCt1c4Q95/7jnEwJLBqQd0od8jOwlCBfqUf/UCbug5+KHen0J7Vc3IWerWkV3CvhGt1jH1fOvrL3T+Ik5Kcs3B63KaOKMP3Tz1LfeSNI1t/Bv7rAg2cr9D6M=
# 127.0.0.1:2222 SSH-2.0-OpenSSH_9.6p1 Ubuntu-3ubuntu13.4
[127.0.0.1]:2222 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBGDwpDZ9km0hCEsk2Ikne12JixK8cYL0l1Nw08h1zA1+Buan30FuxVJRJW+shZ1Oy8Ri/kyy731/b3tFHtdIg0Q=
# 127.0.0.1:2222 SSH-2.0-OpenSSH_9.6p1 Ubuntu-3ubuntu13.4
[127.0.0.1]:2222 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJphwiExvBJdrF9b5KFoYPm39oi76WbMcrl+rRulhe6P
# 127.0.0.1:2222 SSH-2.0-OpenSSH_9.6p1 Ubuntu-3ubuntu13.4

$ ssh -i /home/vuls/.ssh/id_rsa -p 2222 root@127.0.0.1
The authenticity of host '[127.0.0.1]:2222 ([127.0.0.1]:2222)' can't be established.
ED25519 key fingerprint is SHA256:mnWAlUlxQW0Z86NJWybUJC73BfiMK1lgtcNgvHBeViI.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Warning: Permanently added '[127.0.0.1]:2222' (ED25519) to the list of known hosts.
...

$ ssh-keygen -F [127.0.0.1]:2222 -f ~/.ssh/known_hosts
# Host [127.0.0.1]:2222 found: line 1 
|1|ZDcetDreN82WbhfnYpUoU3bBHYU=|Rvgq2pUwfs3hgCXJso8gm2eEJKs= ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJphwiExvBJdrF9b5KFoYPm39oi76WbMcrl+rRulhe6P
# Host [127.0.0.1]:2222 found: line 2 
|1|J2QVgaSQxMPSySZ7Ftul7MmDxV8=|gp/FqEY44wTyMGeA9eR15lpf1yk= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCqJ1Qo9i7j3IC4e3tIpsOWBgcyJJ95WiMafFcTCNmwfvNEyLpRXvKl9jYtTdFCUivNpcOgNn3Kx4oAJsRmjnUvcpFeWr7pe/eC7fs5ecAYCfC4v0xepIqsU72+2rC2d0tXFQri0SAFW0j84EYf/oPfqKRLvgu/7Md/AXHlNBIVuJRI/imCbt0NiuJnOK4jJZUakEQcrT9NCMQMAgKpKY18hCSpbOlF6z+tHI4DtlDHplMMuxbAexY7QszgyqvTT6RQsuShAiq8jmpYHgHW4iGAi6Idp5DREVydXy6vhknLlbOkrlksHmQyMFO0qTKbA+Ddzy/sWaLM3tXmidr3bAwL8QJ6JrkI6IdxmTiO1wK0t/DXkiDVkS9klXf1AGfY5iE2HO9VvmcSCt1c4Q95/7jnEwJLBqQd0od8jOwlCBfqUf/UCbug5+KHen0J7Vc3IWerWkV3CvhGt1jH1fOvrL3T+Ik5Kcs3B63KaOKMP3Tz1LfeSNI1t/Bv7rAg2cr9D6M=
# Host [127.0.0.1]:2222 found: line 3 
|1|hvZF+vUbwqSOc0Bua8l11uqas60=|Dw4pDhJLKiB41qGquLiVPCPkdhQ= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBGDwpDZ9km0hCEsk2Ikne12JixK8cYL0l1Nw08h1zA1+Buan30FuxVJRJW+shZ1Oy8Ri/kyy731/b3tFHtdIg0Q=

$ docker stop vuls-target

// Prepare another machine that can connect via SSH
$ docker run --rm -itd -p 2222:22 --name vuls-target vuls-target:debian12
3d19b194bf233baf017ccd73a1cf38987ace35fd3ad95106c25dd913209da34e

$ ssh-keyscan -p 2222 127.0.0.1
# 127.0.0.1:2222 SSH-2.0-OpenSSH_9.2p1 Debian-2+deb12u3
# 127.0.0.1:2222 SSH-2.0-OpenSSH_9.2p1 Debian-2+deb12u3
# 127.0.0.1:2222 SSH-2.0-OpenSSH_9.2p1 Debian-2+deb12u3
[127.0.0.1]:2222 ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDBXAs5U99aC1+fsXzPApR0PdY0OfFZLGtJ95aYcjT+z9x5NfeN7QnVnXay1ECkZht6Q2jTNa+fto2VvglYx3MXiMjzY2ucjFGiFZZyIp0A1AbYaIUJIa/RM4b9nWs2/agvVZvKT6hWuxBhPLPWohDFvvXVLSJQgY0Pcc8Low6tgjd2h4khVf+XRwSy8rdhIjSQxZYLQOlUrPSMN/4XmZCzQGxEkqm/cbqrJGD/TKyvL8I/oF5dB70X+ACcEPCOiaeWoumYySrwH+ekWXfEey4TfubdCWAH3WPqyDXDxMsVuyjWR7g6LAgqo84kDxaM5P+DNOzbGXWztzoRRx/R10V08t3TX8QENM1IGQNQOli2VFBstCP9gYFjqTSpphS++t2q0DA3ESCYmKD1lmWjRQZB1mLT8ApmtMDYM/YS0fWr3zRJL240GnRFE3WFWTFc6vck1rV4I/277S05Y3Ct6q8IZDSmlrM8vde0jJZsOAxJ43bWOIbgDVGje5qKW4matR0=
# 127.0.0.1:2222 SSH-2.0-OpenSSH_9.2p1 Debian-2+deb12u3
[127.0.0.1]:2222 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDaZfvGHBvUUn8m5LlqDzHyoVOL85NW/wVpPxUFDUb9vf6XvyEc1+aM7gQwCIDP6pqdBq5wDeDu4wG2RghIvT0k=
# 127.0.0.1:2222 SSH-2.0-OpenSSH_9.2p1 Debian-2+deb12u3
[127.0.0.1]:2222 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBdR67BinH0Rn/oKwN2NM0Vek6oNpDhns5cphWO0gaM8

$ ssh -i /home/vuls/.ssh/id_rsa -p 2222 root@127.0.0.1
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ED25519 key sent by the remote host is
SHA256:QY87P9WTPDn3GAIVs99WmFEhOusyHM09GsquBqGpyb4.
Please contact your system administrator.
Add correct host key in /home/vuls/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /home/vuls/.ssh/known_hosts:3
  remove with:
  ssh-keygen -f "/home/vuls/.ssh/known_hosts" -R "[127.0.0.1]:2222"
Host key for [127.0.0.1]:2222 has changed and you have requested strict checking.
Host key verification failed.
```

Could you please use ssh-keygen and ssh-keyscan to compare the host key in your known_hosts with the host key of the host you are connecting to?

**Comment by Rattkener** [comment]
Aye I got access to the system recently no host key conflicts on my machine but vuls doesn't seem to agree.

**Comment by MaineK00n** [comment]
Could you provide a debug log of when you ssh into the machine that is failing with vuls?
```console
$ ssh -vvv -i /home/vuls/.ssh/id_rsa -p 2222 root@127.0.0.1
OpenSSH_8.9p1 Ubuntu-3ubuntu0.10, OpenSSL 3.0.2 15 Mar 2022
debug1: Reading configuration data /home/vuls/.ssh/config
...
debug1: Authenticating to 127.0.0.1:2222 as 'root'
debug3: put_host_port: [127.0.0.1]:2222
debug3: record_hostkey: found key type ED25519 in file /home/vuls/.ssh/known_hosts:1
debug3: load_hostkeys_file: loaded 1 keys from [127.0.0.1]:2222
debug1: load_hostkeys: fopen /home/vuls/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug3: order_hostkeyalgs: have matching best-preference key type ssh-ed25519-cert-v01@openssh.com, using HostkeyAlgorithms verbatim
...
debug1: Server host key: ssh-ed25519 SHA256:QY87P9WTPDn3GAIVs99WmFEhOusyHM09GsquBqGpyb4
debug3: put_host_port: [127.0.0.1]:2222
debug3: put_host_port: [127.0.0.1]:2222
debug3: record_hostkey: found key type ED25519 in file /home/vuls/.ssh/known_hosts:1
debug3: load_hostkeys_file: loaded 1 keys from [127.0.0.1]:2222
debug1: load_hostkeys: fopen /home/vuls/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ED25519 key sent by the remote host is
SHA256:QY87P9WTPDn3GAIVs99WmFEhOusyHM09GsquBqGpyb4.
Please contact your system administrator.
Add correct host key in /home/vuls/.ssh/known_hosts to get rid of this message.
Offending ED25519 key in /home/vuls/.ssh/known_hosts:1
  remove with:
  ssh-keygen -f "/home/vuls/.ssh/known_hosts" -R "[127.0.0.1]:2222"
Host key for [127.0.0.1]:2222 has changed and you have requested strict checking.
Host key verification failed.
```

**Comment by Rattkener** [comment]
Certainly, overly revealing info removed:

`ssh -vvvv -i ~/.ssh/id_rsa RSmith@69.167.186.216 'echo hi' &> ./ssh.log
 
cat ./ssh.log
OpenSSH_8.7p1, OpenSSL 3.0.7 1 Nov 2022
debug1: Reading configuration data /etc/ssh/ssh_config
debug3: /etc/ssh/ssh_config line 55: Including file /etc/ssh/ssh_config.d/50-redhat.conf depth 0
debug1: Reading configuration data /etc/ssh/ssh_config.d/50-redhat.conf
debug2: checking match for 'final all' host ${REDACTED_REMOTE_HOST_IP} originally ${REDACTED_REMOTE_HOST_IP}
debug3: /etc/ssh/ssh_config.d/50-redhat.conf line 3: not matched 'final'
debug2: match not found
debug3: /etc/ssh/ssh_config.d/50-redhat.conf line 5: Including file /etc/crypto-policies/back-ends/openssh.config depth 1 (parse only)
debug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config
debug3: gss kex names ok: [gss-curve25519-sha256-,gss-nistp256-sha256-,gss-group14-sha256-,gss-group16-sha512-]
debug3: kex names ok: [curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512]
debug1: configuration requests final Match pass
debug2: resolve_canonicalize: hostname ${REDACTED_REMOTE_HOST_IP} is address
debug1: re-parsing configuration
debug1: Reading configuration data /etc/ssh/ssh_config
debug3: /etc/ssh/ssh_config line 55: Including file /etc/ssh/ssh_config.d/50-redhat.conf depth 0
debug1: Reading configuration data /etc/ssh/ssh_config.d/50-redhat.conf
debug2: checking match for 'final all' host ${REDACTED_REMOTE_HOST_IP} originally ${REDACTED_REMOTE_HOST_IP}
debug3: /etc/ssh/ssh_config.d/50-redhat.conf line 3: matched 'final'
debug2: match found
debug3: /etc/ssh/ssh_config.d/50-redhat.conf line 5: Including file /etc/crypto-policies/back-ends/openssh.config depth 1
debug1: Reading configuration data /etc/crypto-policies/back-ends/openssh.config
debug3: gss kex names ok: [gss-curve25519-sha256-,gss-nistp256-sha256-,gss-group14-sha256-,gss-group16-sha512-]
debug3: kex names ok: [curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512]
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/home/${REDACTED_REMOTE_LOCAL_USER}/.ssh/known_hosts'
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/home/${REDACTED_REMOTE_LOCAL_USER}/.ssh/known_hosts2'
debug3: ssh_connect_direct: entering
debug1: Connecting to ${REDACTED_REMOTE_HOST_IP} [${REDACTED_REMOTE_HOST_IP}] port 22.
debug3: set_sock_tos: set socket 3 IP_TOS 0x48
debug1: Connection established.
debug1: identity file /home/${REDACTED_REMOTE_LOCAL_USER}/.ssh/id_rsa type 0
debug1: identity file /home/${REDACTED_REMOTE_LOCAL_USER}/.ssh/id_rsa-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.7
debug1: Remote protocol version 2.0, remote software version OpenSSH_7.4
debug1: compat_banner: match: OpenSSH_7.4 pat OpenSSH_7.4* compat 0x04000006
debug2: fd 3 setting O_NONBLOCK
debug1: Authenticating to ${REDACTED_REMOTE_HOST_IP}:22 as '${REDACTED_REMOTE_USER}'
debug3: record_hostkey: found key type ED25519 in file /home/${REDACTED_REMOTE_LOCAL_USER}/.ssh/known_hosts:1
debug3: record_hostkey: found key type ECDSA in file /home/${REDACTED_REMOTE_LOCAL_USER}/.ssh/known_hosts:2
debug3: load_hostkeys_file: loaded 2 keys from ${REDACTED_REMOTE_HOST_IP}
debug1: load_hostkeys: fopen /home/${REDACTED_REMOTE_LOCAL_USER}/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug3: order_hostkeyalgs: have matching best-preference key type ssh-ed25519-cert-v01@openssh.com, using HostkeyAlgorithms verbatim
debug3: send packet: type 20
debug1: SSH2_MSG_KEXINIT sent
debug3: receive packet: type 20
debug1: SSH2_MSG_KEXINIT received
debug2: local client KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,diffie-hellman-group18-sha512,ext-info-c,kex-strict-c-v00@openssh.com
debug2: host key algorithms: ssh-ed25519-cert-v01@openssh.com,ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,sk-ssh-ed25519-cert-v01@openssh.com,sk-ecdsa-sha2-nistp256-cert-v01@openssh.com,rsa-sha2-512-cert-v01@openssh.com,rsa-sha2-256-cert-v01@openssh.com,ssh-ed25519,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,sk-ssh-ed25519@openssh.com,sk-ecdsa-sha2-nistp256@openssh.com,rsa-sha2-512,rsa-sha2-256
debug2: ciphers ctos: aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes256-ctr,aes128-gcm@openssh.com,aes128-ctr
debug2: ciphers stoc: aes256-gcm@openssh.com,chacha20-poly1305@openssh.com,aes256-ctr,aes128-gcm@openssh.com,aes128-ctr
debug2: MACs ctos: hmac-sha2-256-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha1,umac-128@openssh.com,hmac-sha2-512
debug2: MACs stoc: hmac-sha2-256-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha2-256,hmac-sha1,umac-128@openssh.com,hmac-sha2-512
debug2: compression ctos: none,zlib@openssh.com,zlib
debug2: compression stoc: none,zlib@openssh.com,zlib
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug2: peer server KEXINIT proposal
debug2: KEX algorithms: curve25519-sha256,curve25519-sha256@libssh.org,diffie-hellman-group-exchange-sha256,diffie-hellman-group18-sha512,diffie-hellman-group14-sha256,diffie-hellman-group16-sha512,kex-strict-s-v00@openssh.com
debug2: host key algorithms: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ssh-ed25519
debug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com
debug2: MACs ctos: umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com
debug2: MACs stoc: umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com
debug2: compression ctos: none,zlib@openssh.com
debug2: compression stoc: none,zlib@openssh.com
debug2: languages ctos: 
debug2: languages stoc: 
debug2: first_kex_follows 0 
debug2: reserved 0 
debug3: kex_choose_conf: will use strict KEX ordering
debug1: kex: algorithm: curve25519-sha256
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: aes256-gcm@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: aes256-gcm@openssh.com MAC: <implicit> compression: none
debug1: kex: curve25519-sha256 need=32 dh_need=32
debug1: kex: curve25519-sha256 need=32 dh_need=32
debug3: send packet: type 30
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug3: receive packet: type 31
debug1: SSH2_MSG_KEX_ECDH_REPLY received
debug1: Server host key: ssh-ed25519 SHA256:XUKxSPI4Og5irkZ6p1CidLGfI630UXwE6jU3Z30grfs
debug3: record_hostkey: found key type ED25519 in file /home/${REDACTED_REMOTE_LOCAL_USER}/.ssh/known_hosts:1
debug3: record_hostkey: found key type ECDSA in file /home/${REDACTED_REMOTE_LOCAL_USER}/.ssh/known_hosts:2
debug3: load_hostkeys_file: loaded 2 keys from ${REDACTED_REMOTE_HOST_IP}
debug1: load_hostkeys: fopen /home/${REDACTED_REMOTE_LOCAL_USER}/.ssh/known_hosts2: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts: No such file or directory
debug1: load_hostkeys: fopen /etc/ssh/ssh_known_hosts2: No such file or directory
debug1: Host '${REDACTED_REMOTE_HOST_IP}' is known and matches the ED25519 host key.
debug1: Found key in /home/${REDACTED_REMOTE_LOCAL_USER}/.ssh/known_hosts:1
debug3: send packet: type 21
debug1: ssh_packet_send2_wrapped: resetting send seqnr 3
debug2: set_newkeys: mode 1
debug1: rekey out after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug3: receive packet: type 21
debug1: ssh_packet_read_poll2: resetting read seqnr 3
debug1: SSH2_MSG_NEWKEYS received
debug2: set_newkeys: mode 0
debug1: rekey in after 4294967296 blocks
debug1: Will attempt key: /home/${REDACTED_REMOTE_LOCAL_USER}/.ssh/id_rsa RSA SHA256:s54ZFtbqI9f5jkocI3lhKBxBDT81FPTATdyRt87Rm9Q explicit
debug2: pubkey_prepare: done
debug3: send packet: type 5
debug3: receive packet: type 7
debug1: SSH2_MSG_EXT_INFO received
debug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>
debug3: receive packet: type 6
debug2: service_accept: ssh-userauth
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug3: send packet: type 50
debug3: receive packet: type 51
debug1: Authentications that can continue: publickey,password,keyboard-interactive
debug3: start over, passed a different list publickey,password,keyboard-interactive
debug3: preferred gssapi-with-mic,publickey,keyboard-interactive,password
debug3: authmethod_lookup publickey
debug3: remaining preferred: keyboard-interactive,password
debug3: authmethod_is_enabled publickey
debug1: Next authentication method: publickey
debug1: Offering public key: /home/${REDACTED_REMOTE_LOCAL_USER}/.ssh/id_rsa RSA SHA256:s54ZFtbqI9f5jkocI3lhKBxBDT81FPTATdyRt87Rm9Q explicit
debug3: send packet: type 50
debug2: we sent a publickey packet, wait for reply
debug3: receive packet: type 60
debug1: Server accepts key: /home/${REDACTED_REMOTE_LOCAL_USER}/.ssh/id_rsa RSA SHA256:s54ZFtbqI9f5jkocI3lhKBxBDT81FPTATdyRt87Rm9Q explicit
debug3: sign_and_send_pubkey: RSA SHA256:s54ZFtbqI9f5jkocI3lhKBxBDT81FPTATdyRt87Rm9Q
debug3: sign_and_send_pubkey: signing using rsa-sha2-256 SHA256:s54ZFtbqI9f5jkocI3lhKBxBDT81FPTATdyRt87Rm9Q
debug3: send packet: type 50
debug3: receive packet: type 52
Authenticated to ${REDACTED_REMOTE_HOST_IP} ([${REDACTED_REMOTE_HOST_IP}]:22) using "publickey".
debug1: pkcs11_del_provider: called, provider_id = (null)
debug1: channel 0: new [client-session]
debug3: ssh_session2_open: channel_new: 0
debug2: channel 0: send open
debug3: send packet: type 90
debug1: Requesting no-more-sessions@openssh.com
debug3: send packet: type 80
debug1: Entering interactive session.
debug1: pledge: filesystem full
debug3: receive packet: type 80
debug1: client_input_global_request: rtype hostkeys-00@openssh.com want_reply 0
debug3: client_input_hostkeys: received RSA key SHA256:/nebICqWSnglhDZOi7uo+nci5HaLNfVMahYAMk12DOY
debug3: client_input_hostkeys: received ECDSA key SHA256:9NckMXqMIFYrm4ftGrYj58cJGsYhkrb0jVcDoC7EH3I
debug3: client_input_hostkeys: received ED25519 key SHA256:XUKxSPI4Og5irkZ6p1CidLGfI630UXwE6jU3Z30grfs
debug1: client_input_hostkeys: searching /home/${REDACTED_REMOTE_LOCAL_USER}/.ssh/known_hosts for ${REDACTED_REMOTE_HOST_IP} / (none)
debug3: hostkeys_foreach: reading file "/home/${REDACTED_REMOTE_LOCAL_USER}/.ssh/known_hosts"
debug3: hostkeys_find: found ssh-ed25519 key at /home/${REDACTED_REMOTE_LOCAL_USER}/.ssh/known_hosts:1
debug3: hostkeys_find: found ecdsa-sha2-nistp256 key at /home/${REDACTED_REMOTE_LOCAL_USER}/.ssh/known_hosts:2
debug1: client_input_hostkeys: searching /home/${REDACTED_REMOTE_LOCAL_USER}/.ssh/known_hosts2 for ${REDACTED_REMOTE_HOST_IP} / (none)
debug1: client_input_hostkeys: hostkeys file /home/${REDACTED_REMOTE_LOCAL_USER}/.ssh/known_hosts2 does not exist
debug3: client_input_hostkeys: 3 server keys: 1 new, 1 retained, 1 incomplete match. 0 to remove
debug3: client_input_hostkeys: asking server to prove ownership for 1 keys
debug3: send packet: type 80
debug3: receive packet: type 91
debug2: channel_input_open_confirmation: channel 0: callback start
debug2: fd 3 setting TCP_NODELAY
debug3: set_sock_tos: set socket 3 IP_TOS 0x20
debug2: client_session2_setup: id 0
debug1: Sending command: echo hi
debug2: channel 0: request exec confirm 1
debug3: send packet: type 98
debug2: channel_input_open_confirmation: channel 0: callback done
debug2: channel 0: open confirm rwindow 0 rmax 32768
debug3: receive packet: type 81
debug1: client_global_hostkeys_private_confirm: server used untrusted RSA signature algorithm ssh-rsa for key 0, disregarding
debug3: hostkeys_foreach: reading file "/home/${REDACTED_REMOTE_LOCAL_USER}/.ssh/known_hosts"
debug3: host_delete: ED25519 key already at /home/${REDACTED_REMOTE_LOCAL_USER}/.ssh/known_hosts:1
debug3: host_delete: ECDSA key already at /home/${REDACTED_REMOTE_LOCAL_USER}/.ssh/known_hosts:2
debug1: update_known_hosts: known hosts file /home/${REDACTED_REMOTE_LOCAL_USER}/.ssh/known_hosts2 does not exist
debug2: channel 0: rcvd adjust 2097152
debug3: receive packet: type 99
debug2: channel_input_status_confirm: type 99 id 0
debug2: exec request accepted on channel 0
debug3: receive packet: type 96
debug2: channel 0: rcvd eof
debug2: channel 0: output open -> drain
debug3: receive packet: type 98
debug1: client_input_channel_req: channel 0 rtype exit-status reply 0
debug3: receive packet: type 98
debug1: client_input_channel_req: channel 0 rtype eow@openssh.com reply 0
debug2: channel 0: rcvd eow
debug2: chan_shutdown_read: channel 0: (i0 o1 sock -1 wfd 4 efd 6 [write])
debug2: channel 0: input open -> closed
debug3: receive packet: type 97
debug2: channel 0: rcvd close
debug3: channel 0: will not send data after close
hi
debug3: channel 0: will not send data after close
debug2: channel 0: obuf empty
debug2: chan_shutdown_write: channel 0: (i3 o1 sock -1 wfd 5 efd 6 [write])
debug2: channel 0: output drain -> closed
debug2: channel 0: almost dead
debug2: channel 0: gc: notify user
debug2: channel 0: gc: user detached
debug2: channel 0: send close
debug3: send packet: type 97
debug2: channel 0: is dead
debug2: channel 0: garbage collecting
debug1: channel 0: free: client-session, nchannels 1
debug3: channel 0: status: The following connections are open:
  #0 client-session (t4 r0 i3/0 o3/0 e[write]/0 fd -1/-1/6 sock -1 cc -1)

debug3: send packet: type 1
Transferred: sent 3848, received 2724 bytes, in 0.2 seconds
Bytes per second: sent 20719.9, received 14667.6
debug1: Exit status 0


`

**Comment by MaineK00n** [comment]
To address this issue, I would like to reproduce your environment. Can you provide an environment that can be reproduced using Docker or Vagrant?

**Comment by Rattkener** [comment]
I went to check today, no changes made to environment as I had other tasks that needed handling, new blobs were copied in the scan process. Now scan function is working as intended... I can't even begin to explain what happened here and I have no idea how to reproduce :\

**Comment by MaineK00n** [comment]
So I'll close this issue for now. If you have a similar problem, please open it again.
