### ISSUE TITLE
Support Gentoo Linux

### ISSUE THREAD

**Issue by alexanderhaensch** [future-architect/vuls#200]
Gentoo Linux has a program 'glsa-check' that can be used to support gentoo. Gentoos security team releases information about vulnerable packages on [1]. Glsa-check compares the list with the installed package versions. More info: [2]
While it is possible to run glsa-check via cronjob, it would be brilliant to have the results in vuls.

The required package would be: app-portage/gentoolkit

[1]https://security.gentoo.org/glsa/
[2]https://wiki.gentoo.org/wiki/GLSA

**Comment by kotakanbe** [comment]
Memo: 
OVAL https://dev.gentoo.org/~swift/docs/security_benchmarks/gentoo-oval.txt

**Comment by kotakanbe** [comment]
Memo:

https://security.gentoo.org/subscribe
```
Check your system's status
Use glsa-check to check your system's security status.
To see all advisories that affect your system, run:

% glsa-check -t affected
```

**Comment by necrose99** [comment]
speaking of Gentoo , in my Gentoo Arm64 chroot  it compiles and runs..

**Comment by necrose99** [comment]
i made some template packges ,  my home intweerwebs have only cell based link 
APT com has shit wires in our corrnor lease is THANK the gods coming to a close. 
https://github.com/pentoo/pentoo-overlay/issues/352
@pentoo  the Gentoo Pentesting Edition.... Livecd... etc.. 
@linxon was alble to further refine them down to working packages.. 

I can Confirm , @ARM64  @scaleway hosting in 2018 over summer , 
debian based host and /gentoo (chroot) I was able to build vuls.io CLI  , i have ports to a number of @pentoo packages siting in my dropbox.
runs quite nice on Gentoo  RPI 
https://github.com/sakaki-/gentoo-on-rpi3-64bit/releases

*/var/tmp or /tmp/portage ,  PACKAGENAME** ...... 

**ebuild NAM.ebuild rpm    >>> builds rpmspec , rpm of package**  
(This is a little known feature of Gentoo portage)  
(can build deps for vuils.io scanner and the gui to rpms/and ore specs etc.. ) 
Can go fishing to get these... from above formention directores. 
however it may refrance Gentoo packages in rpmspec.. however wala template none the less.. 
Quick and dirty RPM builds 

https://github.com/debbuild/debbuild  RPMSPEC to Debian packer managler... 
wich may help..

**Comment by kotakanbe** [comment]
If you still want this, please re-open the issue.

**Comment by necrose99** [comment]
Already in Pentoo Linux..
Gentoo Users can add pentoo overlay.
