### ISSUE TITLE
Not able to install gomail fails

### ISSUE THREAD

**Issue by duanebc** [future-architect/vuls#202]
`[root@5dd37d7a-5a06-4241-826d-a755490cefff vuls-master]# go build main.go
/root/go/src/github.com/future-architect/vuls/cache/bolt.go:25:2: cannot find package "github.com/boltdb/bolt" in any of:
	/usr/local/go/src/github.com/boltdb/bolt (from $GOROOT)
	/root/go/src/github.com/boltdb/bolt (from $GOPATH)
/root/go/src/github.com/future-architect/vuls/commands/cmdutil.go:6:2: cannot find package "github.com/howeyc/gopass" in any of:
	/usr/local/go/src/github.com/howeyc/gopass (from $GOROOT)
	/root/go/src/github.com/howeyc/gopass (from $GOPATH)
/root/go/src/github.com/future-architect/vuls/commands/discover.go:31:2: cannot find package "github.com/kotakanbe/go-pingscanner" in any of:
	/usr/local/go/src/github.com/kotakanbe/go-pingscanner (from $GOROOT)
	/root/go/src/github.com/kotakanbe/go-pingscanner (from $GOPATH)
/root/go/src/github.com/future-architect/vuls/scan/sshutil.go:34:2: cannot find package "golang.org/x/crypto/ssh" in any of:
	/usr/local/go/src/golang.org/x/crypto/ssh (from $GOROOT)
	/root/go/src/golang.org/x/crypto/ssh (from $GOPATH)
/root/go/src/github.com/future-architect/vuls/scan/sshutil.go:35:2: cannot find package "golang.org/x/crypto/ssh/agent" in any of:
	/usr/local/go/src/golang.org/x/crypto/ssh/agent (from $GOROOT)
	/root/go/src/golang.org/x/crypto/ssh/agent (from $GOPATH)
/root/go/src/github.com/future-architect/vuls/report/mail.go:27:2: cannot find package "gopkg.in/gomail.v2" in any of:
	/usr/local/go/src/gopkg.in/gomail.v2 (from $GOROOT)
	/root/go/src/gopkg.in/gomail.v2 (from $GOPATH)
`

Installed each one individually, and still getting the same issue (just hangs there)

`[root@5dd37d7a-5a06-4241-826d-a755490cefff vuls-master]# go get -v gopkg.in/gomail.v2
Fetching https://gopkg.in/gomail.v2?go-get=1
Parsing meta tags from https://gopkg.in/gomail.v2?go-get=1 (status code 200)
get "gopkg.in/gomail.v2": found meta tag main.metaImport{Prefix:"gopkg.in/gomail.v2", VCS:"git", RepoRoot:"https://gopkg.in/gomail.v2"} at https://gopkg.in/gomail.v2?go-get=1
gopkg.in/gomail.v2 (download)
`

I tried building as the go get failed first.  This is a CentOS 6.* testing server I just created, installed go and dependencies as mentioned.  

Working attempt from Ubuntu 14.04 server.
`root@media:~#  go get -v gopkg.in/gomail.v2
Fetching https://gopkg.in/gomail.v2?go-get=1
Parsing meta tags from https://gopkg.in/gomail.v2?go-get=1 (status code 200)
get "gopkg.in/gomail.v2": found meta tag main.metaImport{Prefix:"gopkg.in/gomail.v2", VCS:"git", RepoRoot:"https://gopkg.in/gomail.v2"} at https://gopkg.in/gomail.v2?go-get=1
gopkg.in/gomail.v2 (download)
Fetching https://gopkg.in/alexcesaro/quotedprintable.v3?go-get=1
Parsing meta tags from https://gopkg.in/alexcesaro/quotedprintable.v3?go-get=1 (status code 200)
get "gopkg.in/alexcesaro/quotedprintable.v3": found meta tag main.metaImport{Prefix:"gopkg.in/alexcesaro/quotedprintable.v3", VCS:"git", RepoRoot:"https://gopkg.in/alexcesaro/quotedprintable.v3"} at https://gopkg.in/alexcesaro/quotedprintable.v3?go-get=1
gopkg.in/alexcesaro/quotedprintable.v3 (download)
gopkg.in/alexcesaro/quotedprintable.v3
gopkg.in/gomail.v2
`

**Comment by hkato** [comment]
I was facing with the same issue.

https://github.com/future-architect/vuls/blob/master/README.md
Step3. Install requirements
- git v2

**Comment by sadayuki-matsuno** [comment]
@duanebc 
Now gomail was replaced with go/smtp, you can use Vuls without git v2.
ref #211

**Comment by kotakanbe** [comment]
If you are still in trouble, please reopen the issue.
Thanks

**Comment by duanebc** [comment]
> root@media:~# go get -v github.com/future-architect/vuls
github.com/aws/aws-sdk-go (download)
github.com/go-ini/ini (download)
github.com/jmespath/go-jmespath (download)
github.com/boltdb/bolt (download)
github.com/cenkalti/backoff (download)
github.com/gosuri/uitable (download)
github.com/mattn/go-runewidth (download)
github.com/jroimartin/gocui (download)
github.com/nsf/termbox-go (download)
Fetching https://golang.org/x/crypto/ssh?go-get=1
Segmentation fault (core dumped)


> root@media:~# git --version
git version 2.10.1

That's after installing git v2?  Can you make it a bit more clear what the fix is?

**Comment by kotakanbe** [comment]
Probably the error was occurred in go runtime....
Please try using the latest version of go.

**Comment by duanebc** [comment]
> root@media:~# dpkg -l | grep golang
ii  golang-1.6                                1.6-0ubuntu1~14.04                                  all          Go programming language compiler - metapackage
ii  golang-1.6-doc                            1.6-0ubuntu1~14.04                                  all          Go programming language - documentation
ii  golang-1.6-go                             1.6-0ubuntu1~14.04                                  amd64        Go programming language compiler, linker, compiled stdlib
ii  golang-1.6-src                            1.6-0ubuntu1~14.04                                  amd64        Go programming language - source files
ii  golang-go.tools                           0.0~hg20131126-3                                    amd64        supplementary Go tools
ii  golang-go.tools-dev                       0.0~hg20131126-3                                    all          supplementary Go tools (development files)
ii  golang-src                                2:1.6-1ubuntu2~ubuntu14.04.1~ppa1                   amd64        Go programming language - source files
root@media:~# go get -v github.com/future-architect/vuls
Fetching https://golang.org/x/crypto/ssh?go-get=1
Segmentation fault (core dumped)

> root@media:~# go version
go version xgcc (Ubuntu 4.9.3-0ubuntu4) 4.9.3 linux/amd64

**Comment by kotakanbe** [comment]
Would you try with Go 1.7?

**Comment by duanebc** [comment]
That worked thanks.  May want to change your documentation to show golang 1.7 or greater now possibly.

**Comment by kotakanbe** [comment]
Yeah, I fixed README.
Thanks :)
