### ISSUE TITLE
Add HipChat Support

### ISSUE THREAD

**Issue by bscott** [future-architect/vuls#203]
Add Support for HipChat

**Comment by kotakanbe** [comment]
Pull Request Welcome :)

**Comment by kotakanbe** [comment]
Does anyone want to implement it?
I think you can do it by referring to it.

**Comment by kazuminn** [comment]
Do you want it yet? If you want it, +1

**Comment by kotakanbe** [comment]
@bscott @wnoguchi

Finally, @kazuminn worked HipChar support. please test if you like before merging to master.
https://github.com/future-architect/vuls/pull/593

**Comment by kotakanbe** [comment]
<img width="851" alt="2018-01-29 17 22 30" src="https://user-images.githubusercontent.com/534611/37015688-fa3588fa-214b-11e8-8984-1b08509fa956.png">

**Comment by kotakanbe** [comment]
Document

https://github.com/vulsdoc/vuls/pull/19/files
https://github.com/vulsdoc/vuls/pull/18/files

**Comment by kotakanbe** [comment]
How to test P/R

```
cd /path/to/vuls
git fetch origin pull/593/head:hipchat
git checkout hipchat
make dep
make install
-- edit config.toml --
vuls scan
vuls report -to-hipchat
```

**Comment by RVIRUS0817** [comment]
![vuls-hipchat](https://user-images.githubusercontent.com/5633085/37021270-58ce9954-2162-11e8-821c-190bf540a123.png)

I tried test!!
No Problem!!!!
