### ISSUE TITLE
Is there a way to scan Ubuntu machines with OVAL

### ISSUE THREAD

**Issue by karmatikde** [future-architect/vuls#2050]
Apologies in advance if this has been discussed before. In the README file it is mentioned that High-quality scans for **Ubuntu** can be done with **OVAL**. However, when I run the scans it shows me the following message. 
`Skip OVAL and Scan with gost alone`
Is there a way to scan Ubuntu machines with OVAL? If not, are there any plans to offer this feature in the future?

**Comment by MaineK00n** [comment]
For Ubuntu, gost data source provides detection equivalent to OVAL.
I apologize for any confusion caused by reading the README.

In the future, we would like to allow users to freely choose their data source.

**Comment by karmatikde** [comment]
Thank you very much for the quick response. I really appreciate it.
