### ISSUE TITLE
https://hub.docker.com/r/vuls/go-cve-dictionary/ is empty

### ISSUE THREAD

**Issue by stapelberg** [future-architect/vuls#208]
Running the instructions from https://github.com/future-architect/vuls/tree/master/setup/docker fails:
```
$ docker pull vuls/go-cve-dictionary
Using default tag: latest
Pulling repository docker.io/vuls/go-cve-dictionary
Tag latest not found in repository docker.io/vuls/go-cve-dictionary
```

Looking at the docker hub, no tags or build details are shown:
![2016-10-09-211010_851x726_scrot](https://cloud.githubusercontent.com/assets/55506/19222978/cc5c6bf4-8e64-11e6-8f01-b0f344eb7aff.png)

**Comment by stapelberg** [comment]
The same holds true for all the other docker images under the “vuls” organization. Is vuls no longer available via Docker?

**Comment by sadayuki-matsuno** [comment]
@stapelberg 
I changed all the images into the auto built one at last night.
Now the auto building is running, you can use these in a few minutes.

**Comment by kotakanbe** [comment]
If you are still in trouble, please reopen the issue.
Thanks
