### ISSUE TITLE
scan localhost?

### ISSUE THREAD

**Issue by Yashiroo** [future-architect/vuls#210]
Hi,
I'm just trying out vuls, i installed docker on my vps and am following the  instructions, but i do not understand the config.toml configuration step. I want to run this inside a docker container and want to scan the docker host with it. I do not know how to configure the config.toml file so it does not use ssh to connect to the host.
Please let me know if there is a simple setup like this, or if i am missing something here.
Thanks,

**Comment by kotakanbe** [comment]
Local scan mode(without ssh) is not yet supported.
( @NickNeedsAName is working in #103 )

For now, you have to run SSHd on the target host.
