### ISSUE TITLE
vuls prepare silently fails to install yum-plugin-security RHEL 6.7

### ISSUE THREAD

**Issue by trocster** [future-architect/vuls#22]
Hello, 

[vuls@aserver ~]$ vuls prepare -debug bserver
INFO[0000] Start Preparing (config: /home/vuls/config.toml)
[Apr 13 10:45:48]  INFO [localhost] Detecting OS...
DEBU[0000] Command: set -o pipefail; ls /etc/debian_version
DEBU[0000] SSH executed. cmd: set -o pipefail; ls /etc/debian_version, status: <nil>
stdout:
ls: cannot access /etc/debian_version: No such file or directory

stderr:

[Apr 13 10:45:48] DEBUG [localhost] Not Debian like Linux. Host: bserver.domain.com:22
DEBU[0000] Command: set -o pipefail; ls /etc/fedora-release
DEBU[0000] SSH executed. cmd: set -o pipefail; ls /etc/fedora-release, status: <nil>
stdout:
ls: cannot access /etc/fedora-release: No such file or directory

stderr:

DEBU[0000] Command: set -o pipefail; ls /etc/redhat-release
DEBU[0000] SSH executed. cmd: set -o pipefail; ls /etc/redhat-release, status: <nil>
stdout:
/etc/redhat-release

stderr:

DEBU[0000] Command: set -o pipefail; cat /etc/redhat-release
DEBU[0001] SSH executed. cmd: set -o pipefail; cat /etc/redhat-release, status: <nil>
stdout:
Red Hat Enterprise Linux Server release 6.7 (Santiago)

stderr:

[Apr 13 10:45:49]  INFO [localhost] (1/1) Successfully detected. bserver: rhel 6.7
[Apr 13 10:45:49] DEBUG [localhost] []scan.osTypeInterface{
  &scan.redhat{
    linux: scan.linux{
      ServerInfo: config.ServerInfo{
        ServerName:  "bserver",
        User:        "root",
        Password:    "",
        Host:        "bserver.domain.com",
        Port:        "22",
        KeyPath:     "/home/vuls/.ssh/id_rsa_k1",
        KeyPassword: "",
        SudoOpt:     config.SudoOption{
          ExecBySudo:   true,
          ExecBySudoSh: false,
        },
        CpeNames:        []string{},
        LogMsgAnsiColor: "\x1b[35m",
      },
      Family:     "rhel",
      Release:    "6.7",
      osPackages: scan.osPackages{
        Packages:         models.PackageInfoList{},
        UnsecurePackages: scan.CvePacksList{},
      },
      log: &logrus.Entry{
        Logger: &logrus.Logger{
          Out: &os.File{
            file: &os.file{
              fd:      2,
              name:    "/dev/stderr",
              dirinfo: (*os.dirInfo)(nil),
            },
          },
          Hooks: {
            0x01: []logrus.Hook{
              &lfshook.lfsHook{
                paths: {
                  0x04: "/var/log/vuls/bserver:22.log",
                  0x03: "/var/log/vuls/bserver:22.log",
                  0x02: "/var/log/vuls/bserver:22.log",
                  0x01: "/var/log/vuls/bserver:22.log",
                  0x00: "/var/log/vuls/bserver:22.log",
                  0x05: "/var/log/vuls/bserver:22.log",
                },
                levels: []logrus.Level{
                  0x05, 0x04, 0x03, 0x02, 0x01, 0x00,
                },
              },
            },
            0x00: []logrus.Hook{
              &lfshook.lfsHook{...},
            },
            0x05: []logrus.Hook{
              &lfshook.lfsHook{...},
            },
            0x04: []logrus.Hook{
              &lfshook.lfsHook{...},
            },
            0x03: []logrus.Hook{
              &lfshook.lfsHook{...},
            },
            0x02: []logrus.Hook{
              &lfshook.lfsHook{...},
            },
          },  
          Formatter: &prefixed.TextFormatter{
            ForceColors:      false,
            DisableColors:    false,
            DisableTimestamp: false,
            ShortTimestamp:   false,
            TimestampFormat:  "",
            DisableSorting:   false,
            MsgAnsiColor:     "\x1b[35m",
          },
          Level: 0x05,
          mu:    sync.Mutex{
            state: 0,
            sema:  0x00000000,
          },
        },
        Data: {
          "prefix": "bserver:22",
        },
        Time:    (unexported time.Time),
        Level:   0x00,
        Message: "",
      },
    },
  },
}
[Apr 13 10:45:49]  INFO [localhost] Installing...
[Apr 13 10:45:49]  INFO [bserver:22] Nothing to do
[Apr 13 10:45:49]  INFO [localhost] Success

However plugin is not installed. 

[root@bserver ~]# yum info yum-plugin-security
Loaded plugins: product-id, rhnplugin, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to registe\
r.
This system is not registered with RHN Classic or RHN Satellite.
You can use rhn_register to register.
RHN Satellite or RHN Classic support will be disabled.
Available Packages
Name        : yum-plugin-security
Arch        : noarch
Version     : 1.1.30
Release     : 30.el6
Size        : 41 k
Repo        : rhel-x86_64-server-6
Summary     : Yum plugin to enable security filters
URL         : http://yum.baseurl.org/download/yum-utils/
License     : GPLv2+
Description : This plugin adds the options --security, --cve, --bz and --advisory flags
            : to yum and the list-security and info-security commands.
            : The options make it possible to limit list/upgrade of packages to specific
            : security relevant ones. The commands give you the security information.

When this plugin is installed manually the scan completes fine, otherwise this error appears: 

[Apr 13 10:32:55] ERROR [localhost] Failed to scan. err: root@bserver.domain.com:22: Failed to yum updateinfo list available --security. status: 1, stdout: Loaded plugins: product-id, rhnplugin, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to register.
This system is not registered with RHN Classic or RHN Satellite.
You can use rhn_register to register.
RHN Satellite or RHN Classic support will be disabled.
Usage: yum [options] COMMAND

List of Commands:

check          Check for problems in the rpmdb
check-update   Check for available package updates
clean          Remove cached data
deplist        List a package's dependencies
distribution-synchronization Synchronize installed packages to the latest available versions
downgrade      downgrade a package
erase          Remove a package or packages from your system
groupinfo      Display details about a package group
groupinstall   Install the packages in a group on your system
grouplist      List available package groups
groupremove    Remove the packages in a group from your system
help           Display a helpful usage message
history        Display, or use, the transaction history
info           Display details about a package or group of packages
install        Install a package or packages on your system
list           List a package or groups of packages
load-transaction load a saved transaction from filename
makecache      Generate the metadata cache
provides       Find what package provides the given value
reinstall      reinstall a package
repolist       Display the configured software repositories
resolvedep     Determine which package provides the given dependency
search         Search package details for the given string
shell          Run an interactive yum shell
update         Update a package or packages on your system
upgrade        Update packages taking obsoletes into account
version        Display a version for the machine and/or available repos.

Command line error: no such option: --security
, stderr:

**Comment by kotakanbe** [comment]
Thanks for reporting.
I will check it tomorrow.

**Comment by kotakanbe** [comment]
I tried on RHEL6@AWS, But it works well. 
In the case of RHEL, yum-plugin-security installed by default. 
I think you should execute rhn_register to register to RHN.

https://access.redhat.com/solutions/8036

```
yum info yum-plugin-security
Loaded plugins: product-id, rhnplugin, subscription-manager
This system is not registered to Red Hat Subscription Management. You can use subscription-manager to registe\
r.
This system is not registered with RHN Classic or RHN Satellite.
You can use rhn_register to register.
```
