### ISSUE TITLE
pipefail problem when default shell is zsh on remote

### ISSUE THREAD

**Issue by beebird** [future-architect/vuls#25]
Another problem I encountered is:

[Apr 14 01:39:32] ERROR [localhost] Failed: xxx@xx.xx.xx.xx:22: Failed to yum install -y yum-plugin-security. status: 1, stdout: zsh:set:1: no such option: pipefail

Thanks!

**Comment by kotakanbe** [comment]
@beebird 
Thanks for reporting.
Vuls Doesn't support zsh on remote for now.

https://github.com/future-architect/vuls#misc
> Does Vuls accept ssh connections with fish-shell or old zsh as the login shell?
No, Vuls needs a user on the server for bash login. see also #8

**Comment by beebird** [comment]
I see, thanks!
