### ISSUE TITLE
EC2RoleCreds support?

### ISSUE THREAD

**Issue by chris-x86-64** [future-architect/vuls#250]
## Problem
* Due to this line ( https://github.com/future-architect/vuls/blob/549b315a65820864b2debcd66e86a9b5ad168be0/report/s3.go#L66 ) EC2RoleCreds is not supported at the moment.
  * Such a constraint forces users to put their AWS credentials within the file system.

## Ideas
* Use https://github.com/ushios/awsconfig ?

## P.S.
I was thinking of patching it myself but then I realized that I have absolutely no skill in Golang.

**Comment by kotakanbe** [comment]
Thank you :)
I will investigate.

**Comment by kotakanbe** [comment]
Merged https://github.com/future-architect/vuls/pull/370
