### ISSUE TITLE
`vuls prepare` doesn't work on Debian host due to apt-get confirmation prompt

### ISSUE THREAD

**Issue by Code0x58** [future-architect/vuls#251]
`vuls prepare` won't actually install aptitude on a Debain host as it will get tripped up by a confirmation prompt. 

This can be fixed by either adding `DEBIAN_FRONTEND=noninteractive` to the call environment, or simply adding a `-y` flag.

This is true for e40ef656d6285148d5ac55a02516312e265bac90 which is in the latest vuls/vuls Docker image.

**Comment by kotakanbe** [comment]
Thanks.
merged.

**Comment by Code0x58** [comment]
I realise that I went in completely the wrong direction as I didn't properly read the log output. Looking at it, I think the problem was that stdin wasn't available to read a response.

The `-y` is still needed to install packages though (unless all dependencies are met), so the path is still good.

I have make another issue to address what I actually encountered  #260
