### ISSUE TITLE
Display vendor support information when there is no vulnerability information in NVD

### ISSUE THREAD

**Issue by kotakanbe** [future-architect/vuls#257]
Currently when there is no vulnerability information in NVD, the details are indicated as "?".
Most of the distribution support sites have vulnerability information.
Import vulnerability information from distribution support site beforehand and display it if there is no  information in NVD.

**Comment by Djelibeybi** [comment]
You might want to review how Clair does this by leveraging the OVAL data provided by some vendors. For example, we provide OVAL information for all errata and CVEs for Oracle Linux at https://linux.oracle.com/security/oval/ either as a single combined file or in individual files by year.

OVAL data is machine readable (XML) so would be pretty simple to import.

**Comment by kotakanbe** [comment]
Done https://github.com/future-architect/vuls/pull/449
