### ISSUE TITLE
Can't init database in a path having blanks

### ISSUE THREAD

**Issue by vvoody** [future-architect/vuls#26]
```
$ mkdir '/tmp/path having blanks/'
$ cd '/tmp/path having blanks/'
$ pwd
/tmp/path having blanks
$ go-cve-dictionary server
[Apr 14 10:49:25] ERROR SQLite3 DB path must be a *Absolute* file path. dbpath: /tmp/path having blanks/cve.sqlite3
```

If I run `go-cve-dictionary server` in a path without blanks in the name, that's fine.

BTW, could you approve my request to join slack team? I applied many days ago :(

**Comment by kotakanbe** [comment]
@vvoody 
>BTW, could you approve my request to join slack team? I applied many days ago :(

Vuls Slack team is open team. 
You will receive the confirm mail after submitting your email-address.

Please try again.

**Comment by kotakanbe** [comment]
> Blanks in the path
I will change the error message. Thanks!

**Comment by kotakanbe** [comment]
Or you can send me pull request if you like! :-)

**Comment by vvoody** [comment]
Oh, I missed the email :( Now, you saw me :)

And for this issue, I found it's caused by package govalidator's regex patterns, `WinPath` and `UnixPath`.
The patterns don't allow blanks. Opened an issue for them, https://github.com/asaskevich/govalidator/issues/124.

```
WinPath        string = `^[a-zA-Z]:\\(?:[^\\/:*?"<>|\r\n]+\\)*[^\\/:*?"<>|\r\n]*$`
UnixPath       string = `^((?:\/[a-zA-Z0-9\.\:]+(?:_[a-zA-Z0-9\:\.]+)*(?:\-[\:a-zA-Z0-9\.]+)*)+\/?)$`
```

**Comment by kotakanbe** [comment]
Tnaks!
