### ISSUE TITLE
Continue scanning even when some hosts have tech issues?

### ISSUE THREAD

**Issue by chris-x86-64** [future-architect/vuls#264]
## Problem

Occasionally, some hosts fail to report the scan results despite that ssh connectivity checks and sudo checks pass. In such cases, Vuls stops abruptly, discarding the rest of the results.

I need an option to continue to produce the scan results even if it loses contact with part of the designated hosts during scan.

## Suggested procedures

* Add `-ignore-failures` option so that Vuls tries to finish the whole scanning process even when some hosts act up mid-scan.
* Define *Scan failed* JSON data to show in the TUI, send to Slack, etc.

## P.S.

While I was investigating this problem, I found another thing-- When a host is loaded with vulnerabilities, `-report-slack` may fail because Slack declines messages with too may attachments. I'll raise a separate issue regarding this.

**Comment by chris-x86-64** [comment]
Here is an example of the stderr output when a scan fails:

```
time="Nov 15 07:31:15" level=info msg="Fetching CVE details..." 
time="Nov 15 07:31:15" level=info msg=Done 
time="Nov 15 07:32:18" level=error msg="Failed to scan vulnerable packages" 
time="Nov 15 07:32:18" level=error msg="Failed to scan. err: vuls@{IP_ADDR}:22: Failed to parse LANGUAGE=en_US.UTF-8 yum --color=never  check-update. err: Unknown format: https://access.redhat.com/articles/1320623\r" 
time="Nov 15 07:32:18" level=error msg="Failed to scan. err: vuls@{IP_ADDR}:22: Failed to parse LANGUAGE=en_US.UTF-8 yum --color=never  check-update. err: Unknown format: https://access.redhat.com/articles/1320623\r"
```

**Comment by kotakanbe** [comment]
Merged
