### ISSUE TITLE
Latest version of labstack echo breaks installation

### ISSUE THREAD

**Issue by llazzaro** [future-architect/vuls#268]
# Environment
Debian 8
## Vuls

Hash : ef21376f0a3fcc97074487bf3e81fae1a4b06d0b

## Go
- Go version: 1.7.1

# Current Output

when I try to do a "make install" I got:

```
../go/src/github.com/kotakanbe/go-cve-dictionary/server/server.go:12:2: cannot find package "github.com/labstack/echo/engine/standard" in any of:
        /usr/local/go/src/github.com/labstack/echo/engine/standard (from $GOROOT)
        /home/leonardo/go/src/github.com/labstack/echo/engine/standard (from $GOPATH)
make: *** [install] Error 1
```

# Addition Details

engine directory is missing in the master branch of the echo project. latest version that seems to be compatible is v2.2.0

Can you also please fill in each of the remaining sections.

## Temporal fix

I clone the tag from the echo project on the go directory.

**Comment by kotakanbe** [comment]
Thanks for reporting.
I will check it.

**Comment by llazzaro** [comment]
I think this issue makes more sense on the go-cve-dictionary project.

**Comment by kotakanbe** [comment]
I tried it but did not reproduce it.
Is there anyone else who has this problem?

Vuls/go-cve-dictionary uses glide ( https://github.com/Masterminds/glide ) for package management to avoid this kind of problem. I think that this problem does not occur with make install. (It happens with go get)

Glide gets the dependent package under the vendor directory with git clone, then git checkout to the version specified in glide.lock.
Looking at the output you pasted, you can see that the Go compiler has not been looking for a vendor directory.

Please try the following.
```
1. remove  /home/leonardo/go/src/github.com/labstack/echo/
2. make install again
```
or 

```
go-cve-dictionary$ mv vendor /tmp
go-cve-dictionary$ glide install
go-cve-dictionary$ go install
```
