### ISSUE TITLE
docker fetchnvd failing

### ISSUE THREAD

**Issue by tobowers** [future-architect/vuls#274]
# Environment

OSX, docker-machine (not docker for mac), docker 1.11.2

## Vuls

go-cve-dictionary v0.1.0 99e8407

## OS
- Target Server: OSX

# Current Output

<details>
root@b04b00409a54:/vuls# $GOPATH/bin/go-cve-dictionary fetchnvd -debug -years 2002
 0 / 1 [--------------------------------------------------------------------------------------------------------------------]   0.00%[Nov 30 14:11:35]  INFO Fetching... https://static.nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2002.xml.gz
[Nov 30 14:11:39]  INFO Fetched 6721 CVEs
[Nov 30 14:11:39]  INFO Opening DB (sqlite3).
[Nov 30 14:11:39]  INFO Migrating DB
[Nov 30 14:11:39] ERROR Failed to migrate. err: disk I/O error
</details>

# Addition Details

## Expected Behavior

no disk error

## Actual Behavior

disk error.

## Steps to reproduce the behaviour

Drop into bash like this: `docker run --rm -it     -v $PWD:/vuls     -v $PWD/go-cve-dictionary-log:/var/log/vuls --entrypoint=/bin/bash    vuls/go-cve-dictionary -l`

I think it has something to do with root user vs the 1000/1000 user of boot2docker (permissions). I can touch the sqlite file just fine though.

Also... when I run the container without -v $PWD:/vuls everything works as expected.

**Comment by kotakanbe** [comment]
Thanks for reporting.
This issue will be good information for those with the same problem.

I usually use docker for mac, it works fine.
