### ISSUE TITLE
vuls prepare failed to centos7

### ISSUE THREAD

**Issue by shigechika** [future-architect/vuls#275]
# Environment

## Vuls

Hash : ____

To check the commit hash of HEAD

$ cd $GOPATH/src/github.com/future-architect/vuls 
$ git rev-parse --short HEAD 
8db147a

## OS
- Target Server: centos 7.2.1511
- Vuls Server: CentOS  6.8

## Go
- Go version: go1.7.1 linux/amd64

# Current Output

Please re-run the command using ```-debug``` and provide the output below.

$ vuls prepare -debug hoge 
INFO[0000] Start Preparing (config: /home/vuls/config.toml) 
INFO[0000] Validating Config...                         
[Dec  2 16:42:52]  INFO [localhost] Detecting OS... 
[Dec  2 16:42:52]  INFO [localhost] Detecting OS of servers... 
[Dec  2 16:42:52] DEBUG [localhost] SSHResult: servername: hoge, cmd: set -o pipefail; ls /etc/debian_version, exitstatus: 2, stdout: ls: /etc/debian_version にアクセスできません: そのようなファイルやディレクトリはありません
, stderr: , err: %!s(<nil>)
[Dec  2 16:42:52] DEBUG [localhost] Not Debian like Linux. SSHResult: servername: hoge, cmd: set -o pipefail; ls /etc/debian_version, exitstatus: 2, stdout: ls: /etc/debian_version にアクセスできません: そのようなファイルやディレクトリはありません
, stderr: , err: %!s(<nil>)
[Dec  2 16:42:53] DEBUG [localhost] SSHResult: servername: hoge, cmd: set -o pipefail; ls /etc/fedora-release, exitstatus: 2, stdout: ls: /etc/fedora-release にアクセスできません: そのようなファイルやディレクトリはありません
, stderr: , err: %!s(<nil>)
[Dec  2 16:42:53] DEBUG [localhost] SSHResult: servername: hoge, cmd: set -o pipefail; ls /etc/redhat-release, exitstatus: 0, stdout: /etc/redhat-release
, stderr: , err: %!s(<nil>)
[Dec  2 16:42:53] DEBUG [localhost] SSHResult: servername: hoge, cmd: set -o pipefail; cat /etc/redhat-release, exitstatus: 0, stdout: CentOS Linux release 7.2.1511 (Core) 
, stderr: , err: %!s(<nil>)
[Dec  2 16:42:53] DEBUG [localhost] Redhat like Linux. Host: hoge.nihon-u.ac.jp:22
[Dec  2 16:42:53]  INFO [localhost] (1/1) Detected: hoge: centos 7.2.1511
[Dec  2 16:42:53]  INFO [localhost] Detecting OS of containers... 
[Dec  2 16:42:53]  INFO [localhost] Checking sudo configuration... 
[Dec  2 16:42:54] DEBUG [hoge] SSHResult: servername: hoge, cmd: set -o pipefail; sudo -S yum --version, exitstatus: 0, stdout: 3.4.3
インストール: rpm-4.11.3-17.el7.x86_64 (日時: 2016-11-08 06:42)
  構築      : CentOS BuildSystem <http://bugs.centos.org>  (日時: 2015-11-20 11:15)
  コミット  : Florian Festi <ffesti@redhat.com> (日時: 2015-09-11)

インストール: yum-3.4.3-132.el7.centos.0.1.noarch (日時: 2016-11-08 06:42)
  構築      : CentOS BuildSystem <http://bugs.centos.org>  (日時: 2015-12-03 15:33)
  コミット  : Johnny Hughes <johnny@centos.org> (日時: 2015-12-03)

インストール: yum-plugin-fastestmirror-1.1.31-34.el7.noarch (日時: 2016-11-08 06:42)
  構築      : CentOS BuildSystem <http://bugs.centos.org>  (日時: 2015-11-20 15:34)
  コミット  : Valentina Mukhamedzhanova <vmukhame@redhat.com> (日時: 2015-10-12)
, stderr: , err: %!s(<nil>)
[Dec  2 16:42:54]  INFO [hoge] sudo ... OK
[Dec  2 16:42:54] DEBUG [hoge] SSHResult: servername: hoge, cmd: set -o pipefail; rpm -q yum-plugin-changelog, exitstatus: 1, stdout: パッケージ yum-plugin-changelog はインストールされていません。
, stderr: , err: %!s(<nil>)
[Dec  2 16:42:54]  INFO [localhost] The following servers need dependencies installed
[Dec  2 16:42:54]  INFO [localhost]   - yum-plugin-changelog on hoge
[Dec  2 16:42:54]  INFO [localhost] Is this ok to install dependencies on the servers? [y/N]
STOP!

# Addition Details

hoge$ rpm -q yum
yum-3.4.3-132.el7.centos.0.1.noarch

## Expected Behavior

use yum with option -y

**Comment by kotakanbe** [comment]
```
[Dec 2 16:42:54] INFO [localhost] Is this ok to install dependencies on the servers? [y/N]
STOP!
```

Please input y and then press Enter key.
Or specify -assume-yes option.
https://github.com/future-architect/vuls#usage-prepare

**Comment by shigechika** [comment]
Thank you for rely. Resolved.

[vuls@vuls ~]$ vuls prepare **-assume-yes** target1 target2
INFO[0000] Start Preparing (config: /home/vuls/config.toml)
INFO[0000] Validating Config...
[Dec  5 11:21:29]  INFO [localhost] Detecting OS...
[Dec  5 11:21:29]  INFO [localhost] Detecting OS of servers...
[Dec  5 11:21:29]  INFO [localhost] (1/2) Detected: target1: centos 7.2.1511
[Dec  5 11:21:30]  INFO [localhost] (2/2) Detected: target2: centos 7.2.1511
[Dec  5 11:21:30]  INFO [localhost] Detecting OS of containers...
[Dec  5 11:21:30]  INFO [localhost] Checking sudo configuration...
[Dec  5 11:21:30]  INFO [target1] sudo ... OK
[Dec  5 11:21:30]  INFO [target2] sudo ... OK
[Dec  5 11:21:31]  INFO [localhost] The following servers need dependencies installed
[Dec  5 11:21:31]  INFO [localhost]   - yum-plugin-changelog on target1
[Dec  5 11:21:31]  INFO [localhost]   - yum-plugin-changelog on target2
[Dec  5 11:21:36]  INFO [target2] Installed: yum-plugin-changelog
[Dec  5 11:21:38]  INFO [target1] Installed: yum-plugin-changelog
[Dec  5 11:21:38]  INFO [localhost] All dependencies were installed correctly
