### ISSUE TITLE
PackInfo not found error when vuls scan.

### ISSUE THREAD

**Issue by hogehogehugahuga** [future-architect/vuls#281]
# Environment

RHEL6.5 provided by **cloud provider.**

## Vuls

Unknown

To check the commit hash of HEAD

## OS
- Target Server: Self scan ; The repository provided by cloud provider.
- Vuls Server: RHEL6.5 

# Addition Details

I got the following information

- When I scanned, we got an error like the following.
  - Failed to scan. err: xxx@xxx.xxx.xxx: PackInfo not found. packInfo: <pkg name>
- Temporarily avoided with the following setting.
  - remove available option from scan/redhat.go Line597, and compile.

I do not have the following information. Give me some information.

- Where is the "cloud provider"?
  - It could be caused by a repository of cloud providers.
- Seems to have occurred in several people.

**Comment by hogehogehugahuga** [comment]
Workaround seems to be successful.

```
[vuls:~]$ vi go/src/github.com/future-architect/vuls/scan/redhat.go
# 597行名からabailableを削除
- cmd = "yum --color=never updateinfo list available --security"
+ cmd = "yum --color=never updateinfo list --security"
[vuls:~]$ cd go/src/github.com/future-architect/vuls
[vuls:vuls]$ rm -rf vendor
[vuls:vuls]$ make install
[vuls:vuls]$ cd 
[vuls:~]$ vuls scan ....
```

RHEL installed with ISO does not cause problems.
It seems to be a 'Cloud provider custom repository' problem.

I think "yum updateinof list **available** --security" and "rpm -qa" have a mismatch.
I ask the thi probrem reporter to report both results.

**Comment by hogrcyan** [comment]
After modified the program and re-executing the vuls scan command, it succeeded.
I appreciate your prompt response.

Cloud service provider： IDC Frontier Inc.
Template Name： Red Hat Enterprise Linux 6.5 64-bit

[rpm-qa_PaaS_RHEL65.txt](https://github.com/future-architect/vuls/files/656332/rpm-qa_PaaS_RHEL65.txt)
[yum-updateinfoListAvailable--security_PaaS_RHEL65.txt](https://github.com/future-architect/vuls/files/656334/yum-updateinfoListAvailable--security_PaaS_RHEL65.txt)
[yum-updateinfoList--security_PaaS_RHEL65.txt](https://github.com/future-architect/vuls/files/656333/yum-updateinfoList--security_PaaS_RHEL65.txt)

**Comment by hogrcyan** [comment]
I created a new VirtualMachine using the same OS template on IDCF cloud.
There is no difference in the result of the ”yum updateinfo list available --security” and "updateinfo list --security" before and after executing the following command.
(executing the command)
   yum clean metadata
   yum clear dbcache
   yum clean all
   rpm --rebuilddb

I modifiel redhat.go and excecuted vuls scan, The same error occured again.
```
$ vi go/src/github.com/future-architect/vuls/scan/redhat.go
# 597行目を元に戻す
- cmd = "yum --color=never updateinfo list --security"
+ cmd = "yum --color=never updateinfo list available --security"
```
[Dec 16 14:54:56] ERROR [xxx-xxx-xxx-xxx] Failed to scan vulnerable packages
[Dec 16 14:54:56] ERROR [localhost] Failed to scan. err: root@xxxxx: PackInfo not found. packInfo: "389-ds-base"

[rpm-qa-NewVM.txt](https://github.com/future-architect/vuls/files/656523/rpm-qa-NewVM.txt)
[yum-updateinfoListAvailable--security_NewVM_after.txt](https://github.com/future-architect/vuls/files/656526/yum-updateinfoListAvailable--security_NewVM_after.txt)
[yum-updateinfoListAvailable--security_NewVM_before.txt](https://github.com/future-architect/vuls/files/656524/yum-updateinfoListAvailable--security_NewVM_before.txt)
[yum-updateinfoList--security_NewVM_after.txt](https://github.com/future-architect/vuls/files/656527/yum-updateinfoList--security_NewVM_after.txt)
[yum-updateinfoList--security_NewVM_before.txt](https://github.com/future-architect/vuls/files/656525/yum-updateinfoList--security_NewVM_before.txt)

**Comment by kotakanbe** [comment]
https://access.redhat.com/solutions/10021

**Comment by kotakanbe** [comment]
Fixed. Please try it out :)
