### ISSUE TITLE
With the "prepare" command, we need to check that the plugin is enabled.

### ISSUE THREAD

**Issue by hogehogehugahuga** [future-architect/vuls#284]
The "Prepare" command checks the existence of plugins. However, it does not seem to check whether it actually works.
For example, the following situation.

- on RHEL
- yum-plugin-security is installed, but it disabled.
  - /etc/yum/pluginconf.d/security.conf : [main] enabled=0
- prepare command passed, but scan comannd return "yum --security option not found" errors.

It is a rare case, but I want to be able to check it. (The same applies to other OS.)

- Execute minimum command for pre-check on prepare
  - For example, `# yum --security check-update` (or updateinfo?)

/*
 レアケースと思いますが、pluginは入っているが設定で無効になっている場合、という状況があるようです。
 この状況だとplugin-securityが入っていない旨のエラーが出るようです。これを検知したいという趣旨です。
 scan時にに流すコマンドが使えるのか、のチェックを入れればいいのかな、と思っています。
*/

**Comment by kotakanbe** [comment]
Merged.

Check whether all dependencies are available in configtest subcommand.
https://github.com/future-architect/vuls/pull/375
