### ISSUE TITLE
Scan all containers except

### ISSUE THREAD

**Issue by rjes** [future-architect/vuls#285]
Hi!
Is it possible to scan all running docker containers except for the containers in the configuration file?

**Comment by kotakanbe** [comment]
Hi!

In the current implementation, only two types are supported: the mode of scanning the running container and the mode of scanning the container specifying the container.

see https://github.com/future-architect/vuls#usage-scan-docker-containers

**Comment by kotakanbe** [comment]
```
[servers]

[servers.172-31-4-82]
host         = "172.31.4.82"
user        = "ec2-user"
keyPath     = "/home/username/.ssh/id_rsa"
[servers.172-31-4-82.container]
type = "lxd" # or "docker"
containers = ["${running}"]
except = ["ubuntu1", "fa30c26ed699"]
```

**Comment by kotakanbe** [comment]
@rjes Merged!
