### ISSUE TITLE
Pointless sudo

### ISSUE THREAD

**Issue by yoshi314** [future-architect/vuls#29]
On debian systems vuls does sudo test -f /usr/bin/aptitude , which is rather unnecessary.

**Comment by kotakanbe** [comment]
Minimal docker container doesn't have aptitude.
So I think it's better to check whether aptitude is installed.

**Comment by yoshi314** [comment]
Yes, but that file is not in a restricted location. The command works just as well without sudo for any user.

I am doing a restricted setup enabling bare minimum via sudoers for restricted account for vuls, and this particular case makes no sense.

**Comment by kotakanbe** [comment]
I understand.
Please send a pull request If you like :-)

**Comment by yoshi314** [comment]
Will do, once i figure out how to build vuls in-place. Go is a bit unfamillar territory for me atm.

**Comment by kotakanbe** [comment]
It's OK. I am waiting your pull request !

**Comment by kotakanbe** [comment]
Fixed
