### ISSUE TITLE
cannot find package "github.com/future-architect/vuls/commands"

### ISSUE THREAD

**Issue by hktalent** [future-architect/vuls#290]
mac os 10.12.2
cd safe/future-architect/vuls
make install
.....

go install -ldflags "-X 'main.version=v0.1.7' -X 'main.revision=7b2e2cb'"
main.go:27:2: cannot find package "github.com/future-architect/vuls/commands" in any of:
	/usr/local/Cellar/go/1.7.4_1/libexec/src/github.com/future-architect/vuls/commands (from $GOROOT)
	/usr/local/opt/go/src/github.com/future-architect/vuls/commands (from $GOPATH)
/usr/local/opt/go/src/github.com/mattn/go-sqlite3/sqlite3.go:118:2: cannot find package "golang.org/x/net/context" in any of:
	/usr/local/Cellar/go/1.7.4_1/libexec/src/golang.org/x/net/context (from $GOROOT)
	/usr/local/opt/go/src/golang.org/x/net/context (from $GOPATH)
make: *** [install] Error 1

so
http://github.com/future-architect/vuls/commands

is 404

**Comment by kotakanbe** [comment]
I can not reproduce the issue.

I think that the directory structure on your pc is wrong.
```
$ mkdir -p $GOPATH/src/github.com/future-architect
$ cd $GOPATH/src/github.com/future-architect
$ git clone https://github.com/future-architect/vuls.git
$ cd vuls
$ make install
```

**Comment by hktalent** [comment]
@kotakanbe thanks

[INFO]	Replacing existing vendor dependencies
go install -ldflags "-X 'main.version=v0.2.0' -X 'main.revision=1e8f24d'"
# github.com/future-architect/vuls/vendor/github.com/mattn/go-sqlite3
In file included from vendor/github.com/mattn/go-sqlite3/sqlite3-binding.c:2:
vendor/github.com/mattn/go-sqlite3/code/sqlite3-binding.c:16475:17: warning: 'OSAtomicCompareAndSwapPtrBarrier' is deprecated: first deprecated in macOS 10.12 - Use atomic_compare_exchange_strong() from <stdatomic.h> instead [-Wdeprecated-declarations]
/usr/include/libkern/OSAtomicDeprecated.h:547:6: note: 'OSAtomicCompareAndSwapPtrBarrier' has been explicitly marked deprecated here
