### ISSUE TITLE
vuls report -to-email only one E-Mail

### ISSUE THREAD

**Issue by Klar** [future-architect/vuls#295]
When I use the "vuls report" command with "-to-email", I receive for every host a new Mail.

Is it possible to configure "vuls report" to receive only one E-Mail with all the host information, same like "vuls report -format-one-line-text" ? or with the output of "-format-full-text"

thanks for your help.

**Comment by kotakanbe** [comment]
Nice idea.
I will implement it in the near future.

**Comment by kotakanbe** [comment]
#331

**Comment by kotakanbe** [comment]
Merged!

**Comment by Klar** [comment]
thank you! :+1:
