### ISSUE TITLE
Changelog parsing fails when package maintainers aren't consistent regarding versions

### ISSUE THREAD

**Issue by jsulinski** [future-architect/vuls#327]
This seems to only be a problem in the Debian community, as I haven't seen it occur in Ubuntu yet, but a number of package changelogs only include the version number pre "+".  Example version number: 4.2.2-4+b1

**Examples of packages impacted**

debian 8.6/8.7:

liblcms2-2
libxpm4
liblcms2-dev

debian 8.5:

libpam0g
libpam-modules
tar
sed
libpam-modules-bin
bash

**Comment by kotakanbe** [comment]
Merged
