### ISSUE TITLE
vuls scan including localhost when called from cron can't create results files.

### ISSUE THREAD

**Issue by shigechika** [future-architect/vuls#333]
# Environment
CentOS 6.8

## Vuls
vuls v0.2.0 1730caf

## Go
go version go1.7.1 linux/amd64

# Current Output
    time="2017-02-07T17:39:01+09:00" level=info msg="Start scanning" 
    time="2017-02-07T17:39:01+09:00" level=info msg="config: /home/vuls/config-lo.toml" 
    time="2017-02-07T17:39:01+09:00" level=debug  msg="map[string]config.\x1b[32mServerInfo\x1b[0m{}" 
    time="Feb  7 17:39:01" level=info msg="Validating Config..." 
    time="Feb  7 17:39:01" level=info msg="Detecting Server/Contianer OS... " 
    time="Feb  7 17:39:01" level=info msg="Detecting OS of servers... " 
    time="Feb  7 17:39:01" level=debug msg="execResult: servername: \n  cmd: set -o pipefail; ls /etc/debian_version\n  exitstatus: 2\n  stdout: \n  stderr: ls: cannot access /etc/debian_version: No such file or directory\n\n  err: exit status 2" 
    time="Feb  7 17:39:01" level=debug msg="execResult: servername: \n  cmd: set -o pipefail; ls /etc/fedora-release\n  exitstatus: 2\n  stdout: \n  stderr: ls: cannot access /etc/fedora-release: No such file or directory\n\n  err: exit status 2" 
    time="Feb  7 17:39:01" level=debug msg="execResult: servername: \n  cmd: set -o pipefail; ls /etc/redhat-release\n  exitstatus: 0\n  stdout: /etc/redhat-release\n\n  stderr: \n  err: %!s(<nil>)" 
    time="Feb  7 17:39:01" level=debug msg="execResult: servername: \n  cmd: set -o pipefail; cat /etc/redhat-release\n  exitstatus: 0\n  stdout: CentOS release 6.8 (Final)\n\n  stderr: \n  err: %!s(<nil>)" 
    time="Feb  7 17:39:01" level=debug msg="Redhat like Linux. Host: localhost:local" 
    time="Feb  7 17:39:01" level=info msg="(1/1) Detected: lo: centos 6.8" 
    time="Feb  7 17:39:01" level=info msg="Detecting OS of containers... " 
    time="Feb  7 17:39:01" level=info msg="Checking sudo configuration... " 
    time="Feb  7 17:39:01" level=debug msg="execResult: servername: \n  cmd: set -o pipefail; sudo -S yum --version\n  exitstatus: 1\n  stdout: \n  stderr: sudo: sorry, you must have a tty to run sudo\n\n  err: exit status 1" 
    time="Feb  7 17:39:01" level=error msg="sudo error on execResult: servername: \n  cmd: set -o pipefail; sudo -S yum --version\n  exitstatus: 1\n  stdout: \n  stderr: sudo: sorry, you must have a tty to run sudo\n\n  err: exit status 1" 
    time="Feb  7 17:39:01" level=error msg="Failed to sudo with nopassword via SSH. Define NOPASSWD in /etc/sudoers on target servers"

# Addition Details
- /home/vuls/config.toml
    [servers.lo]
    host = "localhost"
    port = "local"
    :(snip)

- /usr/local/etc/vuls-daily.sh
    #!/bin/bash
    SHELL=/bin/bash
    HOME=/home/vuls
    . /etc/profile.d/goenv.sh
    cd $HOME
    go-cve-dictionary fetchnvd -last2y -dbpath=/home/vuls/cve.sqlite3
    go-cve-dictionary fetchjvn -last2y -dbpath=/home/vuls/cve.sqlite3
    vuls scan -results-dir=/home/vuls/results
    :(snip)

- crontab
    30 08 * * * vuls /usr/local/etc/vuls-daily.sh
    :(snip)

**Comment by hogehogehugahuga** [comment]
I succeeded in may environment on root@CentOS68 and "vuls v0.2.0 a6f0c55".

LocalScanmode need a PATH to the following Linux commands,
- cat, curl, ls, rpm, sudo, uname, wget

Please try specifying the same PATH as in interactive execution.
- set PATH to when interactive success vuls execution.

====
root's crontab set
MM HH * * * cat /root/vuls/scan.sh 
----
#!/bin/bash
# this is "cat scan.sh "
SHELL=/bin/bash
PLUGINDIR=/root/vuls
HOME=/root
PATH=/root/vuls/bin
$PLUGINDIR/vuls scan -config=$PLUGINDIR/config.toml -results-dir=$PLUGINDIR/results -log-dir=/var/log/vuls -debug
----
# ls /root/vuls/bin
cat  curl  ls  rpm  sudo  uname  wget
====

**Comment by knqyf263** [comment]
@shigechika 
Did you add the following line to `/etc/sudoers` ?
https://github.com/future-architect/vuls#-ssh-external-option

```
Defaults:vuls !requiretty
```

This error may be related to the above setting.
>stderr: sudo: sorry, you must have a tty to run sudo

**Comment by shigechika** [comment]
@knqyf263 BINGO!!!
I added "Defaults:vuls !requiretty" in /etc/sudoers.
Vuls could created results files including localhost.
Thank you very much.

**Comment by knqyf263** [comment]
You're welcome!
I'll update README for local scan mode.
