### ISSUE TITLE
mac os 10.12.3 make install error

### ISSUE THREAD

**Issue by hktalent** [future-architect/vuls#334]
mac os 10.12.3

origin	https://github.com/future-architect/vuls.git (fetch)
origin	https://github.com/future-architect/vuls.git (push)

run：
vi ~/.bash_profile

export GOROOT=/usr/local/opt/go
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
source ~/.bash_profile

$ sudo mkdir /var/log/vuls
$ sudo chown ec2-user /var/log/vuls
$ sudo chmod 700 /var/log/vuls
$
$ mkdir -p $GOPATH/src/github.com/kotakanbe
$ cd $GOPATH/src/github.com/kotakanbe
$ git clone https://github.com/kotakanbe/go-cve-dictionary.git
$ cd go-cve-dictionary
$ make install

$ for i in {2002..2016}; do go-cve-dictionary fetchnvd -years $i; done
... snip ...
$ ls -alh cve.sqlite3

$ mkdir -p $GOPATH/src/github.com/future-architect
$ cd $GOPATH/src/github.com/future-architect
$ git clone https://github.com/future-architect/vuls.git
$ cd vuls
$ make install

[INFO]	Replacing existing vendor dependencies
go install -ldflags "-X 'main.version=v0.2.0' -X 'main.revision=1e8f24d'"
# github.com/future-architect/vuls/vendor/github.com/mattn/go-sqlite3
In file included from vendor/github.com/mattn/go-sqlite3/sqlite3-binding.c:2:
vendor/github.com/mattn/go-sqlite3/code/sqlite3-binding.c:16475:17: warning: 'OSAtomicCompareAndSwapPtrBarrier' is deprecated: first deprecated in macOS 10.12 - Use atomic_compare_exchange_strong() from <stdatomic.h> instead [-Wdeprecated-declarations]
/usr/include/libkern/OSAtomicDeprecated.h:547:6: note: 'OSAtomicCompareAndSwapPtrBarrier' has been explicitly marked deprecated here

**Comment by hktalent** [comment]
#290 
thanks

[INFO]	Replacing existing vendor dependencies
go install -ldflags "-X 'main.version=v0.2.0' -X 'main.revision=1e8f24d'"
# github.com/future-architect/vuls/vendor/github.com/mattn/go-sqlite3
In file included from vendor/github.com/mattn/go-sqlite3/sqlite3-binding.c:2:
vendor/github.com/mattn/go-sqlite3/code/sqlite3-binding.c:16475:17: warning: 'OSAtomicCompareAndSwapPtrBarrier' is deprecated: first deprecated in macOS 10.12 - Use atomic_compare_exchange_strong() from <stdatomic.h> instead [-Wdeprecated-declarations]
/usr/include/libkern/OSAtomicDeprecated.h:547:6: note: 'OSAtomicCompareAndSwapPtrBarrier' has been explicitly marked deprecated here

**Comment by kotakanbe** [comment]
You can ignore it.
