### ISSUE TITLE
Unknown OS Type

### ISSUE THREAD

**Issue by hktalent** [future-architect/vuls#335]
# Environment
mac os 10.12.3
## Vuls

$ pwd
/usr/local/opt/go/bin
QQ1160:bin xiatian$ ./vuls scan
INFO[0000] Start scanning                               
INFO[0000] config: /usr/local/opt/go/bin/config.toml    
[Feb 13 15:31:46]  INFO [localhost] Validating Config...
[Feb 13 15:31:46]  INFO [localhost] Detecting Server/Container OS... 
[Feb 13 15:31:46]  INFO [localhost] Detecting OS of servers... 
[Feb 13 15:31:47] ERROR [localhost] (1/1) Failed: 192-168-10-115, err: [Unknown OS Type]
[Feb 13 15:31:47] ERROR [localhost] Failed to init servers: No scannable servers

$ git pull
remote: Counting objects: 8, done.
remote: Total 8 (delta 4), reused 4 (delta 4), pack-reused 3
Unpacking objects: 100% (8/8), done.
From https://github.com/future-architect/vuls
   1e8f24d..0066048  master     -> origin/master
Updating 1e8f24d..0066048
Fast-forward
 scan/debian.go | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
To check the commit hash of HEAD
$ vuls -v
$ ./vuls -v
vuls v0.2.0 1e8f24d

or
$ cd $GOPATH/src/github.com/future-architect/vuls 
$ git rev-parse --short HEAD 
0066048
## OS
- Target Server: Write here
- Vuls Server: Write here
$ uname -a
Darwin QQ1160.local 16.4.0 Darwin Kernel Version 16.4.0: Thu Dec 22 22:53:21 PST 2016; root:xnu-3789.41.3~3/RELEASE_X86_64 x86_64

## Go
- Go version: here
$ go version
warning: GOPATH set to GOROOT (/usr/local/opt/go) has no effect
go version go1.7.5 darwin/amd64
# Current Output

Please re-run the command using ```-debug``` and provide the output below.

# Addition Details

Can you also please fill in each of the remaining sections.

## Steps to reproduce the behaviour
$ cat config.toml 
[servers]

[servers.192-168-10-115]
host         = "192.168.10.115"
port        = "22"
user        = "root"
keyPath     = "/Users/xiatian/.ssh/id_rsa"
$ pwd
/usr/local/opt/go/bin
QQ1160:bin xiatian$ ./vuls scan
INFO[0000] Start scanning                               
INFO[0000] config: /usr/local/opt/go/bin/config.toml    
[Feb 13 15:31:46]  INFO [localhost] Validating Config...
[Feb 13 15:31:46]  INFO [localhost] Detecting Server/Container OS... 
[Feb 13 15:31:46]  INFO [localhost] Detecting OS of servers... 
[Feb 13 15:31:47] ERROR [localhost] (1/1) Failed: 192-168-10-115, err: [Unknown OS Type]
[Feb 13 15:31:47] ERROR [localhost] Failed to init servers: No scannable servers

**Comment by kotakanbe** [comment]
Please let me know about scan target server.

**Comment by hktalent** [comment]
@kotakanbe 
thanks is ok
被扫描机器上运行
ssh-keygen -t rsa;cat ~/.ssh/id_rsa.pub >> ~/.ssh/authorized_keys;chmod 600 ~/.ssh/authorized_keys
cat   ~/.ssh/id_rsa
拷贝到本机
cd /Users/xiatian/.ssh
vi 115.key
修改
QQ1160:bin xiatian$ cat config.toml 
[servers]

[servers.192-168-10-115]
host         = "192.168.10.115"
port        = "22"
user        = "root"
keyPath     = "/Users/xiatian/.ssh/115.key"
