### ISSUE TITLE
Command line error: no such option: --security

### ISSUE THREAD

**Issue by hktalent** [future-architect/vuls#336]
$ ./vuls scan 

[Feb 13 16:11:36]  INFO [localhost] Scanning vulnerable OS packages...
[Feb 13 16:11:40] ERROR [192-168-10-115] Failed to scan vulnerable packages
[Feb 13 16:11:40] ERROR [localhost] Failed to scan. err: root@192.168.10.115:22: Failed to SSH: execResult: servername: 192-168-10-115
  cmd: set -o pipefail; yum --color=never --security updateinfo list updates
  exitstatus: 1
  stdout: Loaded plugins: refresh-packagekit
Usage: yum [options] COMMAND

List of Commands:

check          Check for problems in the rpmdb
check-update   Check for available package updates
clean          Remove cached data
deplist        List a package's dependencies
distribution-synchronization Synchronize installed packages to the latest available versions
downgrade      downgrade a package
erase          Remove a package or packages from your system
groupinfo      Display details about a package group
groupinstall   Install the packages in a group on your system
grouplist      List available package groups
groupremove    Remove the packages in a group from your system
help           Display a helpful usage message
history        Display, or use, the transaction history
info           Display details about a package or group of packages
install        Install a package or packages on your system
list           List a package or groups of packages
load-transaction load a saved transaction from filename
makecache      Generate the metadata cache
provides       Find what package provides the given value
reinstall      reinstall a package
repolist       Display the configured software repositories
resolvedep     Determine which package provides the given dependency
search         Search package details for the given string
shell          Run an interactive yum shell
update         Update a package or packages on your system
upgrade        Update packages taking obsoletes into account
version        Display a version for the machine and/or available repos.

Command line error: no such option: --security

  stderr: 
  err: %!s(<nil>)

in
192-168-10-115

[root@appserver .ssh]# yum --color=never --security updateinfo list updates
Loaded plugins: refresh-packagekit
Usage: yum [options] COMMAND

List of Commands:

check          Check for problems in the rpmdb
check-update   Check for available package updates
clean          Remove cached data
deplist        List a package's dependencies
distribution-synchronization Synchronize installed packages to the latest available versions
downgrade      downgrade a package
erase          Remove a package or packages from your system
groupinfo      Display details about a package group
groupinstall   Install the packages in a group on your system
grouplist      List available package groups
groupremove    Remove the packages in a group from your system
help           Display a helpful usage message
history        Display, or use, the transaction history
info           Display details about a package or group of packages
install        Install a package or packages on your system
list           List a package or groups of packages
load-transaction load a saved transaction from filename
makecache      Generate the metadata cache
provides       Find what package provides the given value
reinstall      reinstall a package
repolist       Display the configured software repositories
resolvedep     Determine which package provides the given dependency
search         Search package details for the given string
shell          Run an interactive yum shell
update         Update a package or packages on your system
upgrade        Update packages taking obsoletes into account
version        Display a version for the machine and/or available repos.

Command line error: no such option: --security

**Comment by hktalent** [comment]
scanner server
 uname -a
Linux appserver 2.6.32-279.el6.x86_64 #1 SMP Thu Jun 21 15:00:18 EDT 2012 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kotakanbe** [comment]
try `vuls prepare` to install yum-plugin-security
see https://github.com/future-architect/vuls#usage-prepare

**Comment by kotakanbe** [comment]
Which distribution do you use?

**Comment by kotakanbe** [comment]
If the same error occurs even after prepreping, execute `yum install yum-plugin-security` on the target server.

**Comment by hktalent** [comment]
@kotakanbe  is ok，thank you
