### ISSUE TITLE
vuls is running on FreeBSD 10.3 and go 1.6.1

### ISSUE THREAD

**Issue by sheo0147** [future-architect/vuls#34]
I installed go and vuls to FreeBSD 10.3/go-1.6.1 and it running now.

Does vuls supports FreeBSD vulnerability check?

- pkg audit -F tells installed packages' vulnerability informations.

Thank you to publish good tool.

**Comment by justyntemme** [comment]
Would it be better to copy linux.go and re-format it for BSD and include the package check? Or just appended it to linux.go if def style? looking to fix this for fun today, just not sure the best way to go about it.

**Comment by sheo0147** [comment]
I think vuls can support many package distribution systems like yum/RPM, apt, and so on.

I want to add some pkg platforms like followings.
FreeBSD: pkg
OS-X: HomeBrew
and 
pkgsrc (mainly used by NetBSD but can use Solaris/Linux/BSD/AIX...)

**Comment by justyntemme** [comment]
So maybe a new file specifically providing functions for package managers? I would start hacking away but i wan't to make sure my goals are aligned with yours.

**Comment by sheo0147** [comment]
For example,.
HomeBrew can get installed package version using  ' brew ls --versions '
FreeBSD/pkg system can get installed package version using ' pkg version ' or ' pkg info '
and shows package audit information using 'pkg audit -F' .

**Comment by kotakanbe** [comment]
@justyntemme 
Sorry for late reply. I am repo owner.

Current Structure is 
- linux.go
    - redhat.go
    - debian.go

linux is base structure. I was considered to define a common function of debian / redhat to linux. But now, common function is none :)

So I am going to change the name of linux.go to something good name.
Please add freebsd.go under linux.go for now.

- linux.go
    - redhat.go
    - debian.go
    - freebsd.go

I don't know so much about FreeBSD and I don't have FreeBSD machine now.
So I can not decide the best structure now.
The structure may be changed after you hacking :)

**Comment by justyntemme** [comment]
I have a little bit of experience in BSD. I spinning up a VM and will get to work. plan to go as described all in linux.go if things work as planned. Don't see any reason why it wouldn'tB.

**Comment by kotakanbe** [comment]
@justyntemme are working.
https://github.com/justyntemme/vuls

**Comment by sheo0147** [comment]
Sorry for late reply.
I think linkx.go will rename to target_common.go, so looks clean of hierarchical structure.

sorry for my poor english.

**Comment by justyntemme** [comment]
I have renamed linux.go to target_common.go in my fork. Progress is slow but feature is on it's way.

**Comment by kotakanbe** [comment]
https://github.com/future-architect/vuls/pull/98

**Comment by kotakanbe** [comment]
FreeBSD support was implemented.
The remaining of FreeBSD is Jail(container) Support.
Jail support is working on https://github.com/future-architect/vuls/pull/102
