### ISSUE TITLE
Can Vuls show details about updateable packages

### ISSUE THREAD

**Issue by musicalpike** [future-architect/vuls#341]
In my recent scanning result, there are no vulnerabilities popping up but updateable packages as the following:

Total: 0 (High:0 Medium:0 Low:0 ?:0)	4 updatable packages

No CVE-IDs are found in updatable packages.
4 updatable packages

I would like to know if there is a report option to show the details of these updateable packages. Cheers

**Comment by kotakanbe** [comment]
Please thumb up if you want this function.

**Comment by kotakanbe** [comment]
I think that it would be even better if vuls can display changelogs only for parts related to version upgrade.
