### ISSUE TITLE
yum --color=never

### ISSUE THREAD

**Issue by trocster** [future-architect/vuls#36]
Feature request:

In scanning an estate of servers run by different sysadmins, colorized output to yum has resulted in failed parsing. 

E.g.

[Apr 20 11:25:35] ERROR [localhost] Failed to scan. err: root@serverb.example.com:22: Failed to parse yum check-update. err: Unknown format: at.x86_64                                        3.1.10-48.el6   repo-name-server-6-base

Perhaps some input validation can detect control characters produced by yum and an appropiate error produced for the user ? Or a mention in the documentation. Perhaps this post is enough. 

Many thanks for the fixes so far.

**Comment by kotakanbe** [comment]
@trocster 
Thanks for reporting.
The bug was fixed and merged to master.
Please test on your environment.

Many thanks.

```
$ go get -u github.com/kotakanbe/go-cve-dictionary
$ go get -u github.com/future-architect/vuls
```
