### ISSUE TITLE
SSH ciphers

### ISSUE THREAD

**Issue by theonlydoo** [future-architect/vuls#37]
Got this error on every server that I have : 
```
WARN[0020] Failed to ssh root@xxx err: ssh: handshake failed: ssh: no common algorithm for client to server cipher; client offered: [aes128-ctr aes192-ctr aes256-ctr aes128-gcm@openssh.com arcfour256 arcfour128], server offered: [aes256-cbc], Retrying in 10.034154425s...
```

And i have to disable my cipher to use vuln.

**Comment by kotakanbe** [comment]
Thanks for reporting.
I need some time...

**Comment by theonlydoo** [comment]
No problem I tought so :-) glad to report !

**Comment by kotakanbe** [comment]
Hi, @theonlydoo 
Finally, Vuls supports external ssh command.
https://github.com/future-architect/vuls/pull/101

For details, see https://github.com/future-architect/vuls#-ssh-external-option

Please try it out!
