### ISSUE TITLE
error on install - Ubuntu 16.04

### ISSUE THREAD

**Issue by jammasterj89** [future-architect/vuls#376]
Hi, I'm trying to install vuls on Ubuntu 16.04, but I'm erroring at "Step4. Deploy go-cve-dictionary", I try to "make install" and it errors with the following:

main.go:4:2: cannot find package "context" in any of:
        /home/vagrant/go/src/github.com/kotakanbe/go-cve-dictionary/vendor/context (vendor tree)
        /usr/local/go/src/context (from $GOROOT)
        /home/vagrant/go/src/context (from $GOPATH)
Makefile:39: recipe for target 'install' failed
make: *** [install] Error 1

**Comment by kotakanbe** [comment]
@jammasterj89 

Perhaps Go version is old, please install it with 1.7 or 1.8.
https://golang.org/dl/

**Comment by jammasterj89** [comment]
thank you @kotakanbe, upgraded to 1.7 and that fixed the problem.
