### ISSUE TITLE
With a long package name, a parse error occurs.

### ISSUE THREAD

**Issue by hogehogehugahuga** [future-architect/vuls#391]
# Environment

Oracle Linux Server release 7.1 Local scan mode.

## Vuls

Hash :  vuls v0.2.0 af5a120

## OS
- Target Server: Oracle Linux Server release 7.1
- Vuls Server: Same server.(Oracle Linux Server release 7.1)

## Go
- Go version: go version go1.8 linux/amd64

# Current Output

Please re-run the command using ```-debug``` and provide the output below.

# Addition Details

`vuls scan` failed.

```
# vuls scan
...
[date] ERROR [localhost] Failed to scan vulnerable packages
[date] ERROR [localhost] Error: localhost, err: [Failed to parse LANGUAGE=en_US.UTF-8 yum --color=never check-update. err: Unknown format: gnome-shell-extension-alternate-tab.noarch]
...
# yum check-update
読み込んだプラグイン：langpacks

ModemManager.x86_64 ...
...
gnome-shell.x86_64                     3.14.4-53.el7                  ol7_latest   
gnome-shell-extension-alternate-tab.noarch
                                       3.14.4-21.el7                  ol7_latest   
gnome-shell-extension-apps-menu.noarch 3.14.4-21.el7                  ol7_latest   
gnome-shell-extension-common.noarch    3.14.4-21.el7                  ol7_latest   
gnome-shell-extension-launch-new-instance.noarch
                                       3.14.4-21.el7                  ol7_latest   
gnome-shell-extension-places-menu.noarch
                                       3.14.4-21.el7                  ol7_latest   
gnome-shell-extension-window-list.noarch
                                       3.14.4-21.el7                  ol7_latest   
gnome-system-log.x86_64                1:3.9.90-3.el7                 ol7_latest   
gnome-system-monitor.x86_64            3.14.1-4.el7                   ol7_latest   
gnome-terminal.x86_64                  3.14.3-13.el7                  ol7_latest   
gnome-themes-standard.x86_64           3.14.2.2-2.el7                 ol7_latest   
...
#
```

**Comment by hogehogehugahuga** [comment]
I tried the following changes.

- executil.go#L225
  - Before: session.RequestPty("xterm", 400, 1000, modes)
  - After: session.RequestPty("xterm", 400, 2000, modes)
    - There was no effected..

LANGUAGE=en_US.UTF-8 yum --color=never check-update: 
[yum_check-update.txt](https://github.com/future-architect/vuls/files/857031/yum_check-update.txt)

**Comment by hogehogehugahuga** [comment]
I confirmed a similar situation.
- On CentOS68, tcpdump.x86_64: 14:4.0.0-9.20090921gitdf3cb4.2.el6
- Too long to yum check-update. It is longer than expected format.

![yum_update](https://cloud.githubusercontent.com/assets/7194310/24387013/b2578580-13ad-11e7-8e5b-372239826d17.PNG)

**Comment by knqyf263** [comment]
I think it is a problem of the width of the terminal.
The following command will work.
`$ stty columns 1000; yum check-update`

PR welcome!

**Comment by kotakanbe** [comment]
Please try v0.4.0.
If you are still in trouble, please reopen.
