### ISSUE TITLE
 vuls configtest --debugがsudoのチェックで止まってしまう

### ISSUE THREAD

**Issue by lv7777** [future-architect/vuls#395]
# Environment
```
root@kaliProvisional:~/.ssh# uname -a
Linux kaliProvisional 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux
```
## Vuls

Hash : commit af5a1204bc42cd87312ff022597aeb1f28722840

## OS

kali os

## Go
- Go version: go version go1.7.4 linux/amd64

# Current Output

現在` vuls configtest --debug`をすると、5分ぐらい下の状態で止まってしまい

```
[Mar 21 09:43:30]  INFO [localhost] Validating config...
[Mar 21 09:43:30]  INFO [localhost] Detecting Server/Container OS... 
[Mar 21 09:43:30]  INFO [localhost] Detecting OS of servers... 
[Mar 21 09:43:30] DEBUG [localhost] execResult: servername: localhost

[Mar 21 09:43:31] DEBUG [localhost] Debian like Linux. Host: 127.0.0.1:22
[Mar 21 09:43:31]  INFO [localhost] (1/1) Detected: localhost: kali kali-rolling
[Mar 21 09:43:31]  INFO [localhost] Detecting OS of containers... 
[Mar 21 09:43:31]  INFO [localhost] Checking dependendies...
[Mar 21 09:43:31]  INFO [localhost] Checking sudo settings...
[Mar 21 09:43:31]  INFO [localhost] Checking... sudo apt-get update

```

5分ぐらい経つと

```
[Mar 21 09:48:31] ERROR [localhost] Timed out: localhost
[Mar 21 09:48:31]  INFO [localhost] Scannable servers are below...
```
という状態で止まってしまいます。

sshdは22で待機しており、手元ではちゃんとsshが出来ています。

元々、kaliをapt-getすると、sources listに死んだリポジトリがあり、apt-get updateが上手くいかなかったのですが、souceslistを修正して、再起動しても治りません。

これの奇妙な点は、手元では`apt-get update`に成功する点です。もちろんsshも上手く行きます。
また、ソースコード内のapt-getしている部分を`cmd := util.PrependProxyEnv("echo a")`という風に変えてbuildしなおしても変わりませんでした。

そもそもrootでログインしている為、sudoのチェックはいらないはずです。

```config.toml 
[servers]

[servers.localhost]
host="127.0.0.1"
port="22"
user="vuls"
keyPath="/home/vuls/.ssh/id_rsa"

```

```config.toml 
[servers]

[servers.localhost]
host="localhost"
port="local"
```
2つのconfを試して見ましたがエラーメッセージは変わりませんでした。
# Addition Details

Can you also please fill in each of the remaining sections.

**Comment by kotakanbe** [comment]
Thanks for send a issue, But please use English on GitHub Issue as everyone can understand
. If you want to communicate in Japanese, Please Join Vuls slack and Join #vulsjp
Thanks.

https://docs.google.com/forms/d/e/1FAIpQLSfMyxCKV0C1ukTE0Mc9oyOHDI_2nbz4L75LAMj0D_A2vx_fMA/viewform?c=0&w=1
