### ISSUE TITLE
support kali linux

### ISSUE THREAD

**Issue by lv7777** [future-architect/vuls#398]
# Environment

```
root@kaliProvisional:~/.ssh# uname -a
Linux kaliProvisional 4.6.0-kali1-amd64 #1 SMP Debian 4.6.4-1kali1 (2016-07-21) x86_64 GNU/Linux
```

## Vuls
Hash : af5a1204bc42cd87312ff022597aeb1f28722840 
## OS

both environment is same.kali linux

## Go
- Go version: go version go1.7.4 linux/amd64

# Current Output

I can't copy the output. sorry.
but last output the first time is`kali linux is not implemented yet`

# Addition Details

I confirmation the program is reach `detectDebian` function using "printf debug".

and detectDebian function is running four shell command.

`ls /etc/debian_version` and `cat /etc/issue` and `lsb_release -ir` and `cat /etc/lsb-release`

these command is success on my environment, and this function is success, so this program is detect "the environment is debian like".

https://github.com/future-architect/vuls/blob/master/scan/debian.go#L144

in `checkDependencies` is return false because `o.Distro.Family` is `kali`, but `kali` is no swiching parameter.

so I fix 
https://github.com/future-architect/vuls/blob/master/scan/debian.go#L144 to `case "ubuntu", "raspbian", "kali":` the issue is seem fixed.

related #397

## Expected Behavior

support kali linux in vuls

## Actual Behavior

not support kali linux in vuls

## Steps to reproduce the behaviour

1. install vuls
2. write config.toml
3. `vuls configtest --debug`

**Comment by knqyf263** [comment]
@lv7777 Thanks for your issue.

I tried to use `apt-get changelog` on Kali Linux, but I could not use it.

`vuls` uses changelog to detect the vulnerable packages in the case of Debian.
So, it seems to be difficult to support Kali Linux right away...

We are planning to support OVAL in the near future.
Once it's done, `vuls` may be able to support `Kali Linux`.
Please wait a while.

**Comment by kotakanbe** [comment]
If you still want this, please re-open the issue.
