### ISSUE TITLE
169.254.169.254 port 80: Connection refused

### ISSUE THREAD

**Issue by Klar** [future-architect/vuls#402]
`vuls scan -config=/var/vuls/config.toml -results-dir=/var/vuls/results -cachedb-path=/var/vuls/cache.db --debug servername`

```
[Mar 24 09:41:40] DEBUG [servername] execResult: servername: servername
  cmd: set -o pipefail; curl --max-time 1 --retry 3 --noproxy 169.254.169.254 http://169.254.169.254/latest/meta-data/instance-id
  exitstatus: 7
  stdout: curl: (7) Failed to connect to 169.254.169.254 port 80: Connection refused
```

I see that the connection is refused. Do I need to search where or why this is blocked or for what is this used?

I see it's a link-local address.

**Comment by knqyf263** [comment]
@Klar Hello! Thank you for your report!
`vuls` uses `curl` to detect whether target is running on AWS.
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html
https://github.com/future-architect/vuls/blob/cd841462cda948b79ceb9e6a4f9ac8ae98fda9d3/scan/base.go#L218

So, `exitstatus: 7` may be no problem.
https://github.com/future-architect/vuls/blob/cd841462cda948b79ceb9e6a4f9ac8ae98fda9d3/scan/base.go#L229

Do you have any problem with that message? (fail to scan, etc.)

**Comment by Klar** [comment]
Hey,

No, that's fine then. I thought maybe it's something which should work, but as I am not on AWS I can ignore it then.

Thanks for your answer, and the next time I will check the source first :)

**Comment by knqyf263** [comment]
Yes, if you don't use AWS, you can ignore this error.
Feel free to ask us if you have any problems!
