### ISSUE TITLE
Failed to scan - kernel-xxx is an installed security update

### ISSUE THREAD

**Issue by anayama** [future-architect/vuls#403]
# Environment

## Vuls

Hash : 227da93

## OS

AmazonLinux 2016.09

## Go

go version go1.6 linux/amd64

# Current Output

```
Security: kernel-4.4.51-40.58.amzn1.x86_64 is an installed security update
Security: kernel-4.4.23-31.51.amzn1.x86_64 is the currently running version
, stderr: , err: %!s(<nil>)
[Mar 24 19:33:45] ERROR [NFS] Failed to scan vulnerable packages
[Mar 24 19:33:45] ERROR [localhost] Failed to scan. err: ec2-user@x.x.x.x:22: Failed to parse LANG=en_US.UTF-8 yum --color=never check-update. err: Unknown format: Security: kernel-4.4.51-40.58.amzn1.x86_64 is an installed security update
```

# Addition Details

After updating the OS kernel, Vuls scan error occurs unless the server is restarted.
Since content is not a problem, I'd like you to continue scanning as a warning.

**Comment by anayama** [comment]
There is no reproducibility in the latest version (ver. 0.3.0).
Sorry, The problem was solved.

**Comment by knqyf263** [comment]
I'm sorry for late reply.
It is caused by the short width of the tty, but it has been fixed recently.
Thanks for your report!
