### ISSUE TITLE
go get not get 

### ISSUE THREAD

**Issue by jhautefeuille** [future-architect/vuls#407]
go get github.com/kotakanbe/go-cve-dictionary
package github.com/labstack/echo/engine/standard: cannot find package "github.com/labstack/echo/engine/standard"

Ubuntu 16.04 4.4.0-64-generic #85-Ubuntu SMP
go version go1.8 linux/amd64

Thanks

**Comment by kazuminn** [comment]
Don't `go get`
plz `make install`

Read https://github.com/future-architect/vuls#step3-deploy-go-cve-dictionary

**Comment by jhautefeuille** [comment]
Thanks it's better...
