### ISSUE TITLE
options for configtest not being activated

### ISSUE THREAD

**Issue by elfgoh** [future-architect/vuls#422]
# Environment

## Vuls

Hash : cbb2a81

## OS
- Target Server: ARM Debian 8.7 on Beaglebone black
- Vuls Server: ARM Debian 8.7 on Beaglebone black

## Go
- Go version: go version go1.8.1 linux/arm

# Current Output
```
$ vuls configtest -debug -ask-key-password -timeout=300
SSH key password: ********
[Apr 14 13:23:51]  INFO [localhost] Validating config...
[Apr 14 13:23:51]  INFO [localhost] Detecting Server/Container OS...
[Apr 14 13:23:51]  INFO [localhost] Detecting OS of servers...
Enter passphrase for key '/home/debian/.ssh/id_rsa':
[Apr 14 13:24:08] DEBUG [localhost] execResult: servername: 192-168-1-3
  cmd: /usr/bin/ssh -tt -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none root@192.168.1.3 -p 22 -i /home/debian/.ssh/id_rsa -o PasswordAuthentication=no stty cols 1000; ls /etc/debian_version
  exitstatus: 0
  stdout: /etc/debian_version

  stderr:
  err: %!s(<nil>)
Enter passphrase for key '/home/debian/.ssh/id_rsa':
[Apr 14 13:24:21] ERROR [localhost] Timed out while detecting servers
[Apr 14 13:24:21] ERROR [localhost] (1/1) Timed out: 192-168-1-3
[Apr 14 13:24:21] ERROR [localhost] Failed to init servers: No scannable servers
```
# Addition Details

`-timeout` and `-debug` options are not passed. Fwiw, the setup was done on 2 BBB devices with connectivity via a network switch. It is validated that the server can ssh to the target

## Expected Behavior
timeout should be 300 instead of 10 in the debug output. ssh keyprhase should also not be asked

## Actual Behavior

Very fast timeout and repeated prompting of ssh keyphrase
## Steps to reproduce the behaviour

```$ vuls configtest -debug -ask-key-password -timeout=300```

**Comment by kotakanbe** [comment]
@elfgoh 
Sorry for late reply.
Thanks for telling. I will investigate.

**Comment by kotakanbe** [comment]
I think that this problem has already been fixed.
Please re-open this issue if you are still in trouble.
