### ISSUE TITLE
Vuls not sending email Using Gmail

### ISSUE THREAD

**Issue by finid** [future-architect/vuls#423]
# Environment

## Vuls

Hash : f878e22

## OS
- Target Server: Ubuntu 16.04
- Vuls Server: Ubuntu 16.04

## Go
- Go version: 1.8

This is the sample **Email** section in the docs, so this is just a question regarding that section of the config file:

```
[email]
smtpAddr      = "smtp.gmail.com"
smtpPort      = "587"
user          = "username"
password      = "password"
from          = "from@address.com"
to            = ["to@address.com"]
cc            = ["cc@address.com"]
subjectPrefix = "[vuls]"
```
1. Other than the **cc** key, which other key is optional?

2. If I have a send-only SMTP server installed on the server, how would the **Email** section look?

**Comment by kotakanbe** [comment]
Hi, @finid 

In my environment I can send email via Gmail.
You may know something if you run with the --debug flag.

1. from , cc, subjectPrefix is optional.
2. I have not tried it. Please tell me when you try.

**Comment by finid** [comment]
1. I keep getting credentials error with the same credentials I use to log into my Gmail account. Works with another email service provider, just not with Gmail. 

2. I've tried sending using the send-only SMTP server installed on the server, but it doesn't work. Vuls seems to require only using a 3rd party email service to send emails. For using a local SMTP server, the **Email** section of the config file needs to be trimmed, like the following, with the **to** key as the only non-optional key:

```
[email]
from          = "from@address.com"
to            = ["to@address.com"]
cc            = ["cc@address.com"]
subjectPrefix = "[vuls]"
```

**Comment by kotakanbe** [comment]
Sorry for late reply.
Vuls supports SMTP over TLS only for now.

It seems that SMTP transmission can be implemented easily.
This page is helpful.
https://github.com/golang/go/wiki/SendingMail

**Comment by kotakanbe** [comment]
Nobody wants
