### ISSUE TITLE
Vuls scan doesn't show severity score in any of the vulnerable packages

### ISSUE THREAD

**Issue by pratikjoy7** [future-architect/vuls#430]
# Environment
Amazon aws EC2

## OS
- Target Server: Ubuntu 16.04
- Vuls Server: Ubuntu 16.04

## Go
- Go version: 1.7.1

# Current Output

Please re-run the command using ```-debug``` and provide the output below.

# Addition Details

Can you also please fill in each of the remaining sections.

## Expected Behavior
Reports generated from `vuls scan` should assign severity score.
## Actual Behavior
All vulnerable packages were listed in `UnknownCves` list and the `KnownCves` list was empty. The vulnerable packages had NVD and JVN score of 0.
## Steps to reproduce the behaviour
Scan completes successfully without error. So, unsure about how to reproduce this. Every time I run vuls scan the same thing happens.
Note: Previous scan reports had score attached. I am facing this problem since last month.

**Comment by kotakanbe** [comment]
I can't reproduce it.
The Report subcommand select SQLite3 of go-cve-dictionary to find the detailed information.
I think that it is a problem that vulnerability information can not be found.

Please try the following.
- Delete existing SQLite 3 database
- Fetch Vuln Database again. 
  https://github.com/kotakanbe/go-cve-dictionary#usage-fetch-nvd-data
- Reporting

**Comment by kotakanbe** [comment]
Please re-open if you still have the problem.
