### ISSUE TITLE
compile faild

### ISSUE THREAD

**Issue by chennqqi** [future-architect/vuls#436]
# github.com/future-architect/vuls/report
report/azureblob.go:142: cli.CreateBlockBlobFromReader undefined (type storage.BlobStorageClient has no field or method CreateBlockBlobFromReader)
report/tui.go:46: undefined: gocui.OutputNormal
report/tui.go:46: too many arguments in call to gocui.NewGui
	have (<T>)
	want ()
report/tui.go:46: assignment count mismatch: 2 = 1
report/tui.go:178: assignment count mismatch: 2 = 1
report/tui.go:182: assignment count mismatch: 2 = 1
report/tui.go:184: assignment count mismatch: 2 = 1
report/tui.go:186: assignment count mismatch: 2 = 1
report/tui.go:188: assignment count mismatch: 2 = 1
report/tui.go:190: assignment count mismatch: 2 = 1
report/tui.go:190: too many errors

**Comment by kotakanbe** [comment]
You should use `make install` or `make build` (not go get).
https://github.com/future-architect/vuls#step4-deploy-vuls

**Comment by chennqqi** [comment]
Thank you, finally done!
Maybe network problem(FUCK GFW)!
Close this issue.
