### ISSUE TITLE
Possible to scan images in OpenShift Registry with vuls?

### ISSUE THREAD

**Issue by mylespollie** [future-architect/vuls#437]
I'm looking to implement a CVE scanner that works with my Integrated OpenShift Registry.  Is this something I can accomplish with vuls?  Additionally, would vuls put any load on my running containers?

**Comment by kotakanbe** [comment]
Vuls can't directly scan images in the Docker Registry.
Vuls can scan a running container.
I think that container scanning will not be so heavy. Try it in a test environment.
