### ISSUE TITLE
Simply vuls scan Physical Hypervisor Indicates VERY HIGH load average

### ISSUE THREAD

**Issue by wnoguchi** [future-architect/vuls#438]
# Environment

## Vuls

Hash : fecd1ad

To check the commit hash of HEAD
$ vuls -v

or
$ cd $GOPATH/src/github.com/future-architect/vuls 
$ git rev-parse --short HEAD 

## OS
- Target Server: CentOS7, 6, 5(EOL), Ubuntu 16.04, 14 Mixed
- Vuls Server: CentOS 7.3.1611 x86_64

## Go
- Go version: go version go1.7.1 linux/amd64

# Current Output

Please re-run the command using ```-debug``` and provide the output below.

# Addition Details

Can you also please fill in each of the remaining sections.

## Steps to reproduce the behaviour

We scanned weekly hundreds of servers.

```
vuls scan
```

But vuls default behavior seems to run parallel SSH connections.
Thus Same Physical Server VMs runs yum or apt command parallels.
Finally, our Zabbix Notify Hypervisor VERY HIGH load average...
Worst case, HA Cluster falls split brain then inconsistent states...

Above these reasons, we escape this problems run following

```
vuls scan server1
vuls scan server2
...
vuls scan server115
```

But this method will report each servers, TUI, report show last one scan result only...

Any ideas?

Thanks.

**Comment by kotakanbe** [comment]
I asked users the question at Vuls-slack. Please check it out.
https://vuls-github.slack.com/archives/C0VTPKS3T/p1496804076985509
(in Japanese)

**Comment by kotakanbe** [comment]
By the way, the low load scan mode is implemented in the next version.

**Comment by wnoguchi** [comment]
Thanks! and I'll join vuls-slack.

**Comment by kotakanbe** [comment]
Please try v0.4.0.
Fast scan mode don't consume resources of the scan target server.
If you are still in trouble, please reopen.

**Comment by wnoguchi** [comment]
thanks.
I'll try it.
