### ISSUE TITLE
Can't scan remote server - (centos 7 - updated)

### ISSUE THREAD

**Issue by dcialdella** [future-architect/vuls#451]
# Environment

**POSSIBLE SOLUTION
ERROR**
    LANGUAGE=en_US.UTF-8 yum --color=never  check-update
**WORKING**
   env LANGUAGE=en_US.UTF-8 yum --color=never  check-update

## Vuls

Hash : ____

To check the commit hash of HEAD
$ vuls -v

vuls 0.3.0 

or
$ cd $GOPATH/src/github.com/future-architect/vuls 
$ git rev-parse --short HEAD 

## OS
- Target Server: Centos 7 
- Vuls Server: Kali 2017.1 

## Go
- Go version: go version go1.7.1 linux/amd64

# Current Output

Please re-run the command using ```-debug``` and provide the output below.

[Jul 18 10:55:16] DEBUG [192-168-11-10] execResult: servername: 192-168-11-10
  cmd: /usr/bin/ssh -tt -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none root@192.168.11.10 -p 22 -i /root/.ssh/id_rsa -o PasswordAuthentication=no stty cols 1000; LANGUAGE=en_US.UTF-8 yum --color=never  check-update
  exitstatus: 127
  stdout: Unsupported use of '='. To run 'yum' with a modified environment, please use 'env LANGUAGE=en_US.UTF-8 yum…'
fish: stty cols 1000; LANGUAGE=en_US.UTF-8 yum --color=never  check-update
                      ^

  stderr: 
  err: %!s(<nil>)
[Jul 18 10:55:16] ERROR [192-168-11-10] Failed to scan vulnerable packages
[Jul 18 10:55:16] ERROR [localhost] Error: 192-168-11-10, err: [Failed to SSH: execResult: servername: 192-168-11-10
  cmd: /usr/bin/ssh -tt -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none root@192.168.11.10 -p 22 -i /root/.ssh/id_rsa -o PasswordAuthentication=no stty cols 1000; LANGUAGE=en_US.UTF-8 yum --color=never  check-update
  exitstatus: 127
  stdout: Unsupported use of '='. To run 'yum' with a modified environment, please use 'env LANGUAGE=en_US.UTF-8 yum…'
fish: stty cols 1000; LANGUAGE=en_US.UTF-8 yum --color=never  check-update
                      ^

  stderr: 
  err: %!s(<nil>)]

One Line Summary
================
192-168-11-10	Error		Run with --debug to view the details

# Addition Details

vuls scan
[Jul 18 10:51:23]  INFO [localhost] Start scanning
[Jul 18 10:51:23]  INFO [localhost] config: /root/config.toml
[Jul 18 10:51:23]  INFO [localhost] Validating config...
[Jul 18 10:51:23]  INFO [localhost] Detecting Server/Container OS... 
[Jul 18 10:51:23]  INFO [localhost] Detecting OS of servers... 
[Jul 18 10:51:26]  INFO [localhost] (1/1) Detected: 192-168-11-10: centos 7.3.1611
[Jul 18 10:51:26]  INFO [localhost] Detecting OS of containers... 
[Jul 18 10:51:26]  INFO [localhost] Detecting Platforms... 
[Jul 18 10:51:26]  INFO [localhost] (1/1) 192-168-11-10 is running on other
[Jul 18 10:51:26]  INFO [localhost] Scanning vulnerabilities... 
[Jul 18 10:51:26]  INFO [localhost] Scanning vulnerable OS packages...
[Jul 18 10:51:29] ERROR [192-168-11-10] Failed to scan vulnerable packages
[Jul 18 10:51:29] ERROR [localhost] Error: 192-168-11-10, err: [Failed to SSH: execResult: servername: 192-168-11-10
  cmd: /usr/bin/ssh -tt -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none root@192.168.11.10 -p 22 -i /root/.ssh/id_rsa -o PasswordAuthentication=no stty cols 1000; LANGUAGE=en_US.UTF-8 yum --color=never  check-update
  exitstatus: 127
  stdout: Unsupported use of '='. To run 'yum' with a modified environment, please use 'env LANGUAGE=en_US.UTF-8 yum…'
fish: stty cols 1000; LANGUAGE=en_US.UTF-8 yum --color=never  check-update
                      ^

  stderr: 
  err: %!s(<nil>)]

One Line Summary
================
192-168-11-10	Error		Run with --debug to view the details

**Comment by dcialdella** [comment]
I checked it again.


**THIS DO NOT WORKS**
cmd: /usr/bin/ssh -tt -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none root@192.168.11.10 -p 22 -i /root/.ssh/id_rsa -o PasswordAuthentication=no stty cols 1000; LANGUAGE=en_US.UTF-8 yum --color=never  check-update
  exitstatus: 127
  stdout: Unsupported use of '='. To run 'yum' with a modified environment, please use 'env LANGUAGE=en_US.UTF-8 yum…'
fish: stty cols 1000; LANGUAGE=en_US.UTF-8 yum --color=never  check-update




**THIS WORKS**

cmd: /usr/bin/ssh -tt -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none root@192.168.11.10 -p 22 -i /root/.ssh/id_rsa -o PasswordAuthentication=no stty cols 1000; **## env** LANGUAGE=en_US.UTF-8 yum --color=never  check-update
  exitstatus: 127
  stdout: Unsupported use of '='. To run 'yum' with a modified environment, please use 'env LANGUAGE=en_US.UTF-8 yum…'
fish: stty cols 1000; LANGUAGE=en_US.UTF-8 yum --color=never  check-update

**Comment by kotakanbe** [comment]
@dcialdella 
Thanks for reporting.
But Vuls doesn't support fishshell for now.

see 
https://github.com/future-architect/vuls#misc
> Does Vuls accept SSH connections with fish-shell or old zsh as the login shell?
> No, Vuls needs a user on the server for bash login. see also #8
