### ISSUE TITLE
Kali-rolling not supported

### ISSUE THREAD

**Issue by dcialdella** [future-architect/vuls#452]
# Environment

## Vuls

Hash : ____

To check the commit hash of HEAD
$ vuls -v

or
$ cd $GOPATH/src/github.com/future-architect/vuls 
$ git rev-parse --short HEAD 

## OS
- Target Server: Kali
- Vuls Server: Write here

## Go
- Go version: here

# Current Output

Please re-run the command using ```-debug``` and provide the output below.

vuls configtest
[Jul 18 11:24:49]  INFO [localhost] Validating config...
[Jul 18 11:24:49]  INFO [localhost] Detecting Server/Container OS... 
[Jul 18 11:24:49]  INFO [localhost] Detecting OS of servers... 
[Jul 18 11:24:50]  INFO [localhost] (1/2) Detected: local: kali kali-rolling
[Jul 18 11:24:52]  INFO [localhost] (2/2) Detected: 192-168-11-10: centos 7.3.1611
[Jul 18 11:24:52]  INFO [localhost] Detecting OS of containers... 
[Jul 18 11:24:52]  INFO [localhost] Checking dependendies...
[Jul 18 11:24:52] **ERROR [localhost] Error: local, err: [Not implemented yet: kali kali-rolling]**
[Jul 18 11:24:53]  INFO [192-168-11-10] Dependencies... Pass
[Jul 18 11:24:53]  INFO [localhost] Checking sudo settings...
[Jul 18 11:24:53]  INFO [192-168-11-10] Checking... sudo yum --changelog --assumeno update yum
[Jul 18 11:24:55]  INFO [192-168-11-10] Sudo... Pass
[Jul 18 11:24:55]  INFO [localhost] Scannable servers are below...
192-168-11-10 

# Addition Details

Can you also please fill in each of the remaining sections.

**Comment by dcialdella** [comment]
I **SOLVED** this way (quick and dirty)

cat /etc/lsb-release 
DISTRIB_ID=Debian 9 # Kali
DISTRIB_RELEASE=Debian # kali-rolling
DISTRIB_CODENAME=Debian 9 # kali-rolling
DISTRIB_DESCRIPTION="Kali GNU/Linux Rolling"

**Comment by kotakanbe** [comment]
If you want to support Kali Linux, Thumb up please :)

**Comment by finid** [comment]
Kali Rolling is based on Debian, so this shouldn't be much of an issue.

**Comment by kotakanbe** [comment]
If you still want this, please re-open the issue.
