### ISSUE TITLE
README.md.ja not include "Oracle Linux, FreeBSD" 

### ISSUE THREAD

**Issue by ribbon26** [future-architect/vuls#465]
# Environment

## Vuls

Hash : ____

To check the commit hash of HEAD
$ vuls -v

or
$ cd $GOPATH/src/github.com/future-architect/vuls 
$ git rev-parse --short HEAD 

## OS
- Target Server: FreeBSD
- Vuls Server: FreeBSD

## Go
- Go version: here

# Current Output

In README.md  Main Features section, there are the following line

Supports Ubuntu, Debian, CentOS, Amazon Linux, RHEL, Oracle Linux, FreeBSD and Raspbian

but README.md.ja not include "Oracle Linux, FreeBSD" 

# Addition Details

**Comment by kotakanbe** [comment]
Pull request welcome :)

**Comment by kotakanbe** [comment]
Thanks.
I fixed in support_oval branch. the branch will be released on 8/25
