### ISSUE TITLE
Cannot connect to servers

### ISSUE THREAD

**Issue by Xat59** [future-architect/vuls#468]
# Environment

## Vuls
$ docker run  --rm  vuls/vuls -v
vuls v0.3.0 2cec20c

## OS
- Target Server: I tried with CentOS and Ubuntu
- Vuls Server: based on vuls/vuls docker image

## Go
- Go version: based on vuls/vuls docker image

# Current Output
$ cd vuls

$ ls -l
total 4
-rw-rw-r-- 1 xat  xat  106 25 août  10:21 config.toml
drwxr-xr-x 2 root root  22 25 août  00:05 vuls-log

$ cat config.toml 
[servers]

[servers.amazon]
host = "10.20.112.13"
port = "22"
user = "root"
keyPath = "/root/.ssh/id_rsa"

$ ssh root@10.20.112.13 -p 22 -i ~/.ssh/id_rsa 
The authenticity of host '10.20.112.13 (10.20.112.13)' can't be established.
ECDSA key fingerprint is 78:96:c4:df:e5:da:9b:32:2f:6c:9d:0d:a3:c2:2e:ca.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '10.20.112.13' (ECDSA) to the list of known hosts.
Last login: Fri Aug 25 00:20:01 2017 from xat-pc

$ docker run --rm -it     -v ~/.ssh:/root/.ssh:ro     -v $PWD:/vuls     -v $PWD/vuls-log:/var/log/vuls     vuls/vuls configtest     -debug -config=./config.toml
[Aug 25 08:26:29]  INFO [localhost] Validating config...
[Aug 25 08:26:29]  INFO [localhost] Detecting Server/Container OS... 
[Aug 25 08:26:29]  INFO [localhost] Detecting OS of servers... 
[Aug 25 08:26:29] DEBUG [localhost] execResult: servername: amazon
  cmd: /usr/bin/ssh -tt -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none root@10.20.112.13 -p 22 -i /root/.ssh/id_rsa -o PasswordAuthentication=no stty cols 1000; ls /etc/debian_version
  exitstatus: 255
  stdout: 
  stderr: 
  err: %!s(<nil>)
[Aug 25 08:26:29] ERROR [localhost] (1/1) Failed: amazon, err: [Failed to detect OS: Unable to connect via SSH. Check SSH settings. execResult: servername: amazon
  cmd: /usr/bin/ssh -tt -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none root@10.20.112.13 -p 22 -i /root/.ssh/id_rsa -o PasswordAuthentication=no stty cols 1000; ls /etc/debian_version
  exitstatus: 255
  stdout: 
  stderr: 
  err: %!s(<nil>)]
[Aug 25 08:26:29] ERROR [localhost] Failed to init servers: No scannable servers

# Addition Details
As you can see, I'm able to connect without password using the SSH command.

## Expected Behavior
- configtest works
- enable to connect to specified servers

## Actual Behavior
See debug errors

## Steps to reproduce the behaviour
$ mkdir vuls && cd vuls

$ docker pull vuls/vuls

$ cat > config.toml <<EOF
[servers]

[servers.amazon]
host = "10.20.112.13"
port = "22"
user = "root"
keyPath = "/root/.ssh/id_rsa"
EOF

$ ssh-copy-id -i ~/.ssh/id_rsa root@10.20.112.13

$ docker run --rm -it     -v ~/.ssh:/root/.ssh:ro     -v $PWD:/vuls     -v $PWD/vuls-log:/var/log/vuls     vuls/vuls configtest     -debug -config=./config.toml

Thank a lot team !

**Comment by kotakanbe** [comment]
Hi, @Xat59 

>$ docker run --rm vuls/vuls -v
>vuls v0.3.0 2cec20c

The latest version of is v0.4.0

On my environment
```
$ docker run  --rm  vuls/vuls -v
vuls v0.4.0 a8bc253

```

Please remove vuls, go-cve-dictionary and goval-dictionary beforehand.
For details, see

https://github.com/future-architect/vuls/tree/master/setup/docker#caution
2. Remove your old docker images

**Comment by Xat59** [comment]
Hi @kotakanbe ,

so I removed the old docker image and used the new one.

$ docker rmi vuls/vuls

$ cd vuls

$ docker run  --rm  vuls/vuls -v
vuls v0.4.0 a8bc253

$ docker run --rm -it     -v ~/.ssh:/root/.ssh:ro     -v $PWD:/vuls     -v $PWD/vuls-log:/var/log/vuls     vuls/vuls configtest     -debug -config=./config.toml
[Aug 25 09:15:19]  INFO [localhost] Validating config...
[Aug 25 09:15:19]  INFO [localhost] Detecting Server/Container OS... 
[Aug 25 09:15:19]  INFO [localhost] Detecting OS of servers... 
[Aug 25 09:15:19] DEBUG [localhost] Executing... ls /etc/debian_version
[Aug 25 09:15:19] DEBUG [localhost] execResult: servername: amazon
  cmd: /usr/bin/ssh -tt -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none root@10.20.112.13 -p 22 -i /root/.ssh/id_rsa -o PasswordAuthentication=no stty cols 1000; ls /etc/debian_version
  exitstatus: 255
  stdout: 
  stderr: 
  err: %!s(<nil>)
[Aug 25 09:15:19] ERROR [localhost] (1/1) Failed: amazon, err: [Failed to detect OS: Unable to connect via SSH. Check SSH settings. If you have never SSH to the host to be scanned, SSH to the host before scanning in order to add the HostKey. root@10.20.112.13 port: 22
execResult: servername: amazon
  cmd: /usr/bin/ssh -tt -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none root@10.20.112.13 -p 22 -i /root/.ssh/id_rsa -o PasswordAuthentication=no stty cols 1000; ls /etc/debian_version
  exitstatus: 255
  stdout: 
  stderr: 
  err: %!s(<nil>)]
[Aug 25 09:15:19] ERROR [localhost] Failed to init servers: No scannable servers


I have the same behavior

**Comment by kotakanbe** [comment]
The error message shows unable to connect to scan target server from docker container via ssh.
Please check SSH connection like this.
```
$ docker run --rm -it\ 
                    -v ~/.ssh:/root/.ssh:ro \
                    -v $PWD:/vuls \
                    -v $PWD/vuls-log:/var/log/vuls \
                    --entrypoint=/bin/sh vuls/vuls -c 'ssh root@10.20.112.13 -vvv -p22 -i /root/.ssh/id_rsa'
```

**Comment by Xat59** [comment]
Thank a lot @kotakanbe .
The problem was the owner/group permission on exported files :

```
$ docker run --rm -it -v ~/.ssh:/root/.ssh:ro  -v $PWD:/vuls -v $PWD/vuls-log:/var/log/vuls --entrypoint=/bin/sh vuls/vuls -c 'ssh root@10.20.112.13 -vvv -p22 -i /root/.ssh/id_rsa'
OpenSSH_7.4p1 Debian-10+deb9u1, OpenSSL 1.0.2l  25 May 2017
Bad owner or permissions on /root/.ssh/config
```

So I changed them :
```
$ chown root: ~/.ssh/{id_rsa,config}
```

And tried again, successfully :
```
docker run --rm -it     -v ~/.ssh:/root/.ssh:ro     -v $PWD:/vuls     -v $PWD/vuls-log:/var/log/vuls     vuls/vuls configtest     -config=./config.toml                                      
[Aug 25 09:55:19]  INFO [localhost] Validating config...
[Aug 25 09:55:19]  INFO [localhost] Detecting Server/Container OS... 
[Aug 25 09:55:19]  INFO [localhost] Detecting OS of servers... 
[Aug 25 09:55:20]  INFO [localhost] (1/1) Detected: amazon: centos 7.3.1611
[Aug 25 09:55:20]  INFO [localhost] Detecting OS of containers... 
[Aug 25 09:55:20]  INFO [localhost] Checking dependencies...
[Aug 25 09:55:20]  INFO [amazon] Dependencies ... Pass
[Aug 25 09:55:20]  INFO [localhost] Checking sudo settings...
[Aug 25 09:55:20]  INFO [amazon] sudo ... No need
[Aug 25 09:55:20]  INFO [localhost] Scannable servers are below...
amazon 
```

Thank a lot

**Comment by kotakanbe** [comment]
I'm glad the problem was solved.

**Comment by mlipkin** [comment]
I had this problem too. My ~/.ssh/config file has to be owned by root and set to 600. Or simply move the config file out of the .ssh directory.
