### ISSUE TITLE
vuls discover fails

### ISSUE THREAD

**Issue by ama2** [future-architect/vuls#471]
# Environment
CentOS 7.3

## Vuls

Hash : 0ba490c6df24561af761134bbb0ffd5743d39c04

$ vuls -v
vuls v0.4.0 0ba490c

## OS
- Target Server: CentOS7.3
- Vuls Server: CentOS7.3

## Go
- Go version: go version go1.8.3 linux/amd64

# Current Output
$ vuls discover  192.168.2.0/24
ERRO[0020] Active hosts not found in 192.168.2.0/24

# Addition Details

## Expected Behavior
Ping fails for actually exist server

## Actual Behavior
Ping success for actually exist server

## Steps to reproduce the behaviour
- server(192.168.1.10/24) login
- exec ```vuls discover 192.168.2.0/24```

# Cause
I think that the option designation of go-pingscanner.
"-t1" is specified in commands/discover.go.
So ping cannot exceed the subnet.

thanks a lot!

**Comment by kotakanbe** [comment]
Many Thanks!
Fixed.
