### ISSUE TITLE
yum updateinfo is not suppported on CentOS

### ISSUE THREAD

**Issue by st0rmspirit** [future-architect/vuls#477]
My  OS
CentOS release 6.5 (Final)
yum -h
![image](https://user-images.githubusercontent.com/13938323/29913854-f271118c-8e68-11e7-851d-c5d6ab6293cf.png)

hello,
In the program,you say "yum updateinfo is not suppported on CentOS,Parse chnagelog because CentOS does not have security channel",but i exec "yum -h" in my OS,it have updateinfo as you see on the pic above，is there any thing wrong?

![image](https://user-images.githubusercontent.com/13938323/29913751-a5920bd2-8e68-11e7-8320-2b33769b8c7f.png)

![image](https://user-images.githubusercontent.com/13938323/29913914-2a3deeb4-8e69-11e7-80ff-7cc7c8e35dd3.png)

**Comment by kotakanbe** [comment]
@st0rmspirit 

Please execute the commands issued by vuls such as yum updateinfo on CentOS.
I think no output will be showed.

**Comment by andrzejwp** [comment]
yum security plugin is screwed up in CentOS, unfortunately. 
Refer to https://www.centos.org/forums/viewtopic.php?t=51300
