### ISSUE TITLE
some error on go get vuls

### ISSUE THREAD

**Issue by Martwu** [future-architect/vuls#483]
# Environment

## Vuls

Hash : None

$ cd $GOPATH/src/github.com/future-architect/vuls 
$ git rev-parse --short HEAD
820831f

## OS
- Target Server: None
- Vuls Server: 3.10.42-52.145.amzn1.x86_64

## Go
- Go version:  go version go1.9 linux/amd64

# Current Output

when I do installation with go get:

    $ go get github.com/future-architect/vuls

```
 # github.com/future-architect/vuls/report
../go/src/github.com/future-architect/vuls/report/tui.go:57:24: not enough arguments in call to gocui.NewGui
        have ()
        want (gocui.OutputMode)
../go/src/github.com/future-architect/vuls/report/tui.go:58:13: g.Init undefined (type *gocui.Gui has no field or method Init)
../go/src/github.com/future-architect/vuls/report/tui.go:64:3: g.SetLayout undefined (type *gocui.Gui has no field or method SetLayout)
../go/src/github.com/future-architect/vuls/report/tui.go:190:25: multiple-value g.SetCurrentView() in single-value context
```

**Comment by kotakanbe** [comment]
@Martwu Please see Tutorial. 
https://github.com/future-architect/vuls#tutorial

**Comment by Martwu** [comment]
@kotakanbe I am sorry. It works.

**Comment by kotakanbe** [comment]
No problem :)
