### ISSUE TITLE
Possible unneeded line in documentation.

### ISSUE THREAD

**Issue by cstackpole** [future-architect/vuls#489]
In the documentation Step 2: Install requirements there is this line:

> $ ssh centos@52.100.100.100  -i ~/.ssh/private.pem

I recommend changing this to say "On your server:" as the current line does not reflect what users may have.

**Comment by kotakanbe** [comment]
Thanks. 
Would you please send me a Pull Request?
The contribution of improving documentation is greatly appreciated :)
