### ISSUE TITLE
Using Upstream Vendor Go version?

### ISSUE THREAD

**Issue by cstackpole** [future-architect/vuls#490]
Greetings,
In the documentation, "Step2. Install requirements" it says "go v1.8.3 or later (The latest version is recommended)" and then gives the install instructions.

Is there a reason why I shouldn't use the version of Go from the Upstream Vendor?
$ cat /etc/redhat-release 
Scientific Linux release 7.3 (Nitrogen)
$ rpm -qa | grep -i golang
golang-1.8.3-1.el7.x86_64
golang-src-1.8.3-1.el7.noarch
golang-bin-1.8.3-1.el7.x86_64
golang-misc-1.8.3-1.el7.noarch
$ cat /etc/profile.d/goenv.sh 
export GOROOT=/usr/lib/golang/
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

So far everything is working well. Thoughts?
Thanks!

**Comment by kotakanbe** [comment]
The version of Go tested in my environment is listed in the README.
I think that it will work with older versions, but I think you know too, You had better to use the newer version in terms of bug fixes and performance improvements :)
