### ISSUE TITLE
Deep Scan Error + my fix

### ISSUE THREAD

**Issue by cstackpole** [future-architect/vuls#491]
# Environment

## Vuls

Hash : ____

To check the commit hash of HEAD
$ vuls -v
vuls v0.4.0 820831f

or
$ cd $GOPATH/src/github.com/future-architect/vuls 
$ git rev-parse --short HEAD 
820831f

## OS
- Target Server: Scientific Linux release 7.3 (Nitrogen)
- Vuls Server: Scientific Linux release 7.3 (Nitrogen)

## Go
- Go version: here
go version go1.8.3 linux/amd64

# Current Output
$ vuls scan -deep -debug
[snip]
[Sep 12 23:23:01] DEBUG [testsrv] Executing... repoquery --all --pkgnarrow=updates --qf='%{NAME} %{EPOCH} %{VERSION} %{RELEASE} %{REPO}'
[Sep 12 23:28:01] DEBUG [testsrv] execResult: servername: testsrv
  cmd: /bin/ssh -tt -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none vuls@192.168.1.125 -p 22 -i /home/vuls/.ssh/id_rsa -o PasswordAuthentication=no stty cols 1000; sudo -S repoquery --all --pkgnarrow=updates --qf='%{NAME} %{EPOCH} %{VERSION} %{RELEASE} %{REPO}'
  exitstatus: 1
  stdout: [sudo] password for vuls: 

  stderr: 
  err: %!s(<nil>)
[Sep 12 23:28:01] ERROR [testsrv] Failed to scan installed packages: Failed to SSH: execResult: servername: testsrv
  cmd: /bin/ssh -tt -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none vuls@192.168.1.125 -p 22 -i /home/vuls/.ssh/id_rsa -o PasswordAuthentication=no stty cols 1000; sudo -S repoquery --all --pkgnarrow=updates --qf='%{NAME} %{EPOCH} %{VERSION} %{RELEASE} %{REPO}'
  exitstatus: 1
  stdout: [sudo] password for vuls: 

  stderr: 
  err: %!s(<nil>)
[Sep 12 23:28:01] ERROR [localhost] Error: testsrv, err: [Failed to SSH: execResult: servername: testsrv
  cmd: /bin/ssh -tt -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none vuls@192.168.1.125 -p 22 -i /home/vuls/.ssh/id_rsa -o PasswordAuthentication=no stty cols 1000; sudo -S repoquery --all --pkgnarrow=updates --qf='%{NAME} %{EPOCH} %{VERSION} %{RELEASE} %{REPO}'
  exitstatus: 1
  stdout: [sudo] password for vuls: 

  stderr: 
  err: %!s(<nil>)]

# Addition Details

I fixed this by granting sudo access to repoquery.

vuls@192.168.1.125 $ cat /etc/sudoers.d/vuls
vuls ALL=(ALL) NOPASSWD:/usr/bin/yum --color=never repolist, /usr/bin/yum --color=never --security updateinfo list updates, /usr/bin/yum --color=never --security updateinfo updates, /usr/bin/repoquery
Defaults:vuls env_keep="http_proxy https_proxy HTTP_PROXY HTTPS_PROXY"

This seems to be working for me so far.
Thanks!

**Comment by kotakanbe** [comment]
Thanks for telling.
I have never scanned scientific linux.

If many people are using Scientific Linux, It may be possible to support Scientific Linux if someone fix the automatic detection of OS type. 
https://github.com/future-architect/vuls/blob/master/scan/redhat.go#L55

Although it is another topic, Looking at this issue, I noticed that checks on RedHat were missing.
https://github.com/future-architect/vuls/pull/492

**Comment by cstackpole** [comment]
Greetings,
I was trying to make it clear that adding the repoquery to sudoers was the bit that fixed it for me. :-)

As for Scientific Linux, I haven't had issues (that I'm aware of yet) with vuls. I'm not really familiar with Go, but looking at the code it shouldn't be too difficult. I will poke at it for a while.
