### ISSUE TITLE
Deep scan hangs and fails due to sudo time out.

### ISSUE THREAD

**Issue by cstackpole** [future-architect/vuls#494]
# Environment

## Vuls
$ vuls -v
vuls v0.4.0 820831f

To check the commit hash of HEAD
$ vuls -v

or
$ cd $GOPATH/src/github.com/future-architect/vuls 
$ git rev-parse --short HEAD
820831f

## OS
- Target Server: Scientific Linux release 7.3 (Nitrogen)
- Vuls Server: Scientific Linux release 7.3 (Nitrogen)

## Go
- Go version:
go version go1.8.3 linux/amd64

## Expected Behavior
A deep scan should run.

## Actual Behavior
Deep scan hangs.

## Steps to reproduce the behaviour
When running a deep scan it appears to hang. On further investigation I found it was trying to run this command:
`bash -c stty cols 1000; sudo -S yum --color=never changelog all kernel-tools | sudo grep -A 10000 '==================== Available Packages ===================='`

That's a problem because the sudoers file isn't allowing that. I made a quick change to allow sudo to run with that command, but it promptly failed when it tried another package. The short but terrible fix is to just wildcard the sudo, but that's a really terrible idea. Especially when sudo isn't required for the changelog nor grep.

**Comment by kotakanbe** [comment]
Fixed in https://github.com/future-architect/vuls/pull/539
