### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by togakushi** [future-architect/vuls#5]
vuls scan後、1件も脆弱性を検出していない状態でvuls tuiを実行するとindex out of rangeが発生しました。

> $ vuls scan
INFO[0000] Begin scannig (config: /home/username/config.toml) 
[Apr  5 22:50:42]  INFO [localhost] Validating Config...
[Apr  5 22:50:42]  INFO [localhost] Detecting OS... 
[Apr  5 22:50:43]  INFO [localhost] Scanning vulnerabilities... 
[Apr  5 22:50:43]  INFO [localhost] Check required packages for scanning...
[Apr  5 22:50:43]  INFO [localhost] Scanning vuluneable OS packages...
[Apr  5 22:50:48]  INFO [rhel7:22] Fetching CVE details...
[Apr  5 22:50:48]  INFO [rhel7:22] Done
[Apr  5 22:50:48]  INFO [localhost] Scanning vulnerable software specified in CPE...
[Apr  5 22:50:48]  INFO [localhost] Reporting...
rhel7 (rhel 7.2)
 ================
No unsecure packages.
[Apr  5 22:50:48]  INFO [localhost] Insert to DB...

> $ vuls tui
panic: runtime error: index out of range
goroutine 1 [running]:
panic(0xab0dc0, 0xc82000e100)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/future-architect/vuls/report.detailLines(0x0, 0x0, 0x0, 0x0)
        /home/username/bin/go/src/github.com/future-architect/vuls/report/tui.go:657 +0x2470
github.com/future-architect/vuls/report.setDetailLayout(0xc82019fe80, 0x0, 0x0)
        /home/username/bin/go/src/github.com/future-architect/vuls/report/tui.go:629 +0x1ac
github.com/future-architect/vuls/report.layout(0xc82019fe80, 0x0, 0x0)
        /home/username/bin/go/src/github.com/future-architect/vuls/report/tui.go:504 +0x9f
github.com/jroimartin/gocui.(*Gui).flush(0xc82019fe80, 0x0, 0x0)
        /home/username/bin/go/src/github.com/jroimartin/gocui/gui.go:337 +0x16e
github.com/jroimartin/gocui.(*Gui).MainLoop(0xc82019fe80, 0x0, 0x0)
        /home/username/bin/go/src/github.com/jroimartin/gocui/gui.go:265 +0xb2
github.com/future-architect/vuls/report.RunTui(0x0)
        /home/username/bin/go/src/github.com/future-architect/vuls/report/tui.go:65 +0x426
github.com/future-architect/vuls/commands.(*TuiCmd).Execute(0xc82027da40, 0x7f1d02da8e20, 0xc82000e2d8, 0xc820298a80, 0x0, 0x0, 0x0, 0x418eb8)
        /home/username/bin/go/src/github.com/future-architect/vuls/commands/tui.go:67 +0x65
github.com/google/subcommands.(*Commander).Execute(0xc820058070, 0x7f1d02da8e20, 0xc82000e2d8, 0x0, 0x0, 0x0, 0x7f1d02da8e20)
        /home/username/bin/go/src/github.com/google/subcommands/subcommands.go:142 +0x517
github.com/google/subcommands.Execute(0x7f1d02da8e20, 0xc82000e2d8, 0x0, 0x0, 0x0, 0x10dfd60)
        /home/username/bin/go/src/github.com/google/subcommands/subcommands.go:372 +0x55
main.main()
        /home/username/bin/go/src/github.com/future-architect/vuls/main.go:43 +0x411

**Comment by kotakanbe** [comment]
Thanks, I will fix it tomorrow.

**Comment by kotakanbe** [comment]
@togakushi 
Fixed. Please update Vuls as below.
```
$ go get -u github.com/future-architect/vuls
```

**Comment by togakushi** [comment]
vuls tuiが動作することを確認しました。
ご対応ありがとうございます!!
