### ISSUE TITLE
Feature request: Sort report by CVE

### ISSUE THREAD

**Issue by cstackpole** [future-architect/vuls#500]
Greetings,
A feature request. Have an option of sorting via CVE vs hosts.

Right now, it lists the hosts then all the CVE's impacting that host. But I would like to check a CVE and see which of my servers are impacted by it alone.

I can get this with the usiusi360/vulsrepo web display, but it would be nice to have in the tui.

Thanks!

**Comment by kotakanbe** [comment]
If you still want this, please re-open the issue.
