### ISSUE TITLE
make　err　　vuls not installed

### ISSUE THREAD

**Issue by yamada555** [future-architect/vuls#501]
# Environment
centOS 7.3.1611 ,go v1.9.1
## Vuls

Hash : ____

To check the commit hash of HEAD
$ vuls -v

or
$ cd $GOPATH/src/github.com/future-architect/vuls 
$ git rev-parse --short HEAD 
5f2183f
## OS
- Target Server: Write here
- Vuls Server: centOS 7.3.1611

## Go
- Go version: 1.9.1

# Current Output

Please re-run the command using ```-debug``` and provide the output below.

# Addition Details

Can you also please fill in each of the remaining sections.

## Expected Behavior
no err
## Actual Behavior
[vuls@NSTCYBR02 vuls]$ make install
go get -u github.com/golang/dep/...
free
dep ensure
grouped write of manifest, lock and vendor: error while writing out vendor tree: failed to write dep tree: failed to export golang.org/x/text: unable to update repository: : command failed: [git fetch --tags --prune origin]: exit status 128
make: *** [dep] エラー 1

**Comment by cstackpole** [comment]
Check your path structure. These go projects /really/ did not like me placing them in my own structure and I had weird issues at first. When I moved to the structure the documentation has (eg: `export GOPATH=$HOME/go` ) then it worked for me.

Also, that looks like it was a git error. Vuls pulls in quite a few dependencies. That one is specifically related to this sub-project: $HOME/go/src/github.com/future-architect/vuls/vendor/golang.org/x/text. I would check and see if you can do a `git pull` from that directory.

**Comment by finid** [comment]
I had that type error not just with Vuls, but also when deploying go-cve-dictionary. In both cases, the solution was to delete the `vuls` or `go-cve-dictionary` directories and start all over, that is, clone, cd, then `make install`.

Hope that helps.

**Comment by kotakanbe** [comment]
@yamada555 

It might work if deleting $GOPATH/pkg and then re-run

**Comment by yamada555** [comment]
Thank you everyone for everything.
お答え頂く前に以下の方法で解決しました。
https://github.com/future-architect/vuls
上記からZIPファイルをダウンロードしてインストールしました。
gitコマンドは使用しませんでした。
このため、VULSのバージョンが表示できなくなっていますが、
Remote Scan Modeで動作確認はできました。
