### ISSUE TITLE
Adding command line options in config.toml

### ISSUE THREAD

**Issue by finid** [future-architect/vuls#505]
# Environment
Ubuntu 16.04

## vuls 

v0.4.0 

Hash : 5f2183fVuls

## OS
- Target Server: Ubuntu 16.04
- Vuls Server: Ubuntu 16.04

## Go
- Go version: 1.9

# Current Output
What I tried to do is create a new table in the config file for command line options whose value would be too long to type all the time, like the path to cve-sqlite3. So I added this to be top of `config.toml`

```
[options]
cvedb = "/home/user/go/src/github.com/kotakanbe/go-cve-dictionary/cve.sqlite3"
```

I also used another option of the key, like this:

```
[options]
cvedbPath = "/home/user/go/src/github.com/kotakanbe/go-cve-dictionary/cve.sqlite3"
```
In either case, `vuls configtest` passed, but when I ran a scan, it failed with the following output:

```
... INFO [localhost] Validating config...
ERRO[0000] SQLite3 DB path (cvedb) is not exist: /home/user/go/src/github.com/future-architect/vuls/cve.sqlite3
```

It looks like it is expecting the value of cvedb where it is not, and where it was not specified in the config file.

Question: Is specifying command line options in the config file even valid? If yes, what is the correct method of going about it?

# Addition Details

## Expected Behavior

Scan works with the path to cvedb specified int he config file
## Actual Behavior

Scan failed with the error described above.

## Steps to reproduce the behaviour

Modify the config file as described above and attempt a scan

**Comment by kotakanbe** [comment]
@finid 
It is a good idea to define option to config. However, I think it will not work as it is not yet implemented.

**Comment by finid** [comment]
Yep, it does not work, though `vuls configtest` does not complain.

**Comment by kotakanbe** [comment]
If you do not fix this function, https://github.com/future-architect/vuls/blob/master/config/tomlloader.go#L34 
TOML elements will not be loaded. It's just being neglected now. Currently there is no error with configtest because the default value is applied to the option and it happens to be no error.

**Comment by finid** [comment]
Interesting. I knew something was not right, because even with obvious errors in the config file, the test was still passing.

**Comment by kotakanbe** [comment]
merged.
