### ISSUE TITLE
How and when is OVAL called into action during a scan

### ISSUE THREAD

**Issue by finid** [future-architect/vuls#506]
# Environment

Ubuntu 16.04

## Vuls
v0.4.0 

Hash : 5f2183f

## OS
- Target Server: Ubuntu 16.04
- Vuls Server: Ubuntu 16.04

## Go
- Go version: 1.9

# Current Output

# Addition Details

## Expected Behavior

When I run a scan, I want to see an indication that OVAL is being called into action.

## Actual Behavior

I see of evidence of that, so when I run a report (`vuls report -format-short-text`), part of the output includes this line:

```
WARN [localhost] OVAL entries of ubuntu 16 are not found. It's recommended to use OVAL to improve scanning accuracy. For details, see https://github.com/kotakanbe/goval-dictionary#usage , Then report with --ovaldb-path or --ovaldb-url flag
```

Using the official docs, I deployed OVAL, but see no indication that it's being used by Vuls. Input welcome.

## Steps to reproduce the behaviour

Run a Vuls scan and report.

**Comment by oliver-machacik** [comment]
Hi finid,

That means that Vuls is not using OVAL at all. You can use the following three parameters to specify the location and type of your database.

```

**Comment by finid** [comment]
But those options are only when viewing the report, not during the scan, right?

And it false negatives are high, might be better, then, to not use OVAL, just stick with NVD?

**Comment by oliver-machacik** [comment]
After the scan you have to generate the final report before you can view it. During the Scan the OVAL and NVD data is not used at all. Both is not added to the JSON until you invoke `` vuls report ``.

In reference to your second question:
I believe in fact that using the OVAL data is superior to the changelog approach. It is far more specific in its matching criteria once it works properly. However I have to point out that I have no part in developing Vuls. This is only what I understand so far. Maybe you should wait for a more qualified answer from  kotakanbe.

**Comment by kotakanbe** [comment]
### First question: 
Scan, Report is basically divided by the following policy.
- Scan 
To ensure that it ends as soon as possible, obtain only information that can be obtained with commands with SSH etc.
- Report 
Processing matching with vulnerability database
see https://github.com/future-architect/vuls#fast-scan-and-deep-scan

### Second question:
What Olivaer pointed out is right. In the current implementation, the Debian-based OVAL comparison has false negatives so I will fix it soon. #504

**Comment by finid** [comment]
OK, that cleas up a few things. I thought the matching with the databases takes place during the scan.
