### ISSUE TITLE
 Failed to scan updatable packages: zypper -q lu Unknown format

### ISSUE THREAD

**Issue by MSPatey** [future-architect/vuls#515]
# Environment
OpenSUSE Leap 42.3
SUSE Linux Enterprise Server 11
## Vuls

Hash :  a32845f

To check the commit hash of HEAD
$ vuls -v

or
$ cd $GOPATH/src/github.com/future-architect/vuls 
$ git rev-parse --short HEAD 

## OS
- Target Server: OpenSUSE Leap 42.3
- Vuls Server: CentOS 6.9

## Go
- Go version: 1.9.1

# Current Output

 Failed to scan updatable packages: zypper -q lu Unknown format

Please re-run the command using ```-debug``` and provide the output below.

 cmd: /usr/bin/ssh -tt -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none root@172.22.1.25 -p 22 -i /tmp/id_dsa -o PasswordAuthentication=no stty cols 1000; zypper --no-color -q lu
  exitstatus: 0
  stdout: S | Repository             | Name                        | Current Version              | Available Version            | Arch
--+------------------------+-----------------------------+------------------------------+------------------------------+-------
v | Main Update Repository | device-mapper               | 1.02.97-75.28                | 1.02.97-77.1                 | 
...
snip
..
| Main Update Repository | yast2-xml                   | 3.1.1-6.4                    | 3.1.2-8.1                    | x86_64

  stderr: tcgetattr: Inappropriate ioctl for device

  err: %!s(<nil>)
[Oct 18 16:24:09] ERROR [172-22-1-25] Failed to scan updatable packages: zypper -q lu Unknown format: v | Main Update Repository | device-mapper               | 1.02.97-75.28                | 1.02.97-77.1                 | x86_64
# Addition Details

Same error displayed with SLES Enterprise Server 11

**Comment by kotakanbe** [comment]
Thanks for reporting.
I will check it next week.

**Comment by flaviu-toader** [comment]
I fixed it in scan/suse.go by using Index instead of HasPrefix in lines 160 and 161. 

It looks like the output from zypper contains some extra bytes that make the check against the desired prefix return false:

Bytes in line are [**1b 5b 3f 31 30 33 34 68** 53 20 7c 20 52 65 70 6f 73 69 74 6f 72 79 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 7c 20 4e 61 6d 65 20 20 20 20 20 20 20 20 20 20 7c 20 43 75 72 72 65 6e 74 20 56 65 72 73 69 6f 6e 20 20 20 20 7c 20 41 76 61 69 6c 61 62 6c 65 20 56 65 72 73 69 6f 6e 20 20 20 20 7c 20 41 72 63 68]

Bytes in prefix are [53 20 7c 20 52 65 70 6f 73 69 74 6f 72 79]

Hope this helps!

**Comment by kotakanbe** [comment]
@flaviu-toader 
I can't reproduce this issue.
Would you please send a Pull Request if you have already solved.

kota

**Comment by KnappeGEIL** [comment]
Hi,

sorry for commenting on this old issue but I've encountered the same issue even with the patch applied.

I have 0 experience with Go but as far as I could see we only ever need to ignore the first two lines of `zypper -q lu` output, so couldn't we do something like this?

```go
func (o *suse) parseZypperLULines(stdout string) (models.Packages, error) {
        updatables := models.Packages{}
        scanner := bufio.NewScanner(strings.NewReader(stdout))
        counter := 0
        for scanner.Scan() {
                if counter <= 1 {
                        continue
                }
                counter++
                line := scanner.Text()
                pack, err := o.parseZypperLUOneLine(line)
                if err != nil {
                        return nil, err
                }
                updatables[pack.Name] = *pack
        }
        return updatables, nil
}
```

Knappe

**Comment by bestmyjj** [comment]
Hi @kotakanbe , i did install the latest vuls v0.6.3 build-20190301_071124_53f4a29

Still i get error report when scaning a remote Suse. Would You please kindly help? appreciate!

  stderr:
  err: %!s(<nil>)
[Mar  7 12:32:44] ERROR [suse] Failed to scan updatable packages: zypper -q lu Unknown format: v | Clone of SLES11-SP3-Updates for x86_64      | ConsoleKit              | 0.2.10-64.65.1                      | 0.2.10-64.69.1        | x86_64
[Mar  7 12:32:44] ERROR [localhost] Error: suse, err: [zypper -q lu Unknown format: v | Clone of SLES11-SP3-Updates for x86_64      | ConsoleKit              | 0.2.10-64.65.1                      | 0.2.10-64.69.1        | x86_64]


One Line Summary
================
suse    Error           Run with --debug to view the details

**Comment by kotakanbe** [comment]
@bestmyjj Fixed. Please try it out.
https://github.com/future-architect/vuls/pull/786
