### ISSUE TITLE
windows support

### ISSUE THREAD

**Issue by mareban** [future-architect/vuls#524]
Hello,

Thanks for this great project that we already use for our linux+docker environment !

Does vuls work or can work for other system like Windows, Cisco, ... please ? Is there something planned ?

For windows,  the issue #470 mention it, but is it working with ssh or winrm for example ??

Thanks for your help.

**Comment by kotakanbe** [comment]
- Windows
There is no concrete plan for now.
Because I don’t use Windows usually :)

- Cisco, ...
It will be possible to detect with NVD. If I (or Someone) implement this Issue.
https://github.com/future-architect/vuls/issues/512

**Comment by mareban** [comment]
Thanks for your reply, but i think the hard work is done and if vuls project take care of environment like Windows and Cisco it we'll' be even better :-) 

Good job and all the best !
