### ISSUE TITLE
Add native Rocket.Chat report support

### ISSUE THREAD

**Issue by Scream85** [future-architect/vuls#526]
# Environment
## Vuls
Hash : 5a0a6ab

## OS
- Vuls Server: CentOS Linux release 7.4.1708

## Go
- Go version: go1.8.3

**Feature request:** Add native rocket.chat report support.
Currently using webhooks for this to rocket.chat but, it floods my channel with vulnerabilities. Also, there is no option to send a report to rocket chat in a summarized format. As a result, the channel which contains the report loads for half minutes to a minute long.

![screen shot 2017-10-26 at 11 05 54](https://user-images.githubusercontent.com/29313645/32047393-b6a39d90-ba3d-11e7-9fab-570b5ee5d9c2.png)

**Comment by kotakanbe** [comment]
Yesterday Vuls Support to Slack Thread format report, is this OK?
https://github.com/future-architect/vuls/pull/525

**Comment by ChrisFernandez** [comment]
nice, will be cool to add Matrix support as well.

**Comment by Scream85** [comment]
@kotakanbe: As I understand from that thread, this adds support to use a legacy connection type to slack, using only an auth key, the url of slack is hard coded. Using auth key is not a problem, but how do I add the url of rocket chat? You commented out that part of the configuration file, where it points to a server.

Also even with slack or with rocket chat, it would be great to have a summary format, where it shows only how server by server, how many packages require update on that server.

I’m doing a new set up, I’m adding around 150 servers to vuls, but if I’ll do a report to rocket chat, it will be useless, it will overload the channel, the chat client. Now tested with only localhost and one server which requires update for 123 packages and already it is too much with the current format.

Thanks!

**Comment by kotakanbe** [comment]
@Scream85 
How about reporting with the -diff option?
