### ISSUE TITLE
 arch linux support

### ISSUE THREAD

**Issue by ReK2Fernandez** [future-architect/vuls#527]
# Environment
 arch linux
Wondering if there is documentation in how to add support for other popular linux distributions like Arch.

**Comment by kotakanbe** [comment]
@ChrisFernandez 

No documents, sorry.  

I think FreeBSD's implementation is simple and helpful.
https://github.com/future-architect/vuls/blob/master/scan/freebsd.go

Basically, Add a detection logic here, 
https://github.com/future-architect/vuls/blob/master/scan/serverapi.go#L74

And then implement the each interface.
see https://github.com/future-architect/vuls/blob/master/scan/freebsd.go

**Comment by ChrisFernandez** [comment]
@kotakanbe Thanks I will take a look and will let you know if I hit any wall.
thanks <3

**Comment by ChrisFernandez** [comment]
@kotakanbe ok I got it to the point is detecting it,  -debug flag helped a lot :) as of now is very very similar to the BSD one.. so next step I guess is to add arch and linux specific cve vulns etc?
```
 blackarch ~ ]$ vuls configtest 
[Oct 27 02:12:33]  INFO [localhost] Validating config...
[Oct 27 02:12:33]  INFO [localhost] Detecting Server/Container OS... 
[Oct 27 02:12:33]  INFO [localhost] Detecting OS of servers... 
[Oct 27 02:12:33]  INFO [localhost] (1/3) Detected: localhost: archlinux BlackArch Linux Live ISO
[Oct 27 02:12:37]  INFO [localhost] (2/3) Detected: matrix: ubuntu 16.10
[Oct 27 02:12:39]  INFO [localhost] (3/3) Detected: chat: ubuntu 16.04
[Oct 27 02:12:39]  INFO [localhost] Detecting OS of containers... 
[Oct 27 02:12:39]  INFO [localhost] Checking dependencies...
[Oct 27 02:12:39]  INFO [chat] Dependencies... No need
[Oct 27 02:12:39]  INFO [matrix] Dependencies... No need
[Oct 27 02:12:39]  INFO [localhost] Dependencies... No need
[Oct 27 02:12:39]  INFO [localhost] Checking sudo settings...
[Oct 27 02:12:39]  INFO [localhost] sudo ... No need
[Oct 27 02:12:39]  INFO [chat] sudo ... No need
[Oct 27 02:12:39]  INFO [matrix] sudo ... No need
[Oct 27 02:12:39]  INFO [localhost] Scannable servers are below...
```
if you can give me a small example like you did I will work on it after the weekend
and maybe have a pull request by end of next week.

Cheers

**Comment by ChrisFernandez** [comment]
@kotakanbe sorry to msg again but I will have time tonight to work on tis after work will be nice to hace a small tip/example on the CVE's part and what to add.. example some CVE's are not distro but linux kernel base or app base like apache so not sure how you guys do this overlaps etc. Thanks!

**Comment by kotakanbe** [comment]
memo: https://security.archlinux.org/

**Comment by ChrisFernandez** [comment]
@kotakanbe  with Arch linux since there is no oval for it, like as bsd I am using a in-house tool arch-audit  just like bsd uses something similar that outputs the CVE and package,  but after running my scan says:
```
[Oct 31 17:58:17]  INFO [localhost] Validating config...                                                                                                          
[Oct 31 17:58:17]  INFO [localhost] cve-dictionary: /home/rek2/cve.sqlite3                                                                                        
[Oct 31 17:58:17]  INFO [localhost] Loaded: /home/rek2/results/2017-10-31T01:16:08-07:00                                                                          
[Oct 31 17:58:17]  INFO [localhost] Fill CVE detailed information with OVAL                                                                                       
[Oct 31 17:58:17] ERROR [localhost] Failed to fill OVAL information: OVAL for archlinux is not implemented yet 
```
Any suggestion? so far I got everything ported and working with no errors.. now I am not sure I am passing the output of arch-audit the right way I will take a look to that tonight.

**Comment by kotakanbe** [comment]
https://github.com/ilpianista/arch-audit
cool! I did not know this.

```
[Oct 31 17:58:17] ERROR [localhost] Failed to fill OVAL information: OVAL for archlinux is not implemented yet 
```
- Amazon , BSD also have no oval.
add archlinux to the switch case condition.
https://github.com/future-architect/vuls/blob/master/report/report.go#L184

**Comment by ChrisFernandez** [comment]
@kotakanbe @all hey thanks for the info.  I am still working on this, I got busy with work this last week and 1/2
but will catch up soon, don't forget abou this :D

**Comment by ReK2Fernandez** [comment]
was showing the project to a friend, and wanted to update, I started a new job in December, about to install Vuln on our Ubuntu/Centos servers so this will be great oportunity for me to also add the arch support.. I left it almost done :( but will prob start from 0 and do it fresh.

**Comment by kotakanbe** [comment]
@ReK2Fernandez Cool!

**Comment by kotakanbe** [comment]
If you still want this, please re-open the issue.

**Comment by ReK2Fernandez** [comment]
Hello @kotakanbe  yes we will need this, since we have 5 arch linux servers and most developers run blackarch and other arch variants. we all moved to gitlab so do not check github almost, and saw this two issues you closed because I logged into my spam email at gmail
