### ISSUE TITLE
0 updatable packages without yum repos configured and internet access

### ISSUE THREAD

**Issue by kerub77** [future-architect/vuls#528]
# Environment
CentOS 7.3
## Vuls

Hash : vuls v0.4.1 5c84ebe

## OS
- Target Server: CentOS 7.3 and RHEL 7.3
- Vuls Server: CentOS 7.3

## Go
- Go version: 1.8.4

## Expected Behavior
localhost       centos7.3.1611  250 updatable packages

## Actual Behavior
localhost       centos7.3.1611  0 updatable packages

## Steps to reproduce the behaviour
enable and disable the repos on target server
[base]
name=CentOS-$releasever - Base
mirrorlist=http://mirrorlist.centos.org/?release=$releasever&arch=$basearch&repo=os&infra=$infra
#baseurl=http://mirror.centos.org/centos/$releasever/os/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
enabled = 1

**Comment by kotakanbe** [comment]
#478

**Comment by kotakanbe** [comment]
Execute the command `repoquery --all --pkgnarrow=updates --qf="%{NAME} %{EPOCH} %{VERSION} %{RELEASE} %{REPO}"` to check for the existence of the update package. I think that it is unavoidable to display 0 when the command execution result is 0.
