### ISSUE TITLE
Feature: Check running linux kernel for CVEs

### ISSUE THREAD

**Issue by lemonsqueeze** [future-architect/vuls#540]
Hi,

Here's a scenario that could be useful to handle:
- Take a fully updated Ubuntu server with 2 Linux kernels installed
- Boot with the old vulnerable kernel.
- Running vuls on it, we get the list of CVEs this kernel has

Right now vuls stops at `0 updatable packages` which is true,
but we get a false sense that the system is secure while it's actually quite vulnerable.

**Comment by kotakanbe** [comment]
The result of scan is displayed as `0 updatable packages`, but are` vuls report` and `vuls tui` showing the vulnerability of the running kernel?

**Comment by kotakanbe** [comment]
Since Vuls is a dynamic scanner, I implemented to display the vulnerability of the running kernel.

**Comment by lemonsqueeze** [comment]
> The result of scan is displayed as 0 updatable packages, but are vuls report and vuls tui showing the vulnerability of the running kernel?

Same with `vuls report` :

    No CVE-IDs are found in updatable packages.
    0 updatable packages

and `vuls tui` currently:

    No vulnerable packages

It doesn't seem to check running kernel, or am I missing something maybe ?

**Comment by kotakanbe** [comment]
@lemonsqueeze 
I couldn't reproduce it.

Please check the following
1. Update vuls to the latest version.
see https://github.com/future-architect/vuls#how-to-update-to-the-latest-version

2. Fetch OVAL database
https://github.com/kotakanbe/goval-dictionary#usage-fetch-oval-data-from-ubuntu

**Comment by kotakanbe** [comment]
Please re-open this issue if you are still in trouble.
