### ISSUE TITLE
Scanning the localhost with vuls docker results in the OS result being debian

### ISSUE THREAD

**Issue by RVIRUS0817** [future-architect/vuls#566]
https://blog.adachin.me/wordpress/archives/6671
Although docker host is coreos, it becomes debian9.2. 
By the way it has already been confirmed that it was debian at CentOS.
please!

**Comment by lorentzca** [comment]
@RVIRUS0817 I guess you scaned container's localhost.

**Comment by RVIRUS0817** [comment]
Just set `-- net host` as the startup option of the container and set the scan target to config.toml as the ip address of the host machine (` ip route | head -1 | cut - d '' - f 3 `).
by lorentzca

**Comment by RVIRUS0817** [comment]
sloved
