### ISSUE TITLE
Vuls report shows 0 updatable packages

### ISSUE THREAD

**Issue by satorutagawa** [future-architect/vuls#585]
# Environment
CentOS 7.4

## Vuls
vuls v0.4.2 
Hash : 4ccbee7

## OS
- Target Server: CentOS 7.4, CentOS 6.9
- Vuls Server: CentOS7.4 (using Docker 17.12.0-ce)

## Go
- Go version: (Docker)

## Expected Behavior
centos7.4.1708	50 updatable packages

## Actual Behavior
centos7.4.1708	0 updatable packages

## Steps to reproduce the behavior
$ sudo docker run --rm --net=host -v ~/.ssh/docker:/root/.ssh:ro -v $PWD:/vuls vuls/vuls scan -config=/vuls/config-docker-test.toml

I'm removing the docker image and pulling the new image once a day from crontab, and this was working fine until 12/12/2017, but I have been getting 0 update packages since. This is unlike #528, since my CentOS-Base [base] repository is enabled, with internet connection.

**Comment by kotakanbe** [comment]
Thanks, 

I am going to fix this issue in next week.

kota

**Comment by kotakanbe** [comment]
@satorutagawa 

Fixed.
Please try it out.

kota

**Comment by satorutagawa** [comment]
Tried it, and it works. Thank you!
