### ISSUE TITLE
vuls scan -cvss-over does not work.

### ISSUE THREAD

**Issue by sheo0147** [future-architect/vuls#59]
vuls scan -cvss-over dose not work.

Steps.
1. go-cve-dictionary fetchnvd -years 2016
2. go-cve-dictionary fetchnvd server
3. vuls scan -(1)
4. vuls scan -cvss-over 7 -(2)

I. At the phase (1), vuls displays "All of the found CVE vulnerabilities data".
II. At the phase (2), vuls displays "All of the found CVE vulnerabilities data", too.

I think phase (2) shows over 7 of the score only, and that I want.

**Comment by kotakanbe** [comment]
Thanks for reporting. 
I fixed the bug.
