### ISSUE TITLE
Send error email when failure occurs (i.e. VM turned off) during report

### ISSUE THREAD

**Issue by satorutagawa** [future-architect/vuls#600]
# Environment
Docker

## Vuls
Hash : d926b7f

## OS
- Target Server: CentOS 7.4
- Vuls Server: Docker on CentOS 7.4

## Go
- Go version: (Docker)

# Current Output
"Failed to fill OVAL information: OVAL for  is not implemented yet"
This is an expected error message, since one of the VM listed in the toml is turned off.
However, the program should send out an email.
It took me a week to realize that vuls wasn't working...

## Expected Behavior
An error email gets sent letting me know that the report command failed.

## Actual Behavior
Program exits. No email notification.

## Steps to reproduce the behaviour
0. Have email notification setup for report (e.g. -format-short-text -to-email -format-one-email)
1. Turn off one of the VM's being monitored
2. Error message in the log, no email

**Comment by kotakanbe** [comment]
@satorutagawa 

Vuls respects KISS principle.
https://en.wikipedia.org/wiki/KISS_principle

You can use other tools to watch logfile and notify errors.
https://serverfault.com/questions/45246/linux-monitor-logs-and-email-alerts
