### ISSUE TITLE
Use ~/.ssh/config

### ISSUE THREAD

**Issue by jody-frankowski** [future-architect/vuls#62]
I have noticed that vuls uses https://godoc.org/golang.org/x/crypto/ssh. I'm not sure if this library allows it but it would be nice to see vuls use the common ssh config.
It is especially important for options such as `ProxyCommand`.

The way I see it, config.toml would only contain the *list* of hosts you'd want to scan, not how to connect to them.

**Comment by kotakanbe** [comment]
Good Idea

**Comment by kotakanbe** [comment]
Hi, @jody-frankowski 
Finally, Vuls supports external ssh command.
#101

You can use the common ssh config.
For details, see https://github.com/future-architect/vuls#-ssh-external-option

Please try it out!
