### ISSUE TITLE
No vulnerable packages

### ISSUE THREAD

**Issue by HuntFrank** [future-architect/vuls#645]
while i run vuls scan,i only got those no details:

**root@ubuntu:~# vuls scan
[May 15 06:16:02]  INFO [localhost] Start scanning
[May 15 06:16:02]  INFO [localhost] config: /root/config.toml
[May 15 06:16:02]  INFO [localhost] Validating config...
[May 15 06:16:02]  INFO [localhost] Detecting Server/Container OS... 
[May 15 06:16:02]  INFO [localhost] Detecting OS of servers... 
[May 15 06:16:02]  INFO [localhost] (1/1) Detected: 127-0-0-1: ubuntu 16.04
[May 15 06:16:02]  INFO [localhost] Detecting OS of containers... 
[May 15 06:16:02]  INFO [localhost] Detecting Platforms... 
[May 15 06:16:14]  INFO [localhost] (1/1) 127-0-0-1 is running on other
[May 15 06:16:14]  INFO [localhost] Scanning vulnerabilities... 
[May 15 06:16:14]  INFO [localhost] Scanning vulnerable OS packages...
[May 15 06:16:14]  INFO [127-0-0-1] apt-get update...

One Line Summary
================
127-0-0-1	ubuntu16.04	1767 installed, 97 updatable

To view the detail, vuls tui is useful.
To send a report, run vuls report -h.**

while i run vuls tui,i got nothing else 'No vulnerable packages'

anyone can help me

**Comment by kotakanbe** [comment]
Is a warning message displayed at reporting?
If warinig is displayed, fetch Ubuntu OVAL before reporting.
For details,see https://github.com/kotakanbe/goval-dictionary#usage-fetch-oval-data-from-ubuntu

**Comment by HuntFrank** [comment]
THANK YOU ,THIS SOLVED MY PROBLEM.
