### ISSUE TITLE
ERROR Failed to fetch cve data from NVD

### ISSUE THREAD

**Issue by HuntFrank** [future-architect/vuls#647]
I can not figure out why,who can help me about this problem.

root@ubuntu:~# for i in {2002..2016}; do go-cve-dictionary fetchnvd -years $i; done
 0 / 1 [---------------------------------------------------------------]   0.00%[May 16 19:54:56]  INFO Fetching... https://static.nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2002.xml.gz
 1 / 1 [===========================================================] 100.00% 30s
[May 16 19:55:26] ERROR Failed to fetch cve data from NVD. err: [Failed to Read NVD feedfile. url: https://static.nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2002.xml.gz, err: unexpected EOF]
 0 / 1 [---------------------------------------------------------------]   0.00%[May 16 19:55:26]  INFO Fetching... https://static.nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2003.xml.gz
 1 / 1 [===========================================================] 100.00% 15s
[May 16 19:55:41]  INFO Fetched 1546 CVEs
[May 16 19:55:41]  INFO Inserting NVD into DB (sqlite3).
[May 16 19:55:41]  INFO Inserting CVEs...
 1546 / 1546 [======================================================] 100.00% 1s
[May 16 19:55:43]  INFO Refreshed 0 Nvds.
 0 / 1 [---------------------------------------------------------------]   0.00%[May 16 19:55:43]  INFO Fetching... https://static.nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2004.xml.gz
 0 / 1 [---------------------------------------------------------------]   0.00%
 0 / 1 [---------------------------------------------------------------]   0.00%[May 16 20:05:43] ERROR Failed to fetch cve data from NVD. err: Timeout Fetching Nvd
 0 / 1 [---------------------------------------------------------------]   0.00%[May 16 20:05:43]  INFO Fetching... https://static.nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2005.xml.gz
 1 / 1 [===========================================================] 100.00% 20s
[May 16 20:06:04] ERROR Failed to fetch cve data from NVD. err: [HTTP error. errs: [Get https://static.nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2005.xml.gz: dial tcp 129.6.13.177:443: connect: connection refused], url: https://static.nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2005.xml.gz]
 0 / 1 [---------------------------------------------------------------]   0.00%[May 16 20:06:04]  INFO Fetching... https://static.nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2006.xml.gz
 0 / 1 [---------------------------------------------------------------]   0.00%
 0 / 1 [---------------------------------------------------------------]   0.00%
 1 / 1 [==========================================================] 100.00% 7m2s
[May 16 20:13:07] ERROR Failed to fetch cve data from NVD. err: [Failed to Read NVD feedfile. url: https://static.nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2006.xml.gz, err: unexpected EOF]
 0 / 1 [---------------------------------------------------------------]   0.00%[May 16 20:13:07]  INFO Fetching... https://static.nvd.nist.gov/feeds/xml/cve/nvdcve-2.0-2007.xml.gz
 0 / 1 [---------------------------------------------------------------]   0.00%

**Comment by kotakanbe** [comment]
I tried it now but no error occurred.

**Comment by kotakanbe** [comment]
If your host is behind a proxy, use -http-proxy option.
https://github.com/kotakanbe/go-cve-dictionary#usage-fetch-nvd-data

**Comment by HuntFrank** [comment]
THANK YOU ,THIS HELPED ME
