### ISSUE TITLE
Some questions about the function of vuls

### ISSUE THREAD

**Issue by y1026** [future-architect/vuls#650]
Hello,

I have some questions.

I wonder if it is correct to understand.

1.Agent-less means Remote Scan Mode and Agent means Local Mode?

2.If you are using Remote Scan Mode, does the installation proceed automatically if the target server does not have a docker or golang package?

3.Generally, system administrators do not want to install packages on servers.
  If vuls does not install the Docker or golang package on the server being scanned, 
  Can not scan for vulnerabilities?

Thanks.

**Comment by kotakanbe** [comment]
> 1.Agent-less means Remote Scan Mode and Agent means Local Mode?

Exactly. Do not run the daemon process even in localscan mode.

> 2.If you are using Remote Scan Mode, does the installation proceed automatically if the target server does not have a docker or golang package?

Scan target server does not need docker nor golang package. vuls connects to the scan target server via ssh and issues a command.

> 3.Generally, system administrators do not want to install packages on servers.
If vuls does not install the Docker or golang package on the server being scanned,
Can not scan for vulnerabilities?

Basically, no packages needed on scan target server.
Depending on the distribution there are packages that need to be installed.
For details, see  https://vuls.io/docs/en/usage-configtest.html#fast-scan-mode
