### ISSUE TITLE
Provide Option to Disable StrictHostkeyChecking

### ISSUE THREAD

**Issue by choseh** [future-architect/vuls#659]
We're currently trying to deploy vuls on kubernetes. Please provide option to disable StrictHostkeyChecking, it's counterproductive in such environments.

**Comment by choseh** [comment]
dupe

**Comment by xu-xiang** [comment]
how to fix？

**Comment by xu-xiang** [comment]
@choseh

**Comment by kotakanbe** [comment]
@xu-xiang 
Please refer to https://github.com/future-architect/vuls/pull/660
