### ISSUE TITLE
"Goval-dictionary fetch-redhat 7" processing stops due to an HTTP 403 error.

### ISSUE THREAD

**Issue by safe-net9** [future-architect/vuls#698]
Execution of "goval-dictionary fetch-redhat 7" will cause the following error log to be output and stop processing. goval-dictionary is using the latest version.

NFO [08-20 | 14: 28: 26] Fetching ... URL = https: //www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL7.xml.bz2
INFO [08-20 | 14: 28: 26] Finished to fetch OVAL definitions
EROR[08-20|14:28:26] Failed to fetch files                    err="Failed to fetch. err: [aborting: could not write to output stream: Expected HTTP Status 200, received: \"403 Forbidden\"]"

Is there any good solution?

**Comment by GielDeBleser** [comment]
it is also happening for other versions:

Redhat-5
```
t=2018-08-20T08:28:23+0000 lvl=info msg="Fetching... " URL=https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL5.xml.bz2
t=2018-08-20T08:28:24+0000 lvl=info msg="Finished to fetch OVAL definitions"
t=2018-08-20T08:28:24+0000 lvl=eror msg="Failed to fetch files" err="Failed to fetch. err: [aborting: could not write to output stream: Expected HTTP Status 200, received: \"403 Forbidden\"]"
```

Redhat-6
```
t=2018-08-20T08:28:39+0000 lvl=info msg="Fetching... " URL=https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL6.xml.bz2
t=2018-08-20T08:28:40+0000 lvl=info msg="Finished to fetch OVAL definitions"
t=2018-08-20T08:28:40+0000 lvl=eror msg="Failed to fetch files" err="Failed to fetch. err: [aborting: could not write to output stream: Expected HTTP Status 200, received: \"403 Forbidden\"]"
```

while fetching manually seem to work:

```
~ curl -IL https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL5.xml.bz2                                  
HTTP/1.1 200 OK
Server: Apache
Last-Modified: Mon, 20 Aug 2018 04:09:48 GMT
ETag: "7f690a26-d9b83-573d61484db00"
Accept-Ranges: bytes
Content-Length: 891779
Content-Type: application/x-bzip2
Date: Mon, 20 Aug 2018 08:35:03 GMT
Connection: keep-alive
```

**Comment by iveskins** [comment]
Me too. When I run
`docker run --rm -it     
-v $PWD:/vuls     
-v $PWD/goval-dictionary-log:/var/log/vuls     
vuls/goval-dictionary fetch-redhat 5
`
it returns
```
INFO[08-20|08:32:58] Fetching...                              URL=https://www.redhat.com/security/data/oval/com.redhat.rhsa-RHEL5.xml.bz2
INFO[08-20|08:32:59] Finished to fetch OVAL definitions
EROR[08-20|08:32:59] Failed to fetch files                    err="Failed to fetch. err: [aborting: could not write to output stream: Expected HTTP Status 200, received: \"403 Forbidden\"]"
```

**Comment by safe-net9** [comment]
It is still NG today. Successfully using curl may be blocked by the user-agent, is not it?

**Comment by kotakanbe** [comment]
@safe-net9 @GielDeBleser @iveskins 

Fixed. Please try it out.

**Comment by safe-net9** [comment]
It's a shame. I tried it with the latest version, but it does not succeed ...

**Comment by GielDeBleser** [comment]
It is working on master, thanks!

**Comment by safe-net9** [comment]
I ran successfully with different IP address and succeeded.

**Comment by iveskins** [comment]
It works for me now. 
I deleted the docker image and re-downloaded
`docker rmi vuls/goval-dictionary`
