### ISSUE TITLE
Vuls -cvedb-url command line option not working

### ISSUE THREAD

**Issue by bgoareguer** [future-architect/vuls#721]
```
docker run --rm -it -v /root/vuls:/vuls vuls/vuls report -config=/vuls/test_config.toml -cvedb-url=http://172.17.0.1:1323
[Oct 16 12:40:40]  INFO [localhost] Validating config...
[Oct 16 12:40:40]  INFO [localhost] Loaded: /vuls/results/2018-10-16T11:24:26Z
[Oct 16 12:40:40]  INFO [localhost] Validating db config...
ERRO[0000] SQLite3 DB path (cvedb) must be a *Absolute* file path. -cvedb-path:
ERRO[0000] SQLite3 DB path (cvedb) is not exist:
```

Vuls hash : [87a77dd95caa0331bbde7a28386f22bea40df45f](https://github.com/future-architect/vuls/commit/87a77dd95caa0331bbde7a28386f22bea40df45f)

It seems that function validateDB in config/config.go does not handle the case of a cve database being run as an http server with sqlite3 database backend.

This issue is similar to issue #589

**Comment by kotakanbe** [comment]
@bgoareguer 
Sorry for late reply.
I will fix this issue in next week 👍

**Comment by kotakanbe** [comment]
@bgoareguer Fixed 👍
