### ISSUE TITLE
"merge" json files in current folder

### ISSUE THREAD

**Issue by Klar** [future-architect/vuls#752]
Feature Request

# What did you do?

Running vuls with two different config.toml. One with Hosts Ubuntu16.04 and one with Ubuntu Hosts 18.04.

# What did you expect to happen?

That from both config.toml files the output json files will be saved in the latest "current" folder.

# What happened instead?

Creates everytime I run vuls a new symlink to the "current" folder. Same goes if I just run vuls with debug and a specific host. 

I ask because I run a python script which checks the result folder and parses that for Icinga Monitoring Output.

* https://github.com/Klar/nagios_plugins/tree/master/check_vuls

# Steps to reproduce the behaviour

Run vuls with a config.toml and a second time with debug and only one host. The "current" folder will only have the host which was run in debug (not all the others which are still "correct" and up to date).

As we monitor a lot of hosts it sometimes happens that vuls does not run correct and the current symlink fodler is empty.

**Comment by kotakanbe** [comment]
How about using -result-dir option?
https://github.com/future-architect/vuls/blob/master/commands/scan.go#L38

**Comment by kotakanbe** [comment]
If you're still having trouble, please re-open this issue.
