### ISSUE TITLE
Error using docker go-cve-dictionary while downloading cves

### ISSUE THREAD

**Issue by ricardo-elevenpaths** [future-architect/vuls#757]
# What did you do? (required. The issue will be **closed** when not provided.)
try to download cve-dictionary

# What did you expect to happen?
no errors while downloading

# What happened instead?
Two errors came up during the downloading of cves

* Current Output

**First error:**
`5073 / 5073 [--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 13 p/s
INFO[01-09|15:38:45] Refreshed 5065 NvdJSONs. 
INFO[01-09|15:38:50] Fetching... https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2011.meta 
INFO[01-09|15:38:50] Fetching... https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.meta 
INFO[01-09|15:38:50] Fetching... https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-recent.meta 
INFO[01-09|15:38:51] Fetched... https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.meta 
INFO[01-09|15:38:51] Fetched... https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-recent.meta 
INFO[01-09|15:38:51] Fetched... https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2011.meta 
INFO[01-09|15:38:51] Up to date: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.json.gz 
INFO[01-09|15:38:51] Up to date: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-recent.json.gz 
INFO[01-09|15:38:51]      Newly: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2011.json.gz 
INFO[01-09|15:38:51] Fetching... https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2011.json.gz 
INFO[01-09|15:38:55] Fetched... https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2011.json.gz 
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xacca1b, 0x16)
	/usr/local/go/src/runtime/panic.go:608 +0x72
runtime.sysMap(0xc074000000, 0x4000000, 0x11d6f18)
	/usr/local/go/src/runtime/mem_linux.go:156 +0xc7
runtime.(*mheap).sysAlloc(0x11bd220, 0x4000000, 0x7f60b365b858, 0x7ffdec91f948)
	/usr/local/go/src/runtime/malloc.go:619 +0x1c7
runtime.(*mheap).grow(0x11bd220, 0x6e, 0x0)
	/usr/local/go/src/runtime/mheap.go:920 +0x42
runtime.(*mheap).allocSpanLocked(0x11bd220, 0x6e, 0x11d6f28, 0x20301c00000000)
	/usr/local/go/src/runtime/mheap.go:848 +0x337
runtime.(*mheap).alloc_m(0x11bd220, 0x6e, 0x410100, 0x7f60b396e500)
	/usr/local/go/src/runtime/mheap.go:692 +0x119
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:759 +0x4c
runtime.(*mheap).alloc(0x11bd220, 0x6e, 0x7ffdec010100, 0x41f105)
	/usr/local/go/src/runtime/mheap.go:758 +0x8a
runtime.largeAlloc(0xdc000, 0x450001, 0x7f60bb763000)
	/usr/local/go/src/runtime/malloc.go:1019 +0x97
runtime.mallocgc.func1()
	/usr/local/go/src/runtime/malloc.go:914 +0x46
runtime.systemstack(0x45ec59)
	/usr/local/go/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1229

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:311 fp=0xc0005f8180 sp=0xc0005f8178 pc=0x45ed50
runtime.mallocgc(0xdc000, 0xa7d2a0, 0xc073f28501, 0x9f2760)
	/usr/local/go/src/runtime/malloc.go:913 +0x896 fp=0xc0005f8220 sp=0xc0005f8180 pc=0x415006
runtime.growslice(0xa7d2a0, 0xc073c6c000, 0x70a, 0x70a, 0x70b, 0xc073c6c000, 0x599, 0x70a)
	/usr/local/go/src/runtime/slice.go:204 +0x145 fp=0xc0005f8288 sp=0xc0005f8220 pc=0x449c05
github.com/kotakanbe/go-cve-dictionary/fetcher/nvd/json.convertToModel(0xc0000ce500, 0xc00fd09570, 0x0, 0x0)
/go/src/github.com/kotakanbe/go-cve-dictionary/fetcher/nvd/json/nvd.go:238 +0x2537 fp=0xc0005f9350 sp=0xc0005f8288 pc=0x8a2af7
github.com/kotakanbe/go-cve-dictionary/fetcher/nvd/json.FetchConvert(0xc000b08510, 0x1, 0x1, 0x1, 0x1, 0xc000b08510, 0x0, 0x1)
	/go/src/github.com/kotakanbe/go-cve-dictionary/fetcher/nvd/json/nvd.go:40 +0x472 fp=0xc0005f98d8 sp=0xc0005f9350 pc=0x8a0182
github.com/kotakanbe/go-cve-dictionary/commands.(*FetchNvdCmd).Execute(0xc000284f00, 0xb6cae0, 0xc00008a010, 0xc000284f60, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/kotakanbe/go-cve-dictionary/commands/fetchnvd.go:207 +0xc46 fp=0xc0005f9e30 sp=0xc0005f98d8 pc=0x8f1da6
github.com/kotakanbe/go-cve-dictionary/vendor/github.com/google/subcommands.(*Commander).Execute(0xc000080070, 0xb6cae0, 0xc00008a010, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/kotakanbe/go-cve-dictionary/vendor/github.com/google/subcommands/subcommands.go:141 +0x2fa fp=0xc0005f9ed8 sp=0xc0005f9e30 pc=0x4ea9aa
github.com/kotakanbe/go-cve-dictionary/vendor/github.com/google/subcommands.Execute(0xb6cae0, 0xc00008a010, 0x0, 0x0, 0x0, 0xc000292848)
	/go/src/github.com/kotakanbe/go-cve-dictionary/vendor/github.com/google/subcommands/subcommands.go:385 +0x5f fp=0xc0005f9f20 sp=0xc0005f9ed8 pc=0x4ec49f
main.main()
	/go/src/github.com/kotakanbe/go-cve-dictionary/main.go:46 +0x23d fp=0xc0005f9f98 sp=0xc0005f9f20 pc=0x8f5d3d
runtime.main()
	/usr/local/go/src/runtime/proc.go:201 +0x207 fp=0xc0005f9fe0 sp=0xc0005f9f98 pc=0x435577
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc0005f9fe8 sp=0xc0005f9fe0 pc=0x460e31

goroutine 19 [syscall, 3 minutes]:
os/signal.signal_recv(0x0)
	/usr/local/go/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
	/usr/local/go/src/os/signal/signal_unix.go:29 +0x41

goroutine 20 [select, 3 minutes]:
database/sql.(*DB).connectionOpener(0xc0001da780, 0xb6caa0, 0xc0002e84c0)
	/usr/local/go/src/database/sql/sql.go:1001 +0xe8
created by database/sql.OpenDB
	/usr/local/go/src/database/sql/sql.go:671 +0x15d

goroutine 21 [select, 3 minutes]:
database/sql.(*DB).connectionResetter(0xc0001da780, 0xb6caa0, 0xc0002e84c0)
	/usr/local/go/src/database/sql/sql.go:1014 +0xfb
created by database/sql.OpenDB
	/usr/local/go/src/database/sql/sql.go:672 +0x193

goroutine 6 [chan receive, 3 minutes]:
github.com/kotakanbe/go-cve-dictionary/util.GenWorkers.func1(0xc0005d48a0)
	/go/src/github.com/kotakanbe/go-cve-dictionary/util/util.go:14 +0x53
created by github.com/kotakanbe/go-cve-dictionary/util.GenWorkers
	/go/src/github.com/kotakanbe/go-cve-dictionary/util/util.go:13 +0x66

goroutine 7 [chan receive, 3 minutes]:
github.com/kotakanbe/go-cve-dictionary/util.GenWorkers.func1(0xc0005d48a0)
	/go/src/github.com/kotakanbe/go-cve-dictionary/util/util.go:14 +0x53
created by github.com/kotakanbe/go-cve-dictionary/util.GenWorkers
	/go/src/github.com/kotakanbe/go-cve-dictionary/util/util.go:13 +0x66

goroutine 8 [chan receive, 3 minutes]:
github.com/kotakanbe/go-cve-dictionary/util.GenWorkers.func1(0xc0005d48a0)
	/go/src/github.com/kotakanbe/go-cve-dictionary/util/util.go:14 +0x53
created by github.com/kotakanbe/go-cve-dictionary/util.GenWorkers
	/go/src/github.com/kotakanbe/go-cve-dictionary/util/util.go:13 +0x66

goroutine 47 [chan receive, 3 minutes]:
github.com/kotakanbe/go-cve-dictionary/util.GenWorkers.func1(0xc00006efc0)
	/go/src/github.com/kotakanbe/go-cve-dictionary/util/util.go:14 +0x53
created by github.com/kotakanbe/go-cve-dictionary/util.GenWorkers
	/go/src/github.com/kotakanbe/go-cve-dictionary/util/util.go:13 +0x66
INFO[01-09|15:42:52] Fetching... https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2012.meta 
INFO[01-09|15:42:52] Fetching... https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.meta 
INFO[01-09|15:42:52] Fetching... https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-recent.meta 
INFO[01-09|15:42:53] Fetched... https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-recent.meta 
INFO[01-09|15:42:53] Fetched... https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.meta 
INFO[01-09|15:42:53] Fetched... https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2012.meta 
INFO[01-09|15:42:53] Up to date: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-recent.json.gz 
INFO[01-09|15:42:53] Up to date: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.json.gz 
INFO[01-09|15:42:53]      Newly: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2012.json.gz 
INFO[01-09|15:42:53] Fetching... https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2012.json.gz 
INFO[01-09|15:42:55] Fetched... https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2012.json.gz 
INFO[01-09|15:43:41] Fetched 5549 CVEs 
INFO[01-09|15:43:41] Inserting NVD into DB (sqlite3). 
INFO[01-09|15:43:41] Inserting fetched CVEs... 
`

**Second error:**
`6156 / 6156 [--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------] 100.00% 20 p/s
INFO[01-09|15:54:47] Refreshed 6155 NvdJSONs. 
INFO[01-09|15:54:51] Fetching... https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2014.meta 
INFO[01-09|15:54:51] Fetching... https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.meta 
INFO[01-09|15:54:51] Fetching... https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-recent.meta 
INFO[01-09|15:54:52] Fetched... https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.meta 
INFO[01-09|15:54:52] Fetched... https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2014.meta 
INFO[01-09|15:54:52] Fetched... https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-recent.meta 
INFO[01-09|15:54:52] Up to date: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-modified.json.gz 
INFO[01-09|15:54:52]      Newly: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2014.json.gz 
INFO[01-09|15:54:52] Up to date: https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-recent.json.gz 
INFO[01-09|15:54:52] Fetching... https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2014.json.gz 
INFO[01-09|15:54:54] Fetched... https://nvd.nist.gov/feeds/json/cve/1.0/nvdcve-1.0-2014.json.gz 
INFO[01-09|15:55:22] Failed to parse CpeURI cpe:2.3:a:disney:where\'s_my_perry?_free:1.5.1:*:*:*:*:android:*:*: Error! cannot have unquoted ? embedded in formatted string.: Parse error 
INFO[01-09|15:55:22] Failed to parse CpeURI cpe:2.3:a:disney:where\'s_my_water?_free:1.9.1:*:*:*:*:android:*:*: Error! cannot have unquoted ? embedded in formatted string.: Parse error 
INFO[01-09|15:55:22] Failed to parse CpeURI cpe:2.3:a:gratta_\&_vinci?_project:gratta_\&_vinci?:0.21.13167.93474:*:*:*:*:android:*:*: Error! cannot have unquoted ? embedded in formatted string.: Parse error 
INFO[01-09|15:55:23] Failed to parse CpeURI cpe:2.3:a:whoisit:who-is-it?_lite_name_caller_time_limited_free:1:*:*:*:*:android:*:*: Error! cannot have unquoted ? embedded in formatted string.: Parse error 
INFO[01-09|15:55:28] Fetched 8491 CVEs 
INFO[01-09|15:55:28] Inserting NVD into DB (sqlite3). 
INFO[01-09|15:55:28] Inserting fetched CVEs... `

Please re-run the command using ```-debug``` and provide the output below.

# Steps to reproduce the behaviour
> echo -e "${RED}Deploy ${NC} go-cve-dictionary" 
> docker pull vuls/go-cve-dictionary
> docker run  --rm  vuls/go-cve-dictionary -v

# Configuration (**MUST** fill this out):
no configuration necessary

**Comment by kotakanbe** [comment]
@ricardo-elevenpaths 

```
fatal error: runtime: out of memory
```

Increase the memory and then re-execute.

**Comment by patrickbaber** [comment]
For the record, I had the same problem with a machine which had 2 GB of RAM. After an upgrade to 4 GB RAM, the "out of memory" message disappeared.
