### ISSUE TITLE
Docker: Panic

### ISSUE THREAD

**Issue by wurstbrot** [future-architect/vuls#76]
I am using docker and try to scan my desktop computer and I am getting a panic.

`docker run -v $(pwd)/config.toml:/app/config.toml -v /home/tpagel/.ssh/id_rsa:/app/id_rsa -v /home/tpagel/.ssh/id_rsa.pub:/app/id_rsa.pub  --name vuls vuls
time="May 28 12:46:39" level=info msg="Opening DB. datafile: /app/cve.sqlite3" 
time="May 28 12:46:39" level=info msg="Migrating DB" 
time="May 28 12:46:39" level=info msg="Starting HTTP Server..." 
time="May 28 12:46:39" level=info msg="Listening on 127.0.0.1:1323" 
time="2016-05-28T12:46:41Z" level=warning msg="[Deprecated] password and keypassword in config file are unsecure. Remove them immediately for a security reason. They will be removed in a future release." 
time="2016-05-28T12:46:41Z" level=info msg="Start scanning (config: /app/config.toml)" 
time="May 28 12:46:41" level=info msg="Validating Config..." 
{"time":"2016-05-28T12:46:41Z","remote_ip":"127.0.0.1","method":"GET","uri":"/health","status":200, "latency":57,"latency_human":"57.4µs","rx_bytes":0,"tx_bytes":0}
time="May 28 12:46:41" level=info msg="Detecting Server OS... " 
time="May 28 12:47:07" level=info msg="(1/1) Detected 172-17-0-1: ubuntu 16.04" 
time="May 28 12:47:07" level=info msg="Detecting Container OS..." 
time="May 28 12:47:07" level=info msg="Scanning vulnerabilities... " 
time="May 28 12:47:07" level=info msg="Check required packages for scanning..." 
time="May 28 12:47:07" level=info msg="Scanning vulnerable OS packages..." 
time="May 28 12:55:33" level=info msg="(1/88) Upgradable: apport-2.20.1-0ubuntu2 -> 2.20.1-0ubuntu2.1" 
panic: send on closed channel

goroutine 91 [running]:
panic(0x9e0240, 0xc8201f8280)
	/usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/future-architect/vuls/scan.(*debian).fillCandidateVersion.func2.1(0xc820087080, 0xc820254cc0, 0xc820254c60, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/future-architect/vuls/scan/debian.go:333 +0x6cf
github.com/future-architect/vuls/scan.(*debian).fillCandidateVersion.func2()
	/go/src/github.com/future-architect/vuls/scan/debian.go:334 +0xe8
github.com/future-architect/vuls/util.GenWorkers.func1(0xc820254d80)
	/go/src/github.com/future-architect/vuls/util/util.go:35 +0x60
created by github.com/future-architect/vuls/util.GenWorkers
	/go/src/github.com/future-architect/vuls/util/util.go:37 +0x6d
`

config.toml:
[servers]

[servers.172-17-0-1]
host         = "172.17.0.1"
port        = "22"
user        = "XXX"
password    = "XXX"
keyPath     = "/app/id_rsa"

**Comment by kotakanbe** [comment]
Thanks for reporting. 
I will check it out tomorrow.

**Comment by kotakanbe** [comment]
Merged just now. https://github.com/future-architect/vuls/pull/82
Now Vuls can print error message instead of nil pointer. 
Please update go-cve-dictionary and vuls.

- $ go get -u github.com/kotakanbe/go-cve-dictionary
- restart the server process of go-cve-dicationary
- $ go get -u github.com/future-architect/vuls

Then try again and paste the error message.
Thanks for your contribution.

**Comment by kotakanbe** [comment]
I can't reproduce the issue. 
So, your cooperation is appreciated!

**Comment by wurstbrot** [comment]
Sorry for the delay. For me, it is working now.
