### ISSUE TITLE
Doc request: add docs related to contributing code

### ISSUE THREAD

**Issue by gurungrahul2** [future-architect/vuls#760]
Would be great to have a doc to setup vuls and develop for beginners like me.

**Comment by kotakanbe** [comment]
Sorry, there is no document for developers.
I think it is good to set a break point, and step execution by vscode etc.
Entry point is (here)[https://github.com/future-architect/vuls/blob/master/main.go#L32]

**Comment by kotakanbe** [comment]
It would be nice if someone had written a document for developers.
Please push to https://github.com/vulsdoc/vuls
