### ISSUE TITLE
Fix/upgrade slack.go or pin nlopes/slack to 0.4.0

### ISSUE THREAD

**Issue by b3tyar** [future-architect/vuls#770]
# What did you do? (required. The issue will be **closed** when not provided.)
Install vuls on Centos7

# What did you expect to happen?
make install for vuls is working without issues

# What happened instead?
# github.com/future-architect/vuls/report
report/slack.go:99:52: cannot use msgText(r) (type string) as type slack.MsgOption in argument to api.PostMessage
report/slack.go:99:52: cannot use ParentMsg (type slack.PostMessageParameters) as type slack.MsgOption in argument to api.PostMessage
report/slack.go:108:6: unknown field 'Attachments' in struct literal of type slack.PostMessageParameters
report/slack.go:111:52: cannot use msgText(r) (type string) as type slack.MsgOption in argument to api.PostMessage
report/slack.go:111:52: cannot use params (type slack.PostMessageParameters) as type slack.MsgOption in argument to api.PostMessage
# github.com/future-architect/vuls/report [github.com/future-architect/vuls/report.test]
report/slack.go:99:52: cannot use msgText(r) (type string) as type slack.MsgOption in argument to api.PostMessage
report/slack.go:99:52: cannot use ParentMsg (type slack.PostMessageParameters) as type slack.MsgOption in argument to api.PostMessage
report/slack.go:108:6: unknown field 'Attachments' in struct literal of type slack.PostMessageParameters
report/slack.go:111:52: cannot use msgText(r) (type string) as type slack.MsgOption in argument to api.PostMessage
report/slack.go:111:52: cannot use params (type slack.PostMessageParameters) as type slack.MsgOption in argument to api.PostMessage
make: *** [vet] Error 2

* Current Output

Please re-run the command using ```-debug``` and provide the output below.

# Steps to reproduce the behaviour
No need for extra steps, just try to follow the install steps from the documentation.
The recent change of nlopes/slack is breaking the build. I had to delete the github.com/nlopes/slack and pin the version to 0.4.0 with:
dep ensure --add github.com/nlopes/slack@0.4.0

# Configuration (**MUST** fill this out):

* Go version (`go version`):
go version go1.11.5 linux/amd64

* Go environment (`go env`):
GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build940329232=/tmp/go-build -gno-record-gcc-switches"

* Vuls environment:

Hash : vuls v0.6.2 build-20190128_133342_256c99f

To check the commit hash of HEAD
$ vuls -v

or

$ cd $GOPATH/src/github.com/future-architect/vuls 
$ git rev-parse --short HEAD 

* config.toml:
Not made yet at this point
* command:
mkdir -p $GOPATH/src/github.com/future-architect
cd $GOPATH/src/github.com/future-architect
git clone https://github.com/future-architect/vuls.git
cd vuls
make install

**Comment by kotakanbe** [comment]
@b3tyar 
Thanks for reporting. 
I will update deps and fix the code.

**Comment by kotakanbe** [comment]
Pinned.
https://github.com/future-architect/vuls/blob/master/Gopkg.toml#L39
