### ISSUE TITLE
Ubuntu 12 not supported?

### ISSUE THREAD

**Issue by fnzv** [future-architect/vuls#774]
# What did you do? (required. The issue will be **closed** when not provided.)
vuls scan vulnubuntu (Trying to scan an ubuntu 12 server from a fresh install on a centos 7 vuls server)

# What did you expect to happen?
End the scan and then see from the report the vulnerable packages

# What happened instead?
`[root@vuls-scanner centos]# vuls scan vulnubuntu
[Feb  2 14:35:31]  INFO [localhost] Start scanning
[Feb  2 14:35:31]  INFO [localhost] config: /home/centos/config.toml
[Feb  2 14:35:31]  INFO [localhost] Validating config...
[Feb  2 14:35:31]  INFO [localhost] Detecting Server/Container OS...
[Feb  2 14:35:31]  INFO [localhost] Detecting OS of servers...
[Feb  2 14:35:31]  INFO [localhost] (1/1) Detected: vulnubuntu: ubuntu 12.04
[Feb  2 14:35:31]  INFO [localhost] Detecting OS of containers...
[Feb  2 14:35:31]  INFO [localhost] Checking Scan Modes...
[Feb  2 14:35:31]  INFO [localhost] Detecting Platforms...
[Feb  2 14:35:32]  INFO [localhost] (1/1) vulnubuntu is running on aws
[Feb  2 14:35:32]  INFO [localhost] Scanning vulnerabilities...
[Feb  2 14:35:32]  INFO [localhost] Open boltDB: /home/centos/cache.db
[Feb  2 14:35:32]  INFO [localhost] Scanning vulnerable OS packages...
[Feb  2 14:35:32]  INFO [vulnubuntu] Scanning in deep mode
[Feb  2 14:35:32] ERROR [vulnubuntu] Failed to scan installed packages: Debian: Failed to parse package line: ,,0.6.15-2ubuntu9.6,,
]Feb  2 14:35:32] ERROR [localhost] Error: vulnubuntu, err: [Debian: Failed to parse package line: ,,0.6.15-2ubuntu9.6,,`
* Current Output

Please re-run the command using ```-debug``` and provide the output below.
(i have offuscated my IP and the long list of packages, i kept the last where there is the parsing issue)
`
[Feb  2 14:36:38] DEBUG [vulnubuntu] Executing... dpkg-query -W -f="\${binary:Package},\${db:Status-Abbrev},\${Version},\${Source},\${source:Version}\n"
[Feb  2 14:36:38] DEBUG [vulnubuntu] execResult: servername: vulnubuntu
  cmd: /bin/ssh -tt -o StrictHostKeyChecking=yes -o LogLevel=quiet -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=auto -o ControlPath=/root/.vuls/controlmaster-%r-vulnubuntu.%p -o Controlpersist=10m root@XX.XX.XX.XX -p 22 stty cols 1000; dpkg-query -W -f="\${binary:Package},\${db:Status-Abbrev},\${Version},\${Source},\${source:Version}\n"
.... (some packages..)
....
,,6.0-4ubuntu2.5,,
,,1:0.156.14.11,update-manager,
,,0.119ubuntu8.6,update-notifier,
,,1.5-0ubuntu7.2,,
,,0.100.0-12,,
,,1:005-1,,
,,2.20.1-1ubuntu3,,
,,2.20.1-1ubuntu3,util-linux,
,,2:7.3.429-2ubuntu2.1,,
,,2:7.3.429-2ubuntu2.1,vim,
,,2:7.3.429-2ubuntu2.1,vim,
,,2:7.3.429-2ubuntu2.1,vim,
,,0.5.3-5ubuntu1,,
,,0.6.5-1,,
,,1.13.4-2ubuntu1,,
,,0.52.11-2ubuntu10,newt,
,,0.1.32,whoopsie-daisy,
,,2011.04.28-1ubuntu3,,
,,30~pre9-5ubuntu2,,
,,0.7.3-6ubuntu2.1,,
,,1:1.0.6-1,,
,,2.5-1ubuntu1.3,xkeyboard-config,
,,0.13,,
,,5.1.1alpha+20110809-3,xz-utils,
,,5.1.1alpha+20110809-3,,
,,1:1.2.3.4.dfsg-3ubuntu4,zlib,

  stderr:
  err: %!s(<nil>)
[Feb  2 14:36:38] ERROR [vulnubuntu] Failed to scan installed packages: Debian: Failed to parse package line: ,,0.6.15-2ubuntu9.6,,
]Feb  2 14:36:38] ERROR [localhost] Error: vulnubuntu, err: [Debian: Failed to parse package line: ,,0.6.15-2ubuntu9.6,,

One Line Summary
[Reboot Required] vulnubuntu    Error           Run with --debug to view the details`

# Steps to reproduce the behaviour
Clean install of vuln, Ubuntu 12.04.2 LTS, Precise Pangolin

# Configuration (**MUST** fill this out):
```
[servers.vulnubuntu]
host         = "XX.XX.XX.XX"
port        = "22"
user        = "root"
scanMode     = ["deep"]

```

* Go version (`go version`):
go version go1.10.1 linux/amd64
* Go environment (`go env`):
`GOARCH="amd64"
GOBIN=""
GOCACHE="/root/.cache/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/root/go"
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build186266263=/tmp/go-build -gno-record-gcc-switches"`
* Vuls environment:

Hash : `vuls v0.6.2 build-20190131_115007_256c99f`

Atm i'm running vuls on a centos 7 machine installed following your doc and the ubuntu machine is connected remotely

**Comment by kotakanbe** [comment]
@fnzv 

Ubuntu 12.04 Has Reached End of Life.
https://lists.ubuntu.com/archives/ubuntu-announce/2017-April/000221.html

The vulnerability database `OVAL` is no longer updated.
https://people.canonical.com/~ubuntu-security/oval/

So, Vuls does not support Ubuntu 12.

**Comment by fnzv** [comment]
Ok thank you, i was testing your software with some old OS so i can check the CVEs.
Because on newer OS i only get `[Reboot required]`
