### ISSUE TITLE
NotFixedYet status on vuls IHM

### ISSUE THREAD

**Issue by nicocolt** [future-architect/vuls#779]
# What did you do? (required. The issue will be **closed** when not provided.)
Analyse issue on the web IHM

# What did you expect to happen?
When flag NotYetFixed set to false, the NewPackageVer should be different than PackageVer

# What happened instead?
When flag NotYetFixed set to false, the NewPackageVer is the same than PackageVer
* Current Output

Please re-run the command using ```-debug``` and provide the output below.

# Steps to reproduce the behaviour
docker run .... vuls/vuls scan
docker run ... vuls/vuls report
docker run ... -p 5111:5111 vuls/vulsrepo

# Configuration (**MUST** fill this out):

* Go version (`go version`):
vuls/vuls:latest docker image
* Go environment (`go env`):
vuls/vuls:latest docker image
* Vuls environment:
vuls/vuls:latest docker image
Hash : ____

To check the commit hash of HEAD
$ vuls -v

or

$ cd $GOPATH/src/github.com/future-architect/vuls 
$ git rev-parse --short HEAD 

* config.toml:
[servers]

[servers.192.168.0.2]
host         = "192.168.0.2"
port        = "22"
user        = "cloud"
keyPath     = "/root/.ssh/id_rsa" # path to ssh private key in docker
sshNative   = 1

[cveDict]
type = "sqlite3"
path = "CVE"

[ovalDict]
type = "sqlite3"
path = "OVAL"

[gost]
type = "sqlite3"
path = "GOST"

* command:

**Comment by kotakanbe** [comment]
This repository is being maintained.
https://github.com/ishiDACo/vulsrepo

He is preparing a docker container now. please wait.
