### ISSUE TITLE
Requesting examples in documentation for Github security alerts and vuls

### ISSUE THREAD

**Issue by StackKorora** [future-architect/vuls#788]
# What did you do? (required. The issue will be **closed** when not provided.)
When installing Vuls, it pulls down a LOT of repos that it relies on. I was hoping to have Vuls monitor these as well, but I don't quite understand the documentation example for monitoring Github repositories as found here: https://vuls.io/docs/en/usage-scan-non-os-packages.html

# What did you expect to happen?
I think it would be good if vuls had a template that came along with it which set up Vuls to monitor the Vuls repo along with the others it depends on. Short of that, it would be helpful at least to have a more clear example in the documentation with Vuls being the example.

For brevity, I removed the other questions in the template as they aren't quite relevant since this is a feature request / documentation improvement request.

Thank you.

**Comment by kotakanbe** [comment]
I fixed it to make it easier to understand.
https://vuls.io/docs/en/usage-scan-non-os-packages.html#usage-integrate-with-github-security-alerts
