### ISSUE TITLE
Server mode for rhel is not implemented yet

### ISSUE THREAD

**Issue by MogiePete** [future-architect/vuls#799]
# What did you do?

curl \
  -X POST \
  -H "Content-Type: text/plain" \
  -H "X-Vuls-Server-Name: testserver" \
  -H "X-Vuls-OS-Family: rhel" \
  -H "X-Vuls-OS-Release: 7.6" \
  -H "X-Vuls-Kernel-Release: 3.10.0-957.10.1.el7.x86_64" \
  --data-binary "`rpm -qa --queryformat "%{NAME} %{EPOCHNUM} %{VERSION} %{RELEASE} %{ARCH}\n"`" \
  http://${VULS_SERVER}:5515/vuls

# What did you expect to happen?
Server to scan endpoint.

# What happened instead?

* Current Output

[Apr  8 18:45:10] ERROR [localhost] Server mode for rhel is not implemented yet

# Steps to reproduce the behaviour

Running Server from docker container. Ubuntu and Debian scans are working. 

# Configuration (**MUST** fill this out):

* Vuls environment:

Hash : vuls  build-20190221_050916_53f4a29

* config.toml:

[cveDict]
type = "mysql"
url = "vuls:vulspa55@tcp(svrmariadbc01:3306)/vuls_cve?parseTime=true"

[ovalDict]
type = "mysql"
url = "vuls:vulspa55@tcp(svrmariadbc01:3306)/vuls_goval?parseTime=true"

#[gost]
#type = "sqlite3"
#SQLite3Path = "/vuls/gost/gost.sqlite3"

[servers]

[servers.testserver]
host                = "192.168.50.239"
port                = "22"
user                = "root"
keyPath             = "/root/.ssh/id_rsa"
scanMode            = [ "fast-root" ]

* command:

docker run --rm -it -p 5515:5515  -v ~/.ssh:/root/.ssh:ro   -v /docker/vuls:/vuls   -v /docker/vuls/vuls-log:/var/log/vuls -v /etc/localtime:/etc/localtime:ro -e "TZ=America/New_York" vuls/vuls server -listen=0.0.0.0:5515 -to-localfile -format-json -debug

**Comment by knqyf263** [comment]
Please try using `redhat` instead of `rhel`.
https://github.com/future-architect/vuls/blob/7192ae12875b1cf6773a585007a3cc0b2fb5de0b/config/config.go#L45-L93

**Comment by MogiePete** [comment]
@knqyf263 

I was looking at the wrong file. This fixed the issue. Now I just need to figure out why the reports are different when I run a scan from the server compared to initiating a scan from the remote client.

**Comment by knqyf263** [comment]
How is it different?

**Comment by MogiePete** [comment]
I've attached two different scans.

One if done by running vuls scan and the other is done by triggering the scan with the API.

The API produces the following warning regarding OVAL and redhat Enterprise that running vuls scan does not.

[Apr  9 03:12:31]  WARN [localhost] OVAL entries of redhat Enterprise are not found. It's recommended to use OVAL to improve scanning accuracy. For details, see https://github.com/kotakanbe/goval-dictionary#usage , Then report with --ovaldb-path or --ovaldb-url flag

[scans.zip](https://github.com/future-architect/vuls/files/3057000/scans.zip)

**Comment by MogiePete** [comment]
@knqyf263 

This issue has been resolved. The one liner from the docs picks up Enterprise and not 7.6. I modified what is being sent to Vuls and it now works as expected.

**Comment by knqyf263** [comment]
That's great!
