### ISSUE TITLE
Errors when using fish shell

### ISSUE THREAD

**Issue by budric** [future-architect/vuls#8]
Hi,

Great software package!  Thank you.

When the remote user is configured to use fish shell, the check fails when executing:
set -o pipefail; rpm -qa --queryformat '%{NAME}	%{VERSION}	%{RELEASE}'
I believe the issue is tab characters between %{NAME}	%{VERSION}	%{RELEASE} headers.  

It's not an issue with unknown option as debug output suggests.

Some debug output from vuls near the error:
```
[Apr  6 17:18:41] DEBUG [zabbix:22] SSH executed. cmd: set -o pipefail; rpm -qa --queryformat '%{NAME}	%{VERSION}	%{RELEASE}
', status: <nil>
stdout: 
set: Unknown option '-o'
Standard input: set -o pipefail; rpm -qa --queryformat '%{NAME}	%{VERSION}	%{RELEASE}
                ^
hawkey	0.5.8	2.git.0.202b194.el7
<snip> rest of my packages in similar format </snip>

stderr: 

[Apr  6 17:18:41] ERROR [zabbix:22] Failed to scan installed packages

```

**Comment by thorerik** [comment]
It does seem to rely on bash on the remote end, the issue is infact set -o pipefail, fish doesn't have -o, zsh(which I use) doesn't have the option pipefail until zsh 5.0.8

**Comment by budric** [comment]
Yes, you're right it is the set -o pipefail.  My mistake.

**Comment by kotakanbe** [comment]
I am installing fish-shell (first time in my life)

**Comment by kotakanbe** [comment]
fish shell is so cool!!!

**Comment by kotakanbe** [comment]
fish-shell is awesome. 
But It seems difficult to support fish-shell or old zsh.
Please create a user with bash login shell on target servers.

**Comment by kotakanbe** [comment]
I will update README about this. 
Thanks for reporting.

**Comment by kotakanbe** [comment]
update README.md
https://github.com/future-architect/vuls/commit/ac77cc1f8759e1ee62ca928c8c8d99a49b06d0e4
