### ISSUE TITLE
no cve in the json report

### ISSUE THREAD

**Issue by thinksabin** [future-architect/vuls#842]
# What did you do? (required. The issue will be **closed** when not provided.)
scanned a machine with vuls

# What did you expect to happen?
good report as before

# What happened instead?
no cve in the json report file
* Current Output

Please re-run the command using ```-debug``` and provide the output below.

# Steps to reproduce the behaviour

# Configuration (**MUST** fill this out):

* Go version (`go version`):
go version go1.11 linux/amd64
<img width="613" alt="nocve_vuls_report" src="https://user-images.githubusercontent.com/6102027/59551502-537dce00-8f9a-11e9-89b8-9c66f1acda76.png">

* Go environment (`go env`):
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/ubuntu/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/ubuntu/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build294737416=/tmp/go-build -gno-record-gcc-switches"

* Vuls environment:

Hash : ____

To check the commit hash of HEAD
$ vuls -v
vuls v0.7.0 build-20190612_071308_fcc2c1e

or

$ cd $GOPATH/src/github.com/future-architect/vuls 
$ git rev-parse --short HEAD 

* config.toml:

* command:

**Comment by kotakanbe** [comment]
@thinksabin 
Update to the latest version, retry and please paste a stdout of the report command.

**Comment by kotakanbe** [comment]
Also update Go to the latest version.

**Comment by thinksabin** [comment]
ok sure, i will go the fresh start and let you know.

**Comment by thinksabin** [comment]
So far i have tested, vuls working fine with updated code and go version.

os = ubuntu 16.04
vuls v0.7.0 build-20190615_143533_8c3b305
go version go1.12 linux/amd64

For few curious questions i will join slack channel as before. thanks @kotakanbe

**Comment by kotakanbe** [comment]
Sounds Good :)
