### ISSUE TITLE
Support Debian 10 buster

### ISSUE THREAD

**Issue by kotakanbe** [future-architect/vuls#844]
https://lists.debian.org/debian-devel-announce/2019/06/msg00003.html

Will be released on Jul/6

**Comment by segatomo** [comment]
Scanning and reporting works properly. 
<img width="892" alt="スクリーンショット 2019-09-20 14 28 20" src="https://user-images.githubusercontent.com/29967880/65302380-ff484280-dbb5-11e9-9e18-9e56cf1ba0c4.png">
<img width="1189" alt="スクリーンショット 2019-09-20 14 28 39" src="https://user-images.githubusercontent.com/29967880/65302381-ffe0d900-dbb5-11e9-83fe-f6cd3e9f6ace.png">
