### ISSUE TITLE
Docker ssh problem

### ISSUE THREAD

**Issue by britjumper** [future-architect/vuls#856]
I am trying to setup Vuls to run in docker (Version 18.09.5) on Ubuntu 18.04 and am having a few issues. 

I have followed the instructions https://vuls.io/docs/en/install-with-docker.html and also at https://vuls.io/docs/en/tutorial-docker.html. 

For step 0 in the Scan using docker I created the directories in /home/$myusername/ (where $myusername is the username on the system)

I ran ssh-keygen -t rsa to create my key pairs and verified that I could log onto the system using these.

I created a config.toml file in the /home/$myusername directory that contains the following:

[servers]

[servers.127-0-0-1]
host = "127.0.0.1"
port = "22"
user = "$myusername"
keypath = "/home/$myusername/.ssh/id_rsa"

When I run the command "docker run --rm -it    -v ~/.ssh:/root/.ssh:ro     -v $PWD:/vuls     -v $PWD/vuls-log:/var/log/vuls     vuls/vuls configtest"

I get the following error message and I don't seem to be able to resolve it.

[Jun 28 06:46:46] ERROR [localhost] Error loading /vuls/config.toml
If you update Vuls and get this error, there may be incompatible changes in config.toml
Please check config.toml template : https://vuls.io/docs/en/usage-settings.html
127-0-0-1 is invalid. keypath: /home/$myusername/.ssh/id_rsa not exists:
    github.com/future-architect/vuls/config.TOMLLoader.Load
        /go/src/github.com/future-architect/vuls/config/tomlloader.go:114

**Comment by kotakanbe** [comment]
Please try with this.
```
[servers]

[servers.127-0-0-1]
host = "127.0.0.1"
port = "22"
user = "$myusername"
keypath = "/root/.ssh/id_rsa"
```

The keypath needs to define the path in the docker container.

**Comment by kaurbhupinder** [comment]
I tried this solution but still getting the error

**Comment by britjumper** [comment]
We managed to get it working. It needed the keypath as kotakanbe suggested, but I think there is a missing step in the documentation where you need to copy the certificate into the appropriate docker container.

**Comment by kotakanbe** [comment]
Added JPEG to the doc.
https://vuls.io/docs/en/install-with-vulsctl.html
