### ISSUE TITLE
Unsupport family: centos

### ISSUE THREAD

**Issue by shigechika** [future-architect/vuls#874]
# What did you do? (required. The issue will be **closed** when not provided.)

vuls report

# What did you expect to happen?

# What happened instead?
```
ERROR [localhost] Failed to fill with OVAL:
    github.com/future-architect/vuls/report.FillCveInfo
        /home/vuls/go/src/github.com/future-architect/vuls/report/report.go:179
  - Failed to get centos OVAL info by package: oval.request{packName:"ilmbase", versionRelease:"1.0.1-6.1.el6", newVersionRelease:"1.0.1-6.1.el6", arch:"x86_64", binaryPackNames:[]string(nil), isSrcPack:false}, err:
    github.com/future-architect/vuls/oval.getDefsByPackNameFromOvalDB
        /home/vuls/go/src/github.com/future-architect/vuls/oval/util.go:243
  - Unsupport family: centos
```
* Current Output

Please re-run the command using ```-debug``` and provide the output below.

# Steps to reproduce the behaviour

# Configuration (**MUST** fill this out):

* Go version (`go version`):

go version go1.11.5 linux/amd64

* Go environment (`go env`):

GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vuls/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/vuls/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/lib/golang"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build711366701=/tmp/go-build -gno-record-gcc-switches"

* Vuls environment:

vuls v0.8.4 build-20190718_131452_d770034
go-cve-dictionary v0.3.1 5fe5261
goval-dictionary v0.2.0 0e718b4
gost bbbf56d

* config.toml:

* command:

**Comment by parasit** [comment]
Similar error:
```
ERROR [localhost] Failed to fill with OVAL:
    github.com/future-architect/vuls/report.FillCveInfo
        /home/bart/golang/src/github.com/future-architect/vuls/report/report.go:179
  - Failed to get centos OVAL info by package: oval.request{packName:"libidn", versionRelease:"1.28-4.el7", newVersionRelease:"1.28-4.el7", arch:"x86_64", binaryPackNames:[]string(nil), isSrcPack:false}, err:
    github.com/future-architect/vuls/oval.getDefsByPackNameFromOvalDB
        /home/bart/golang/src/github.com/future-architect/vuls/oval/util.go:243
  - Unsupport family: centos
```
GO version `go version go1.12.7 linux/amd64`

**Comment by parasit** [comment]
Similar error:
```
ERROR [localhost] Failed to fill with OVAL:
    github.com/future-architect/vuls/report.FillCveInfo
        /home/bart/golang/src/github.com/future-architect/vuls/report/report.go:179
  - Failed to get centos OVAL info by package: oval.request{packName:"libidn", versionRelease:"1.28-4.el7", newVersionRelease:"1.28-4.el7", arch:"x86_64", binaryPackNames:[]string(nil), isSrcPack:false}, err:
    github.com/future-architect/vuls/oval.getDefsByPackNameFromOvalDB
        /home/bart/golang/src/github.com/future-architect/vuls/oval/util.go:243
  - Unsupport family: centos
```
GO version `go version go1.12.7 linux/amd64`
