### ISSUE TITLE
Library Vulns Scan doesn't output affectedPackages and confidences attributes.

### ISSUE THREAD

**Issue by okuken** [future-architect/vuls#878]
# What did you do? (required. The issue will be **closed** when not provided.)
Library Vulns Scan (setting composer.lock file)
see:<https://vuls.io/docs/ja/usage-scan-non-os-packages.html#options>

# What did you expect to happen?
report includes below attributes:
* affectedPackages (or cpeURIs)
* confidences

# What happened instead?
above attributes were not included.
It makes that VulsRepo can't show detected vulnerabilities.

# Steps to reproduce the behaviour
Library Vulns Scan (setting composer.lock file)
see:<https://vuls.io/docs/ja/usage-scan-non-os-packages.html#options>

# Configuration (**MUST** fill this out):
```
[servers.name]
host        = "xxx.xxx.xxx.xxx"
port        = "xx"
user        = "xxxxxx"
keyPath     = "xxxxxx"
findLock    = false
lockfiles   = [
    "xxxxxxx/composer.lock",
]
```
* Vuls environment:

Hash : vuls v0.8.5 build-20190801_135356_4326bef

**Comment by kotakanbe** [comment]
This repository is being maintained.
https://github.com/ishiDACo/vulsrepo

He is preparing a docker container now. please wait.
