### ISSUE TITLE
Vuls failed to scan updatable packages

### ISSUE THREAD

**Issue by nicocolt** [future-architect/vuls#879]
Hello,

Vuls is unable to scan updatable packages with the following error:

err:_ Failed to scan updatable packages:
    github.com/future-architect/vuls/scan.(*redhatBase).scanPackages
        /go/src/github.com/future-architect/vuls/scan/redhatbase.go:246
  - Unknown format: Skipping unreadable repository '/etc/yum.repos.d/yum.repo', fields: [Skipping unreadable repository '/etc/yum.repos.d/yum.repo']:
    github.com/future-architect/vuls/scan.(*redhatBase).parseUpdatablePacksLine
        _/go/src/github.com/future-architect/vuls/scan/redhatbase.go:413

My OS is a CentOS 7.6 and i run vuls through docker on a remote server with the following command:

docker run --rm -it -v /root/vuls/id_rsa:/root/.ssh/id_rsa:ro -v /root/vuls:/vuls -v /root/vuls/vuls-log:/var/log/vuls -v /root/.ssh/known_hosts:/root/.ssh/known_hosts:ro  -v /etc/localtime:/etc/localtime:ro -e "TZ=Europe/Paris" vuls/vuls scan -config=/vuls/config.toml

Here is the full stack trace:

[Aug  5 13:34:39]  INFO [localhost] Start scanning
[Aug  5 13:34:39]  INFO [localhost] config: /vuls/config.toml
[Aug  5 13:34:39]  INFO [localhost] Validating config...
[Aug  5 13:34:39]  INFO [localhost] Detecting Server/Container OS...
[Aug  5 13:34:39]  INFO [localhost] Detecting OS of servers...
[Aug  5 13:34:39]  INFO [localhost] (1/1) Detected: proxyssh: centos 7.6.1810
[Aug  5 13:34:39]  INFO [localhost] Detecting OS of static containers...
[Aug  5 13:34:39]  INFO [localhost] Detecting OS of containers...
[Aug  5 13:34:39]  INFO [localhost] Checking Scan Modes...
[Aug  5 13:34:39]  INFO [localhost] Detecting Platforms...
[Aug  5 13:34:39]  INFO [localhost] (1/1) proxyssh is running on aws
[Aug  5 13:34:39]  INFO [localhost] Detecting IPS identifiers...
[Aug  5 13:34:39]  INFO [localhost] (1/1) proxyssh has 0 IPS integration
[Aug  5 13:34:39]  INFO [localhost] Scanning vulnerabilities...
[Aug  5 13:34:39]  INFO [localhost] Scanning vulnerable OS packages...
[Aug  5 13:34:39]  INFO [proxyssh] Scanning in fast mode
[Aug  5 13:34:47]  WARN [proxyssh] err: Failed to scan updatable packages:
    github.com/future-architect/vuls/scan.(*redhatBase).scanPackages
        /go/src/github.com/future-architect/vuls/scan/redhatbase.go:246
  - Unknown format: Skipping unreadable repository '/etc/yum.repos.d/yum.repo', fields: [Skipping unreadable repository '/etc/yum.repos.d/yum.repo']:
    github.com/future-architect/vuls/scan.(*redhatBase).parseUpdatablePacksLine
        /go/src/github.com/future-architect/vuls/scan/redhatbase.go:413

**Comment by kotakanbe** [comment]
Fix the yum settings and check the `Skipping unreadable repository '/etc/yum.repos.d/yum.repo'` does not appear.

https://github.com/future-architect/vuls/blob/3ffed18e027f8bdfe657f9783c3d61bb25e0193e/scan/redhatbase.go#L351
