### ISSUE TITLE
OVAL entries of ubuntu 19.04 are not found. Fetch OVAL before reporting.

### ISSUE THREAD

**Issue by lacksfish** [future-architect/vuls#882]
Preface, I did this on ubuntu 18.04 successfully, then upgraded to 19.04, now I experience the following error:

Running `sudo goval-dictionary fetch-ubuntu 19` did not resolve this issue

### What did you do? (required. The issue will be **closed** when not provided.)
`sudo vuls tui`

### What did you expect to happen?
Terminal shows vulnerability report.

### What happened instead?
Error, missing OVAL entries for ubuntu 19.04
* Current Output
```
[Aug 14 23:42:55]  INFO [localhost] localhost: 0 CVEs are detected with Library
[Aug 14 23:42:55] ERROR [localhost] Failed to fill with OVAL: OVAL entries of ubuntu 19.04 are not found. Fetch OVAL before reporting. For details, see https://github.com/kotakanbe/goval-dictionary#usag
```
Please re-run the command using ```-debug``` and provide the output below.
```
[Aug 14 23:47:10] DEBUG [localhost] Check whether oval fetched: ubuntu 19.04
[Aug 14 23:47:10] ERROR [localhost] Failed to fill with OVAL: OVAL entries of ubuntu 19.04 are not found. Fetch OVAL before reporting. For details, see https://github.com/kotakanbe/goval-dictionary#usage
```

### Configuration (**MUST** fill this out):

* Go version (`go version`): 1.12.8

* Go environment (`go env`):
```
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/me/.cache/go-build"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/me/go"
GOPROXY=""
GORACE=""
GOROOT="/usr/local/go"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build151783119=/tmp/go-build -gno-record-gcc-switches"

```
* Vuls environment:

Hash : vuls v0.8.5 build-20190814_200040_4326bef

* config.toml:
```
[cveDict]
type = "sqlite3"
SQLite3Path = "/correct_path/vuls/cve.sqlite3"

[ovalDict]
type = "sqlite3"
SQLite3Path = "/correct_path/vuls/oval.sqlite3"

[servers]

[servers.localhost]
host = "localhost"
port = "local"
scanMode = [ "fast" ]
#scanMode = ["fast", "fast-root", "deep", "offline"]

```

**Comment by MaineK00n** [comment]
This issue seems to solve it.
https://github.com/kotakanbe/goval-dictionary/issues/91

Perhaps the correction code is also presented, so it seems possible if the PR (not created) is merged.

**Comment by DaikiYamakawa** [comment]
@lacksfish @MaineK00n Thank you for your report.
The cause of this problem is that the codename of Ubuntu19 became end of life.
I made pull request for support to other code name of ubuntu19.
If you want to change of detail, check https://github.com/kotakanbe/goval-dictionary/pull/96
Please check exec ```goval-dictionary fetch-ubuntu 19```

If you still have trouble, please reopen this issue.
