### ISSUE TITLE
Failed to fill with OVAL:- OVAL entries of ubuntu 17.10 are not found. 

### ISSUE THREAD

**Issue by kaurbhupinder** [future-architect/vuls#889]
# What did you do? (required. The issue will be **closed** when not provided.)
I want to scan image having Ubuntu 17.10 OS

# What did you expect to happen?
It should list all vulnerabilities that are present inside image

# What happened instead?

ERROR [localhost] Failed to fill with OVAL:
    github.com/future-architect/vuls/report.FillCveInfo
        /go/src/github.com/future-architect/vuls/report/report.go:178
  - OVAL entries of ubuntu 17.10 are not found. Fetch OVAL before reporting. For details, see https://github.com/kotakanbe/goval-dictionary#usage:
    github.com/future-architect/vuls/report.FillWithOval
        /go/src/github.com/future-architect/vuls/report/report.go:328

* Current Output

Please re-run the command using ```-debug``` and provide the output below.

ERROR [localhost] Failed to fill with OVAL:
    github.com/future-architect/vuls/report.FillCveInfo
        /go/src/github.com/future-architect/vuls/report/report.go:178
  - OVAL entries of ubuntu 17.10 are not found. Fetch OVAL before reporting. For details, see https://github.com/kotakanbe/goval-dictionary#usage:
    github.com/future-architect/vuls/report.FillWithOval
        /go/src/github.com/future-architect/vuls/report/report.go:328

# Steps to reproduce the behaviour

# Configuration (**MUST** fill this out):

* Go version (`go version`):

* Go environment (`go env`):

* Vuls environment:

Hash : ____

To check the commit hash of HEAD
$ vuls -v

or

$ cd $GOPATH/src/github.com/future-architect/vuls 
$ git rev-parse --short HEAD 

* config.toml:

* command:

**Comment by lacksfish** [comment]
Possibly related: https://github.com/future-architect/vuls/issues/882

**Comment by DaikiYamakawa** [comment]
@kaurbhupinder @lacksfish Thank you for your reports.
Vuls can not support ubuntu17 because ubuntu17 is end of life.
Please check https://wiki.ubuntu.com/Releases

If you still have trouble, reopen issue please.
