### ISSUE TITLE
VulsRepo is giving different number of vulnerabilities than normal report we get

### ISSUE THREAD

**Issue by kaurbhupinder** [future-architect/vuls#890]
When I check using following command I get different number of vulnerabilities than what I get using VulsRepo?

docker run --rm -it \
    -v ~/.ssh:/root/.ssh:ro \
    -v $PWD:/vuls \
    -v $PWD/vuls-log:/var/log/vuls \
    -v /etc/localtime:/etc/localtime:ro \
    vuls/vuls report \
    -format-short-text \
    -config=./config.toml # path to config.toml in docker

so which one is giving correct results?

**Comment by kotakanbe** [comment]
Maybe Vulsrepo is wrong.

**Comment by kotakanbe** [comment]
This repository is being maintained.
https://github.com/ishiDACo/vulsrepo

He is preparing a docker container now. please wait.
