### ISSUE TITLE
Not able to point this db cache location in a flag

### ISSUE THREAD

**Issue by klauern** [future-architect/vuls#911]
# What did you do? (required. The issue will be **closed** when not provided.)
I'm attempting to run the `vuls server` from a read-only filesystem, using Redis as a backend to store and retrieve all of the information.  When I start it up, passing in all of the necessary information to speak to a Redis instance, it fails saying it is unable to fill the Library.

These lines appear to load the Library, with no way to customize it:

https://github.com/future-architect/vuls/blob/d5a3e5c2c5c227118fdf1d306766ae9f297f9d3b/report/report.go#L153-L155

And the error seems to occur here:

https://github.com/future-architect/vuls/blob/1fbd516b83017e6bd5425ac36b20a8f8ca693a3e/libmanager/libManager.go#L17

* Current Output

```
time="2019-09-20T02:37:19Z" level=error msg="Failed to fill with Library dependency: failed to mkdir: mkdir db: read-only file system" prefix=localhost
```

**Comment by kotakanbe** [comment]
Fixed. 
Use -trivy-cachedb-dir :)

https://github.com/future-architect/vuls/search?q=-trivy-cachedb-dir&unscoped_q=-trivy-cachedb-dir&type=Code
