### ISSUE TITLE
Cannot import scan results in elasticsearch

### ISSUE THREAD

**Issue by mareban** [future-architect/vuls#917]
Hello,

I've installed the latest version of vuls and i'd like to import results in ES and visualize them in Kibana !

Before, the solution was to use vuls-log-converter (last update in 2017 !) , but something change in the JSON results, that cannot be parsed anymore and i've got some errors !

Is there a way to import the results in ES or do you plan to add the possibility in future ?

Thanks for your help and for this great project.

**Comment by mareban** [comment]
Can someone help me please ?

Thx.

**Comment by kotakanbe** [comment]
I thinks vuls-log-converter is NOT maintained anymore. 
You can normalize nested JSON output using convert tools such as pandas.io.json.json_normalize.
https://pandas.pydata.org/pandas-docs/version/0.22/generated/pandas.io.json.json_normalize.html

**Comment by kazuminn** [comment]
@mareban I have released https://github.com/kazuminn/vulsbeat .
This help you import JSONs.
