### ISSUE TITLE
Results with "to-http" option is not working

### ISSUE THREAD

**Issue by Hi-Fi** [future-architect/vuls#926]
# What did you do? (required. The issue will be **closed** when not provided.)
Tried to do https://vuls.io/docs/en/usage-server.html#example-collect-the-scan-results-from-vuls-agent.

# What did you expect to happen?
Scan from vuls pushed to server. Report is both displayed in stdout and stored to server (as server is configured to store the results). 

# What happened instead?
Error message (using real server produced same error):
```
[Dec  4 06:49:47] ERROR [localhost] Failed to read from JSON: Invalid path: /vuls/results/http:/localhost:5515/vuls:
    github.com/future-architect/vuls/report.JSONDir
        /go/src/github.com/future-architect/vuls/report/util.go:600
```

* Current Output
```
vuls report -debug -to-http http://${VULS_SERVER}:5515/vuls
[Dec  4 06:49:47] ERROR [localhost] Failed to read from JSON: Invalid path: /vuls/results/http:/localhost:5515/vuls:
    github.com/future-architect/vuls/report.JSONDir
        /go/src/github.com/future-architect/vuls/report/util.go:600
```

# Steps to reproduce the behaviour
```
container run --rm -it --entrypoint /bin/sh vuls/vuls
cat << EOF >> config.toml
[servers]

[servers.localhost]
host = "localhost"
port = "local"
EOF
vuls scan
export VULS_SERVER=localhost
vuls report -to-http http://${VULS_SERVER}:5515/vuls
```

# Configuration (**MUST** fill this out):

* Go version (`go version`): N/A
* Go environment (`go env`): N/A

* Vuls environment: 

Hash : vuls v0.9.0 build-20191101_010448_69214e0

To check the commit hash of HEAD
$ vuls -v

or

$ cd $GOPATH/src/github.com/future-architect/vuls 
$ git rev-parse --short HEAD 

* config.toml:
```
[servers]

[servers.localhost]
host = "localhost"
port = "local"
```

* command:
`vuls report -to-http http://${VULS_SERVER}:5515/vuls`

**Comment by ohsh6o** [comment]
I too am suffering from this issue. Is there anything I can do to troubleshoot or assist?

**Comment by segatomo** [comment]
It seems that the documentation was incorrect. With these commands, it worked properly.
```
$ vuls scan
$ export VULS_SERVER=127.0.0.1
$ export VULS_HTTP_URL=http://${VULS_SERVER}:5515/vuls
$ vuls report -to-http
```

**Comment by kotakanbe** [comment]
Please reopen if you are still in trouble.
