### ISSUE TITLE
Update Alpine version in the image.

### ISSUE THREAD

**Issue by tokyowizard** [future-architect/vuls#940]
Would updating the alpine version to 3.11 be ok?
https://github.com/future-architect/vuls/blob/be659ae094bbf5392bc94bdb732b8c26f05da4c5/Dockerfile#L14

Support for [3.7 has ended](https://wiki.alpinelinux.org/wiki/Alpine_Linux:Releases).

**Comment by kotakanbe** [comment]
https://github.com/future-architect/vuls/pull/1002
