### ISSUE TITLE
Add support for `-result-dir` to be a S3 bucket and path for server and scan.

### ISSUE THREAD

**Issue by tokyowizard** [future-architect/vuls#941]
For `vuls server` and `vuls scan`, can the results dir be an S3 bucket, instead of local directory?

When running `vuls scan`, the JSON files are saved in a results-dir directory, locally. Then the JSON files need to be transferred to the Report server's results-dir. If the results-dir is an S3 bucket, the number of actions can be reduced, because the transfer can be excluded.
https://github.com/future-architect/vuls/blob/f738622c287516b1774ffae4d8941f752b0d78a0/img/vuls-architecture-localscan.png

Also each host machine can have a cronjob, which runs a [one-line command](https://vuls.io/docs/en/usage-server.html#example-one-liner-scan) `curl -X POST ... http://$VULS_SERVER:5515/vuls`. If the Vuls Server saves to an S3 bucket, each host machine does not need to save the result locally and transfer the results.

For example, it would be nice to be able do something like:
```
vuls server -results-dir=s3://bucket_name/results_dir -to-s3
vuls scan   -results-dir=s3://bucket_name/results_dir -to-s3
```

**Comment by kotakanbe** [comment]
I don't need this feature at the moment. If you need it, please send us a pull request.

**Comment by tokyowizard** [comment]
Thank you for considering it. I will close this issue for now.
