### ISSUE TITLE
report -to-email smtp not support ssl？

### ISSUE THREAD

**Issue by xxywyc** [future-architect/vuls#945]
hello，I use email for notification in my report, the SMTP use port 465 and requires SSL.
i use the "vuls report -ignore-unfixed -to-email -config=config.toml" , but email cannot be sent. 
Is SSL not supported by default?
# the -debug info:
```
[Mar 28 17:35:03] ERROR [localhost] Failed to report. err: Failed to send emails:
    github.com/future-architect/vuls/report.(*emailSender).Send
        /go/src/github.com/future-architect/vuls/report/email.go:128
  - EOF
```
# the smtp config like:
```
[email]
smtpAddr      = "smtp.xxx.xxx.com"
smtpPort      = "465"
user          = "xxxx"
password      = "xxxxxxx"
from          = "xxxx@xxxx.com"
to            = ["xxxx@xxxx.com"]
subjectPrefix = "[vuls]" 
```
thanks！

**Comment by kotakanbe** [comment]
LTGM

**Comment by DaikiYamakawa** [comment]
@xxywyc Thank you for your reports. I have added SMTPS when we use the command ```vuls report -to-email```
