### ISSUE TITLE
Support Ubuntu 20.04

### ISSUE THREAD

**Issue by kotakanbe** [future-architect/vuls#952]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%240%20Funded-%2300A156.svg" />](https://issuehunt.io/r/future-architect/vuls/issues/952)

http://releases.ubuntu.com/20.04/

20.04 will be released on 4/23.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Submitted pull Requests
- [#982 Supported Ubuntu20.04](https://issuehunt.io/r/future-architect/vuls/pull/982)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/future-architect/vuls/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by Vorty** [comment]
Ubuntu 20 now released.

**Comment by DaikiYamakawa** [comment]
Support Ubuntu20.04
Fixes #982
