### ISSUE TITLE
Export Report to XML failing

### ISSUE THREAD

**Issue by MoCityMM** [future-architect/vuls#954]
Go is a new language for me so, didn't know how to fix this issue... I do have 'encoding/xml' in the 'util.go' file but, didn't work. Here is the error:

ERROR [localhost] Failed to write JSON:
    github.com/future-architect/vuls/report.FillCveInfos
        /home/cdev-1/Go/src/github.com/future-architect/vuls/report/report.go:106
  - Failed to write summary report:
    github.com/future-architect/vuls/report.overwriteJSONFile
        /home/cdev-1/Go/src/github.com/future-architect/vuls/report/util.go:412
  - Failed to Marshal to XML:
    github.com/future-architect/vuls/report.LocalFileWriter.Write
        /home/cdev-1/Go/src/github.com/future-architect/vuls/report/localfile.go:98
  - xml: unsupported type: map[config.IPS]string

**Comment by kotakanbe** [comment]
https://github.com/chrismalek/jsontoxml-cli
This may be helpful.
