### ISSUE TITLE
Documentation: go-cve-dictionary fetchnvd doesnt work

### ISSUE THREAD

**Issue by kmulvey** [future-architect/vuls#96]
the readme suggests running the following:

```$ for i in {2002..2016}; do go-cve-dictionary fetchnvd -years $i; done```

but when running this I got the following error:
```
fetchnvd:
	fetchnvd
		[-last2y]
		[-dbpath=/path/to/cve.sqlite3]
		[-debug]
		[-debug-sql]
```

I ended up using "-last2y", should the readme be updated?

**Comment by kotakanbe** [comment]
Probably, go-cve-dictionary is old.
Please try following commands.
```
go get -u -v github.com/kotakanbe/go-cve-dictionary
go get -u -v github.com/future-architect/vuls
```
