### ISSUE TITLE
Support to Fedora

### ISSUE THREAD

**Issue by asrocha** [future-architect/vuls#976]
Hi, 
firstly,  Thanks for the amazing tool, it is very usefull, I 'm trying learn Go, if I got it certainly I will contribute !!!
but for now,  I 'm a python guy !!!
my question is  possible add Fedora to  supported OS, I think it is not so hard becouse fedora is Redhat based like, Centos and oracle linux !!

**Comment by kazuminn** [comment]
@asrocha Hi. Thank you for question.
is that so. I think I can do it. But you can't do the same with yum, which is used to detect redhat and centOS, with redora dnf.
That's why I can't do it now.
If dnf is updated in the future, it may be possible to do it.

**Comment by asrocha** [comment]
@kazuminn In fedora there yum command it is possible use then ?
Can you show me the yum commands are used on Centos/Oracle, maybe I can translate to DNF, or do similar.

Thanks

**Comment by kazuminn** [comment]
@asrocha I am making support-fedora because it may be technically implemented.
It may not be possible, but it will take time. Have been waiting.

Why do you want to scan fedora? If so, I might be motivated.

**Comment by asrocha** [comment]
@kazuminn  for now, fedora  maybe is the main desktop distribution for Red Hat World,  and Fedora server  and the fedora Silverblue are 2 greats system. After that CoreOs a container image system now is fedora coreos.
but, you are right, better to focus  efforts on ubuntu server 20.04. Fedora is not so important on server world.
Thanks for attention.
If you show me documentation maybe I get a pull request to suport fedora with code and not only questions!!
I thinking in create same scripts (python) to store results in a db and use grafana for dashbording it.
I really loved this tool
