### ISSUE TITLE
I want "ProxyJump" to be supported in "config.toml".

### ISSUE THREAD

**Issue by shirousa** [future-architect/vuls#987]
# Overview

Please support the connection via the connection to the Jump server only with "config.toml".
"config.toml" だけで、Jumpサーバーへの接続を経由した接続をサポートしてほしいです。

# Background

I have a large number of servers, but I am unable to connect directly via SSH.
多数のサーバーを管理しておりますが、SSH で直接接続することができないポリシーです。

Currently, we are using ProxyJump of ".ssh / config" together to connect via Jump Server.
現在は、 ".ssh/config" の ProxyJump を併用し、 Jump サーバー経由の接続を実施しております。
https://www.redhat.com/sysadmin/ssh-proxy-bastion-proxyjump

The file to be managed is divided, and there are omissions in the settings.
管理するファイルが分割されており、対応漏れ等が発生しております。

Therefore, I want to complete it all with "config.toml", and ask for ProxyJump support.
そのため、全て "config.toml" で完結させたく、 ProxyJumpのサポートをお願いしたいです。

From "ssh version 7.3", JumpSever can be specified by "-J" option.
"ssh version 7.3" から "-J" オプションにより JumpSever が指定できるようになっております。
``` $ ssh -J <bastion-host> <remote-host> ```
``` $ ssh -J <bastion1>,<bastion2> <remote>```

Could you add a feature so that this option can be specified when calling "ssh" in the vuls program?
vuls プログラム内で "ssh" をコールする際に、本オプションを指定できるよう、機能を追加いただけないでしょうか？

よろしくお願いいたします。

**Comment by kazuminn** [comment]
@shirousa 
投稿ありがとう。
申し訳ない。その機能は現時点では実装できません。
vulsはsshにcrypto/sshライブラリを使っているのだが、それがproxyjump(-j)に対応していないからです。
こんごサポートすれば、実装できます。

Thank you for posting.
I'm sorry. The feature cannot be implemented at this time.
vuls uses crypto / ssh library for ssh, but it doesn't support proxyjump (-j).
If it supports it in the future, I can implement it

**Comment by shirousa** [comment]
@kazuminn 

Thank you for your answer.
回答をいただきありがとうございます。

I understood the situation, including the background.
現在の状況について、背景も含めて理解いたしました。

If the "crypto / ssh" library supports ProxyJump, please consider adding a new feature.
"crypto/ssh" ライブラリが ProxyJump に対応した際は、改めて機能追加の検討をよろしくお願いいたします。

Thank you for your continued support of great software.
素晴らしいソフトウェアのサポートに感謝いたします。

**Comment by wraithm** [comment]
I too would love a "ProxyJump" or "ProxyCommand" to be supported in vuls. It's unfortunate that crypto/ssh doesn't support these features. I found a golang library that does do an equivalent to ProxyCommand. I don't know if this package is reasonable for production use, but it's possibly something to consider: https://github.com/appleboy/easyssh-proxy

I would be very hesitant to use something non-standard, like this, but I just figured I'd point it out.

Vulsで「ProxyJump」または「ProxyCommand」のサポートをも希望します。 「Easyssh-proxy」は「ProxyCommand」が可能なgolangパッケージです。それが良いかどうかわかりません：https://github.com/appleboy/easyssh -proxy

下手日本語ごめんなさい。

**Comment by DaikiYamakawa** [comment]
@wraithm @shirousa @kazuminn Thank you for your reports. I have added ProxyJump func(#1004 ) but I haven't been able to prepare and test a proxy environment.
So, Please try it in your environment before merge.

# How to check pull request
```console
$ cd /path/to/vuls/
$ git fetch origin pull/1004/head:1004
$ git checkout 1004
$ make build
$ ./vuls scan host
```

**Comment by kotakanbe** [comment]
@DaikiYamakawa Thanks for sending a PR.

@wraithm @shirousa
proxyjump is now supported, so please help me test it. If it works, I'll merge it into master.

@kazuminn 
If no option is specified, the external command ssh will be used.
https://github.com/future-architect/vuls/blob/ebe5f858c88d4f8c5e72df5126987783c37d63cb/commands/scan.go#L79
If you specify ssh-native-insecure, go's native SDK will be used. (But the current implementation of Vuls doesn't check the host key, so --ssh-native-insecure is not recommended)

**Comment by kotakanbe** [comment]
Merged. 
Please reopen If you have any problems :)
