### ISSUE TITLE
Scan results for non-OS packages are incorrect

### ISSUE THREAD

**Issue by BigTree975** [future-architect/vuls#990]
I would like to scan the relevant vulnerability of NginX-1.15.12

I tried to use CPE to obtain the relevant vulnerability information of Nginx-1.15.12, but I did not get the correct result. However, When I searched on the NVD website using CPE, I could get the correct result. 
When I looked up nginx-1.15.12 locally on PET.sqlite3, I also looked up that this version of Nginx is also available in the SQLite library.

# Configuration (**MUST** fill this out):

- go version 
go1.14.4 linux/amd64

* Go environment (`go env`):
export GOROOT=/usr/local/go
export GOPATH=$HOME/go
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

* Vuls environment:

Hash : ____

To check the commit hash of HEAD
$ vuls -v
vuls v0.9.6 build-20200602_020743_d18e7a7

* config.toml:
<img width="589" alt="屏幕快照 2020-06-03 19 48 51" src="https://user-images.githubusercontent.com/33783361/83635193-61c36080-a5d6-11ea-8ba3-f4af478d3c1d.png">

* command:

<img width="1438" alt="屏幕快照 2020-06-03 19 49 14" src="https://user-images.githubusercontent.com/33783361/83635206-69830500-a5d6-11ea-85aa-2c1d3f458a94.png">

the result of vuls report -format-json
<img width="1440" alt="屏幕快照 2020-06-03 19 48 40" src="https://user-images.githubusercontent.com/33783361/83635313-99caa380-a5d6-11ea-807c-b70cb968ee47.png">

We are strictly in accordance with the official website of the tutorial step by step installation, configuration, use

**Comment by kotakanbe** [comment]
memo:
https://nvd.nist.gov/vuln/search/results?form_type=Advanced&cves=on&cpe_version=cpe%3a%2fa%3anginx%3anginx%3a1.15.12

**Comment by segatomo** [comment]
It works fine in my environment.
Would you try `$ go-cve-dictionary fetchnvd -last2y`?
<img width="726" alt="スクリーンショット 2020-06-04 14 10 19" src="https://user-images.githubusercontent.com/29967880/83722942-cd5e0a00-a678-11ea-95aa-c783aa7a2edf.png">
