### ISSUE TITLE
libraries section is wrong

### ISSUE THREAD

**Issue by wagdez** [future-architect/vuls#999]
Scan two Pipfile.lock files...
run vuls scan
check the libraries section in the outpu

Expected result is that each entry in the library will have the Path for one file and the Libs metioned in this entry is for this file.

What happens, is that the first file is Ok, and the second file contains the libs of the first file as well!

reproduces in the latest version

after little investigation, I found that the bug is in the new fanal version which is used...
	github.com/aquasecurity/fanal v0.0.0-20200505074551-9239a362deca
the function GetLibraries concatenates the libraries from all lock files incrementally…

this patches fixes the issue
`diff --git a/analyzer/analyzer.go b/analyzer/analyzer.go
index 9454478..83bb662 100644
--- a/analyzer/analyzer.go
+++ b/analyzer/analyzer.go
@@ -318,8 +318,8 @@ func GetLibraries(filesMap extractor.FileMap) ([]types.Application, error) {
 			return nil, xerrors.Errorf(“failed to get libraries: %w”, err)
 		}
-		var lis []types.LibraryInfo
 		for filePath, libs := range libMap {
+			var lis []types.LibraryInfo
 			for _, lib := range libs {
 				lis = append(lis, types.LibraryInfo{
 					Library: lib,`

**Comment by kotakanbe** [comment]
Probably fixed.
https://github.com/future-architect/vuls/pull/1012
